apache/uniffle

- server/src/main/java/com/tencent/rss/server/ShuffleTaskManager.java
Store shuffleId int to be consistent with other data structure
Store shuffleId int to be consistent with other data structure, like the `partitionsToBlockIds` and `commitLocks`.
No
No need.
> [Minor] Store shuffleId int to be consistent with other data structure

- common/src/main/java/com/tencent/rss/common/config/ConfigOptions.java
- common/src/main/java/com/tencent/rss/common/config/RssConf.java
- common/src/test/java/com/tencent/rss/common/config/ConfigOptionTest.java
Introduce the asList method in ConfigOptions
It’s necessary when getting the list of values from the config directly.
No
UT
> Introduce the asList method in ConfigOptions

- CONTRIBUTING.md
- README.md
- docs/client_guide.md
- docs/coordinator_guide.md
- docs/index.md
- docs/server_guide.md
- pom.xml
- spark-patches/spark-2.4.6_dynamic_allocation_support.patch
- spark-patches/spark-3.1.2_dynamic_allocation_support.patch
- spark-patches/spark-3.2.1_dynamic_allocation_support.patch
Add license header to files so we can minimize files to exclude in apache-rat check.
Asf podding issues
License header is visible in docs, just like [spark](https://github.com/apache/spark/blob/master/docs/index.md?plain=1), for example:
https://github.com/kaijchen/incubator-uniffle/blob/rat-exclude/docs/index.md
CI: https://github.com/kaijchen/incubator-uniffle/runs/7176341386?check_suite_focus=true
> Minimize apache-rat excluded files

- client-mr/pom.xml
- client-spark/common/pom.xml
- client-spark/spark2/pom.xml
- client-spark/spark3/pom.xml
- client/pom.xml
- common/pom.xml
- coordinator/pom.xml
- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/spark2/pom.xml
- integration-test/spark3/pom.xml
- internal-client/pom.xml
- pom.xml
- proto/pom.xml
- server/pom.xml
- storage/pom.xml
Change or add module names in `pom.xml`.
The `artifactId` is not changed.
For clarity and consistency.
No.
```console
$ mvn clean package -T1C -DskipTests -Pspark3
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Uniffle 0.6.0-snapshot:
[INFO] 
[INFO] Apache Uniffle ..................................... SUCCESS [  3.894 s]
[INFO] Apache Uniffle Protocols ........................... SUCCESS [ 11.798 s]
[INFO] Apache Uniffle Common .............................. SUCCESS [  6.869 s]
[INFO] Apache Uniffle Coordinator ......................... SUCCESS [ 13.413 s]
[INFO] Apache Uniffle Internal Client ..................... SUCCESS [  3.790 s]
[INFO] Apache Uniffle Storage ............................. SUCCESS [  9.902 s] …
```
> Update module names

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/SingleStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
There will be NPE problem when process the event if application was cleared already
Fix a critical bug which cause resource leak. 
No
UT is added
> [Bug] Fix NPE problem when process the event if application was cleared already

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
1. Correct the config description
2. Fix typo
Typo
No
No need.
> Correct the config description and fix typo

- README.md
Add CI and Codecov badges in README.
It's easier to see the CI and Codecov result.
And you can click the badges for details.
No.
See: https://github.com/kaijchen/incubator-uniffle/blob/badges/README.md
> Add CI and Codecov badges in README

- common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java
- common/src/test/java/org/apache/uniffle/common/config/ConfigOptionTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessCandidatesCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessClusterLoadCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/AccessCandidatesCheckerHdfsTest.java
- integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkSQLWithDelegationShuffleManager.java
- integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkSQLWithDelegationShuffleManagerFallback.java
- server/src/main/java/org/apache/uniffle/server/HealthCheck.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/test/java/org/apache/uniffle/server/HealthCheckTest.java
Use asList method in some existing configOptions
Directly use the asList method in ConfigOptions to get the config list values, and then avoid splitting values by users.
No.
UTs.
> [Followup] Use asList method in some existing configOptions

- .asf.yaml
Update the asf.yaml to reduce the PR notifications to dev@
Currently there're some many gitbox notifications to dev@, which is actually duplicated with GH notification itself, so trying to reduce this in dev@
No
NA
> [INFRA] Improve asf.yaml to reduce the notifications

- common/src/test/java/org/apache/uniffle/common/BufferSegmentTest.java
- common/src/test/java/org/apache/uniffle/common/PartitionRangeTest.java
- common/src/test/java/org/apache/uniffle/common/RemoteStorageInfoTest.java
1. Add `BufferSegmentTest` and `PartitionRangeTest`.
2. Improve `RemoteStorageInfoTest`.
1. A program with high test coverage has more of its source code executed during testing, which suggests it has a lower chance of containing undetected bugs.
3. Demostrates how to improve test coverage with the help of Codecov.
No production code change.
https://app.codecov.io/gh/kaijchen/incubator-uniffle/commit/cf7f30b1ee216bd6a36ba0eea37f14e7bc0ccbcb
> [TEST] Improve code coverage in rss-common

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileReader.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryClientReadHandler.java
Fix the log of incorrectly bound class.
No
No
> Fix the log of incorrectly bound class

- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/spark2/pom.xml
- integration-test/spark3/pom.xml
Fix misspelled word "integration" in pom.xml
Fix typo.
No.
No need.
> [TYPO] Fix misspelled word "integration"

- client-spark/spark3/src/test/java/org/apache/spark/shuffle/TestUtils.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- pom.xml
- proto/pom.xml
Upgrade gRPC to support Apple Silicon.
To support build on Apple M1 chips.
Run `mvn clean install` on master branch
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Remote Shuffle Service Project Parent POM 0.6.0-snapshot:
[INFO]
[INFO] Remote Shuffle Service Project Parent POM .......... SUCCESS [  2.106 s]
[INFO] Remote Shuffle Service Protocols ................... FAILURE [  2.082 s]
[INFO] Remote Shuffle Service Common ...................... SKIPPED
[INFO] Coordinator ........................................ SKIPPED
[INFO] rss-internal-client ................................ SKIPPED
[INFO] Shuffle Storage .................................... SKIPPED
[INFO] Shuffle Server ..................................... SKIPPED
[INFO] …
```
> Upgrade gRPC to support Apple Silicon

- common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigUtils.java
- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/PartitionRangeAssignmentTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleUploader.java
1. reduce the raw use of parameterized class
2. use `Collections.singletonList` instead of `Arrays.asList` for single element
3. add type annotation for some method signature and variable declaration
This makes javac and IntelliJ's compiler happy
NO
Existing tests should be sufficient.
> [Improvement] reduce compiler warnings

- CONTRIBUTING.md
- README.md
- pom.xml
1. update README.md to reflect JDK requirement
2. exclude json-smart in hadoop-common
3. update CONTRIBUTION.md to change the project name and polish wording
> For the first two changes: 
When building uniffle locally, I noticed that it requires JDK1.8 to build and suspicious maven-default-http-blocker for json-smart.
```
[WARNING] net.minidev:json-smart/maven-metadata.xml failed to transfer from http://0.0.0.0/ during a previous attempt. 
This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-default-http-blocker has elapsed or updates are forced.
Original error: Could not transfer metadata net.minidev:json-smart/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for …
```
> [Chore]: document update and build time optimize

- README.md
- docs/client_guide.md
Supplement doc about assignment tags
Supplement doc about assignment tags
Yes
No need
> Supplement doc about assignment tags

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileReader.java
Fix bug when call `inputstream.skip()` which may return unexpected result
Get exception messages as following, and it maybe caused by unexpected data from `Local` storage
```
com.tencent.rss.common.exception.RssException: Unexpected crc value for blockId[9992363390829154], expected:2562548848, actual:2244862586
at com.tencent.rss.client.impl.ShuffleReadClientImpl.readShuffleBlockData(ShuffleReadClientImpl.java:184)
at org.apache.spark.shuffle.reader.RssShuffleDataIterator.hasNext(RssShuffleDataIterator.java:99)
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
```
No
With current UTs
> [Bug] Fix skip() api maybe skip unexpected bytes which makes inconsistent data

- storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileReader.java
Fix bug when call `inputstream.skip()` which may return unexpected result
Get exception messages as following, and it maybe caused by unexpected data from `Local` storage
```
com.tencent.rss.common.exception.RssException: Unexpected crc value for blockId[9992363390829154], expected:2562548848, actual:2244862586
at com.tencent.rss.client.impl.ShuffleReadClientImpl.readShuffleBlockData(ShuffleReadClientImpl.java:184)
at org.apache.spark.shuffle.reader.RssShuffleDataIterator.hasNext(RssShuffleDataIterator.java:99)
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
```
No
With current UTs
> [Bug] Fix skip() api maybe skip unexpected bytes which makes inconsitent data

- checkstyle.xml
- pom.xml
Change default checkstyle severity to error.
In common sense, "warning" is something can be ignored.
It is better to use "error" to mean something must be fixed. 
And current CI workflow displays "Summary of failures" by filtering errors.
No.
Example of checkstyle failure, click "Summary of failures" to see the filtered result.
https://github.com/kaijchen/incubator-uniffle/runs/7319512298?check_suite_focus=true
> [CI] Change default checkstyle severity to error

- checkstyle.xml
- client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigUtils.java
- common/src/main/java/org/apache/uniffle/common/util/UnitConverter.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/PartitionBalanceAssignmentStrategy.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/ComposedClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/DataSkippableReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsFileWriter.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileQuorumClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryQuorumClientReadHandler.java
1. Set indentation rules in checkstyle
2. Fix violations.
#54 
No.
https://github.com/kaijchen/incubator-uniffle/runs/7351765430?check_suite_focus=true
> [Style] Check indentation

- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssInMemoryRemoteMerger.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssRemoteMergeManagerImpl.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
- client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/RssInMemoryRemoteMergerTest.java
- client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/RssRemoteMergeManagerTest.java
- docs/client_guide.md
- integration-test/mr/src/test/java/org/apache/uniffle/test/MRIntegrationTestBase.java
Rewrite Mapreduce's MergerManager to spill sorted segments to HDFS, 
It returns a merge-sorted iterator to read these HDFS segments.
In cloud, machines may have very limited disk space and performance.
This PR allows to spill data to remote storage (e.g., hdfs)
Yes. 
|Property Name|Default|Description|
|---|---|---|
|mapreduce.rss.reduce.remote.spill.enable|false|Whether to use remote spill|
|mapreduce.rss.reduce.remote.spill.attempt.inc|1|Increase reduce attempts as hdfs is easier to crash than disk|
|mapreduce.rss.reduce.remote.spill.replication|1|The replication number to spill data to hdfs|
|mapreduce.rss.reduce.remote.spill.retries|5|The retry number to spill data to hdfs|
New UT and IT with remote spill.
Co-authored-by: roryqi <roryqi@tencent.com>
> [Experimental Feature] MR Supports Remote Spill

- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/util/RssClientConfig.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- docs/client_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/AssignmentWithTagsTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
Sending commit concurrently in client side
I found when using the `LOCALFILE` storageType, waiting the commit will cost too much time. To speed up, it can be sent commit concurrently by using thread pool.
**Performance Test Case**
Using 1000 executors of Spark, single executor 1g/1core to run TeraSort 1TB.
When using `LOCALFILE` storageType mode, it cost 7.3 min. 
And then after applying this PR, it cost 6.1 min
1. Introducing the conf of `rss.client.data.commit.pool.size`, the default value is assigned shuffle server size.
No need
> Send commit concurrently in client side

- docs/_config.yml
- docs/client_guide.md
- docs/coordinator_guide.md
- docs/index.md
- docs/server_guide.md
Replace Firestorm with Uniffle in the document
Project was renamed to Uniffle
No
No need
> [DOC] Replace Firestorm with Uniffle

- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessInfo.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/AccessClusterTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssAccessClusterRequest.java
- proto/src/main/proto/Rss.proto
Introduce the reservedData to extend more pluggable accessCheckers
In current codebase, the accessinfo only have acessid and tags. If we want to extend more AccessChecker in coordinator, the info is not enough.
To solve this, i think introducing the reservedData is necessary.
No.
UTs
> Introduce the extraProperties to support user-defined pluggable accessCheckers

- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java
Add more detailed debug info for MR client
MR debug is hardy. 
No.
No need.
> [Log Improvment] Add more detailed debug info for MR client

- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
[Improvement] Shutdown the grpc executors pool when closing
Although the executor pool is used in grpc, but the grpc server won't take ownership of the given executor. It's caller's responsibility to shut down the executor when it's desired.
No
No need.
> [Improvement] Shutdown the grpc executors pool when closing

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssGetShuffleAssignmentsResponse.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Log enhancement: return error message when getting assignment servers and log exception when initializing
To be easy to find the cause of error.
No
No need.
> Log enhancement: return error message when getting assignment servers and log exception when initializing

- deploy/kubernetes/build-operator.sh
- deploy/kubernetes/docker/.gitkeep
- deploy/kubernetes/integration-test/.gitkeep
- deploy/kubernetes/operator/.gitkeep
- deploy/kubernetes/pom.xml
- deploy/kubernetes/test-operator.sh
- pom.xml
To solve issue #48, First step. we add Kubernetes operator profile and directory. We add two scripts build-operator.sh and test-operator.sh. We can use these scripts to build and test our operator. When we use the command `mvn compile -Pkubernetes`, we can build the operator. When we use the command `mvn test -Pkubernetes`, we can test the operator.
We hope use Kubernetes to deploy Uniffle.
No
No need.
> [ISSUE-48] [Feature] Init Kubernetes operator directory

- internal-client/src/main/java/org/apache/uniffle/client/factory/ShuffleServerClientFactory.java
[Improvement] No need to use synchronized lock of the method scope when getting client
Avoid unnecessary lock to improve performance.
No
No need.
> [Improvement] No need to use synchronized lock of the method scope when getting client

- README.md
Add "Apache" in the title and improve the description.
No.
See https://github.com/kaijchen/incubator-uniffle/tree/readme#apache-uniffle-incubating
> [DOC] Update title and description in README

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
- common/src/main/java/org/apache/uniffle/common/RssShuffleUtils.java
- common/src/main/java/org/apache/uniffle/common/exception/RssException.java
- common/src/test/java/org/apache/uniffle/common/RssShuffleUtilsTest.java
release shuffleblock  when finished reading
We found spark executor is easy be killed by yarn, and i found it is because executor use too mush offheap memory when read shuffle data.
I found most of offheap memory is used to store uncompressed shuffle Data, and this part of memory will be release only when GC is triggered
No
Add new ut
> [Improvement] ShuffleBlock should be release when finished reading

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
use multi thread to clean local storage
If shuffle server exit abnormally, there will be many files need to be clear when shuffle server start again and this operation will cost a lot of time
No
No need
> [Improvement]LocalStorage init use multi thread #71

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkClientWithLocalTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
1. Add `RssUtils#cloneBitMap()`.
2. Replace `deserializeBitMap(serializeBitMap(bitmap))` by `cloneBitMap(bitmap)`.
1. No need to handle `IOException`.
2. More efficient.
No.
New unit test `RssUtilsTest#testCloneBitmap()`
> [Improvement] Use OR operation instead of serialization for cloning BitMaps

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
Ignore partial failure on initializing local storage in shuffle server side
When setting multiple storage paths, only one disk is insufficient capacity, shuffle server will directly throw exception. We hope it can be ignored, because bad disks are more common in production environments
No
UT
> [Improvement] Ignore partial failure on initializing local storage in shuffle server side

- .github/workflows/build.yml
- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
- pom.xml
- proto/pom.xml
1. Add dependency `javax.annotation-api`.
2. Add Java 11 and Java 17 build in CI, `mvn package -DskipTests` only.
3. Rename jobs and workflows in CI. 
4. Only check main profiles in sequential workflow, just enough to cover all modules.
Support build in Java 11 and Java 17.
No.
https://github.com/kaijchen/incubator-uniffle/actions/runs/2760618905
> [CI] Test compile in Java 11 and Java 17

- bin/utils.sh
Sleep less time but try more times when stopping
Waiting time for executing stop script is too long even if the JVM exits early.
No
Have already verify in our production enviroment.
> Sleep less time but try more times when stopping

- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/storage/StorageManagerFactory.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
Remove `StorageManagerFactory#createStorageManager`  useless server id  
Clean code.
No
Unit test
> [Improve] Remove useless server id from `StorageManagerFactory#createStorageManager`

- common/src/test/java/org/apache/uniffle/common/util/RetryUtilsTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessCandidatesCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ApplicationManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/BasicAssignmentStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ClientConfManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorConfTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorMetricsTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/PartitionBalanceAssignmentStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/PartitionRangeAssignmentTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/PartitionRangeTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ServerNodeTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
Solve issue #123,  solve coordinator module code style problems
Improve our test code style
No
I add the test code style check commits, coordinator module passed.
https://github.com/jerqi/incubator-uniffle/runs/7650825642?check_suite_focus=true
> [MINOR][IMPROVEMENT][COORD] Fix coordinator module code style

- storage/src/test/java/org/apache/uniffle/storage/HdfsShuffleHandlerTestBase.java
- storage/src/test/java/org/apache/uniffle/storage/common/LocalStorageTest.java
- storage/src/test/java/org/apache/uniffle/storage/common/ShuffleFileInfoTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsFileReaderTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsFileWriterTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/util/ShuffleHdfsStorageUtilsTest.java
- storage/src/test/java/org/apache/uniffle/storage/util/ShuffleStorageUtilsTest.java
Solve issue #123,  solve storage module code style problems
Improve our test code style
No
I add the test code style check commits, storage module passed.
https://github.com/jerqi/incubator-uniffle/runs/7691133341?check_suite_focus=true
> [MINOR][IMPROVEMENT][STORAGE] Fix storage module code style

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java
- docs/client_guide.md
To solve issue [#127](https://github.com/apache/incubator-uniffle/issues/127)
Avoid some memory shortage situations, and retry to ensure that the tasks run in the RSS cluster as much as possible.
Two new parameters are added on the client side, `spark.rss.client.access.retry.times`  the number of retry reconnection and `spark.rss.client.access.retry.interval.ms`  the reconnection interval. The user can set these two parameters within his expected time to make the task run in the RSS cluster as much as possible.
No need.
> [Improvement] Add timeout reconnection when DelegationRssShuffleManager send the request of AccessCluster

- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java
Do not use `InetAddress.getLocalHost().getHostAddress()`  in test because it is indeterminate. The return value may be different on a multi-NIC machine or on different system.
In addition to 127.0.0.1, the loopback address 127.0.1.1 can also be returned, which happens on Debian.This will make UT fail.
```
org.opentest4j.AssertionFailedError: 
Expected :127.0.1.1
Actual   :10.0.191.230
at org.apache.uniffle.common.util.RssUtilsTest.testGetHostIp(RssUtilsTest.java:64)
```
No.
UT.
> [MINOR] Fix flaky test testGetHostIp

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorMetrics.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorMetricsTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
To solve #146 
The number of unhealthy nodes can be viewed on the monitoring.
No.
No need.
> [Improvement] Add the number of unhealthy nodes in CoordinatorMetrics

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
the behavior of buffer management and memory allocate
when adding a huge record to a partition where the buffer is not initialized, we only allocate bufferSegmentSize memory, however release the real huge size memory after the buffer is sent.
this will easily cause OOM.
better manage memory
no
pass testing
> [BUGFIX] Fix memory leak which cause oom

- README.md
- build_distribution.sh
Tag Spark and Hadoop version in release package.
1. ~~Add version information to client jar name~~
2. Add version information in RELEASE file
An example：
```
./build_distribution.sh --spark3-profile 'spark3.0' --spark3-mvn '-Dx.x1=1 -Dspark.version=3.0.2' -Dhadoop.version=2.8.0 -Dx.x2=2
```
Before PR：
```
$ cat RELEASE
RSS 0.6.0-snapshot (git revision 04cbdbb) built
Build flags: -Dhadoop.version=2.8.0 -Dx.x3=3    
```
After PR：
```
$ cat RELEASE
RSS 0.6.0-snapshot (git revision 27032c1) built for Hadoop 2.8.0 Spark2 2.4.6 Spark3 3.0.2
Build flags: --spark2-profile 'spark2' --spark2-mvn '' --spark3-profile 'spark3.0' --spark3-mvn '-Dx.x1=1 -Dspark.version=3.0.2' -Dhadoop.version=2.8.0 -Dx.x2=2
```
Unable to determine spark and hadoop version of release package, which may cause confusion in …
> [MINOR] Tagged spark hadoop version in release package

- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- docs/coordinator_guide.md
Remove spaces when reading file of excluded nodes and the use of the excluded node file was added to the coordinator's introduction document.
More user-friendly.
No.
No need.
> [MINOR][DOC] Remove spaces when reading file of excluded nodes

- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ApplicationManagerTest.java
Filter null value when selecting remote storage.
Using the original comparison method, after sorting, the null value is placed in front of the `sizeList`, and a null pointer will be thrown.
No.
Added.
> [Improvement] Filter null value when selecting remote storage in ApplicationManager

- common/src/main/java/org/apache/uniffle/common/exception/NotRetryException.java
- common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java
- common/src/test/java/org/apache/uniffle/common/util/RetryUtilsTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
1.In server side, if requireBufferId not found when send data, thrown an exception.
2.In client side, if fail to send data, require buffer again.
We found shuffle server which under high load is easy encounter java.lang.OutOfMemoryError: Java heap space even we allocate more jvm heap memory and less rss.server.buffer.capacity #76 
No
Have already verify in our production enviroment.
> [ISSUE-76] Disallow sendShuffleData if requireBufferId expired

- server/pom.xml
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/MultiStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/StorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerOnKerberizedHdfsTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/api/ShuffleDeleteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleDeleteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileDeleteHandler.java
Delete shuffle data files stored on secured hdfs using proxy user
In previous PR #53, we introduce the proxy user for shuffle server to write shuffle data to HDFS. 
But I ignored that the shuffle server should also delete these files by the way of proxy user.
No
Manual tests on kerberos HDFS cluster, and unit tests.
> [FOLLOWUP] Delete hdfs shuffle data files using proxy user

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/reader/RssShuffleDataIteratorTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
Use `org.apache.spark.TaskContext#addTaskCompletionListener` to clean up resources used by `RssShuffleDataIterator`. This avoids possible resource leaks.
Before this PR, `RssShuffleDataIterator` would only clean up used resources after all records read.
When the `Spark Task` fails or cancels, or runs some special logic such as `LocalLimit`, the resource will not be cleaned up. This creates potential resource leaks.
No
Added a UT case
> [BUGFIX] Fix resource leak when shuffle read

- README.md
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
for issue https://github.com/apache/incubator-uniffle/issues/173, Add a new flush strategy for ShuffleBufferManager, flush if the size of a single buffer reaches `rss.server.buffer.flush.threshold`, which can make more full use of disk io without waiting for the buffer to reach `(rss.server.buffer.capacity * rss.server.memory.shuffle.highWaterMark.percentage)`
Already added
> [Improvement] ShuffleBufferManager supports triggering flush according to the size of single ShuffleBuffer

- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
From the audit log of HDFS, it can be seen that when the HDFS path of this app was last deleted at 18:00:55, the log in the `shuffleServer` found that the error about `file could not be found`, and the file would continue to be written. At last we found that when some appId cache was removed in `appIdToStorages`, and then `HdfsStorageManager` calls `removeResources` will cause storagePath to not be deleted.
When the cache of `appIdToStorages` removed, the remote path can be deleted normally.
No.
Added ut.
> [Improvement] Should match from pathToStorages when appId does not exist in appIdToStorages

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
###What changes were proposed in this pull request?
follow  #173, when single buffer flush is triggered, the buffer size should reach `rss.server.flush.cold.storage.threshold.size`,  we keep the same logic as MultiStorageManager#selectStorageManager
###Why are the changes needed?
we keep the same logic as MultiStorageManager#selectStorageManager
###Does this PR introduce any user-facing change?
No
###How was this patch tested?
Already added
> [ISSUE-173][FOLLOWUP] The size of single buffer flush should reach rss.server.flush.cold.storage.threshold.size 

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Reverts apache/incubator-uniffle#178
> Revert "[ISSUE-173][FOLLOWUP] The size of single buffer flush should reach rss.server.flush.cold.storage.threshold.size "

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
follow https://github.com/apache/incubator-uniffle/issues/173, when single buffer flush is triggered, the buffer size should reach rss.server.flush.cold.storage.threshold.size, we keep the same logic as MultiStorageManager#selectStorageManager
Make sure cold storage is valid
No
Already added
> [ISSUE-173][FOLLOWUP] The size of single buffer flush should reach rss.server.flush.cold.storage.threshold.size

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Store app user information in shuffleTaskInfo.
Reduce cache.
No.
Passed the ut.
> [FOLLOWUP] Store app user in ShuffleTaskInfo

- README.md
- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java
- common/src/test/java/org/apache/uniffle/common/KerberizedHdfs.java
- common/src/test/java/org/apache/uniffle/common/security/HadoopSecurityContextTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Add the conf of `rss.security.hadoop.krb5-conf.file`
Follow up #53 , the krb5 conf file can be configured in `SecurityConfig`, and also should be configured in shuffle-server/coordinator conf for users.
Yes
Not necessary.
> [FOLLOWUP] Add the conf of rss.security.hadoop.krb5-conf.file

- bin/restart-coordinator.sh
- bin/restart-shuffle-server.sh
- bin/rss-env.sh
- bin/start-coordinator.sh
- bin/start-shuffle-server.sh
- bin/stop-coordinator.sh
- bin/stop-shuffle-server.sh
- bin/utils.sh
Added six optional environment variables:
```
```
Simplify service deployment
Added six optional environment variables.
With the default environment variables, the behavior is the same as before this PR.
local test
> [Improvement] Add optional environment variables

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigOption.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/main/java/org/apache/uniffle/common/util/UnitConverter.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/PartitionBalanceAssignmentStrategy.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
Fix some bad practices reported by spotbugs (medium priority). 
To improve code quality.
No.
CI with extra spotbugs rules: https://github.com/kaijchen/incubator-uniffle/actions/runs/2902861660
> [MINOR] Fix some bad practices reported by spotbugs

- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
Replace HashSet with ImmutableSet in RssMRConfigs and RssSparkConfigs.
It's error prone to use mutable collection in public static fields.
No.
CI.
> [MINOR] Replace HashSet with ImmutableSet in configs

- common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigUtils.java
- common/src/test/java/org/apache/uniffle/common/config/ConfigOptionTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AssignmentStrategyFactory.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorConfTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
Introduce the enumType in ConfigOptions
When I want to extend the zstd compression type in uniffle, I found we lack the enum class for configOptions. 
And I think it will be used for users to specify the concrete implementation in some pluggable class.
No
UTs.
> [IMPROVEMENT] Introduce the enumType in ConfigOptions

- common/src/main/java/org/apache/uniffle/common/RssShuffleUtils.java
- common/src/test/java/org/apache/uniffle/common/RssShuffleUtilsTest.java
This pr aims to enhance the stability of `RssShuffleUtilsTest#testDestroyDirectByteBuffer`,  change to use native address validity to confirm that memory is released
Fix flaky test.
No
- Existing tests
- Manual test
run the following command on MacOS/Apple Silicon environment, `testDestroyDirectByteBuffer ` is a flaky test:
```
mvn clean install -pl common -am -DskipTests
mvn test -pl common -Dtest=org.apache.uniffle.common.RssShuffleUtilsTest#testDestroyDirectByteBuffer
```
**Before**
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.302 s <<< FAILURE! - in org.apache.uniffle.common.RssShuffleUtilsTest
[ERROR] testDestroyDirectByteBuffer  Time elapsed: 0.3 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
at …
```
> [ISSUE-144] Fix flaky test `RssShuffleUtilsTest#testDestroyDirectByteBuffer` 

- .github/workflows/parallel.yml
- README.md
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- pom.xml
support spark 3.2.0
After SPARK-36892, MapOutputTrackerWorker#getMapSizesByExecutorId has been modified to include method names and return parameter types, Java.lang.NoSuchMethodException will be thrown when the RssShuffleManager#getExpectedTasksByExecutorId method is called, The version of our production environment is 3.2.0.
No
reused intergration-test
> [Issue-194][Feature] Support spark 3.2.0

- server/src/main/java/org/apache/uniffle/server/HealthCheck.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/test/java/org/apache/uniffle/server/HealthCheckTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
- server/src/test/java/org/apache/uniffle/server/StorageCheckerTest.java
Introduce more local storage infos' metrics.
In current codebase, there is no such local storage space info metrics. After this PR, we could monitor the disk utilization easily.
No
UTs.
> [IMPROVEMENT] Add more metrics about local storage info

- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileServerReadHandler.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandlerTest.java
Return index-file size of n*SEGMENT_SIZE in HDFS reading
It should keep consistent with the logic of returning the complete index data in localfile reader that data size is always n*SEGMENT_SIZE.
No
> [MINOR][IMPROVEMENT] Return index-file size of n*SEGMENT_SIZE in HDFS reading

- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
- pom.xml
1. Use `Awaitility.await` to replace arbitrary sleep in tests.
2. Make `heartbeatTimeoutTest` more deterministic.
To make tests correct and fast.
And serve as an example of waiting longer for correctness without worrying about the speed.
No.
Before
After
> [TEST] Improve SimpleClusterManagerTest

- DISCLAIMER
- NOTICE
- pom.xml
Add a notice file.
References:
https://github.com/apache/inlong/blob/master/NOTICE
https://github.com/apache/spark/blob/master/NOTICE 
https://infra.apache.org/licensing-howto.html
For apache release.
https://github.com/apache/incubator-uniffle/issues/207 
No.
No need.
> Add Notice and DISCLAMER file

- coordinator/src/main/java/org/apache/uniffle/coordinator/AppBalanceSelectStorageStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/LowestIOSampleCostSelectStorageStrategy.java
Fix incorrect log format strings.
SLF4J use `{}` as placeholder in format strings.
No.
CI.
> Fix incorrect log format strings

- README.md
Change "total lines" badge url to sloc.xyz
And use empty alt message to display nothing on failure.
Current badge sometimes show "total lines: invalid".
No.
https://github.com/kaijchen/incubator-uniffle/tree/sloc#apache-uniffle-incubating
> Change total lines badge url to sloc.xyz in README

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriterBuffer.java
[MINOR] Simplify creating buffer logic
Minor improvement to avoid duplicate code.
No
No need.
> [MINOR] Simplify creating buffer logic

- .github/workflows/build.yml
Support cancelling previous ci actions when new commits are submitted.
I hope the CI actions can always test the latest commits code and cancel the previous ci when new commits are submitted.
Refer to: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
> Support cancelling previous ci actions

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessClusterLoadChecker.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessClusterLoadCheckerTest.java
- docs/coordinator_guide.md
Use the conf of shuffleNodesNumber from jobs to be as checking factor
In the PR #97 , it allow client to specify the shuffle server numbers, but in clusterLoaderChecker, it dont take this into considering. In this PR, it will use the conf of shuffleNodesNumber from jobs to be as checking factor only when the conf of `rss.coordinator.access.loadChecker.serverNum.threshold` is missed.
No.
UTs.
> Use the conf of shuffleNodesNumber from jobs to be as checking factor

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Add more metrics about requiring read memory
1. total_require_read_memory_num
2. total_require_read_memory_retry_num
3. total_require_read_memory_failed_num
These metrics can be as the indicator of high-watermark pressure.
No
No need.
> Add more metrics about requiring read memory

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Adjust the memory required times from 100 to 50 to match the grpc max deadline conf (60s).
If the required memory retry time > 60s, the client will cancel the request. That means the required memory exception wont throw to client side. And the server side wont show any related log. 
No
> Adjust the memory required times to match grpc max deadline conf

- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetShuffleReportForMultiPartTest.java
`org.apache.uniffle.test.GetShuffleReportForMultiPartTest` is flaky
throws Exception:
ava.lang.ClassCastException: org.apache.spark.shuffle.RssShuffleManager cannot be cast to org.apache.uniffle.test.GetShuffleReportForMultiPartTest$RssShuffleManagerWrapper
at org.apache.uniffle.test.GetShuffleReportForMultiPartTest.runTest(GetShuffleReportForMultiPartTest.java:180)
at org.apache.uniffle.test.SparkIntegrationTestBase.runSparkApp(SparkIntegrationTestBase.java:74)
at org.apache.uniffle.test.SparkIntegrationTestBase.run(SparkIntegrationTestBase.java:52)
at org.apache.uniffle.test.GetShuffleReportForMultiPartTest.resultCompareTest(GetShuffleReportForMultiPartTest.java:141)
Fix flaky test
No
GA passed
> [MINOR] Fix flaky test

- deploy/kubernetes/operator/config/manager/rss-controller.yaml
- deploy/kubernetes/operator/config/manager/rss-webhook.yaml
- deploy/kubernetes/operator/examples/full-restart/rss-full-restart.yaml
- deploy/kubernetes/operator/examples/full-upgrade/rss-full-upgrade.yaml
- deploy/kubernetes/operator/examples/partition-upgrade/rss-partition-upgrade.yaml
- deploy/kubernetes/operator/examples/specific-upgrade/rss-specific-upgrade.yaml
For issue #48 
I add some yaml files of components and crd exampes.
> [ISSUE-48][FEATURE][FOLLOW UP] Add yaml of components and crd exampes

- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetShuffleReportForMultiPartTest.java
```
org.opentest4j.AssertionFailedError: expected: <0> but was: <-218>
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
at org.apache.uniffle.test.GetShuffleReportForMultiPartTest.validateRequestCount(GetShuffleReportForMultiPartTest.java:198)
at org.apache.uniffle.test.GetShuffleReportForMultiPartTest.runTest(GetShuffleReportForMultiPartTest.java:185)
at org.apache.uniffle.test.SparkIntegrationTestBase.runSparkApp(SparkIntegrationTestBase.java:74)
at …
```
> Fix Flaky test GetShuffleReportForMultiPartTest

- README.md
- docs/server_guide.md
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
Set the default disk capacity to the total space
When shuffle-servers are colocated with NodeManagers, the disk capacity is hard to set. Because when it's equal with the total space, it will cause the most shuffle-servers startup fail due to free-space checking. If not, it will waste some disk resources.
And the default disk capacity is 1TB, it's not out-of-box value. So this PR is to set the default value of 'rss.server.disk.capacity' to the disk total space.
No
> Set the default disk capacity to the total space

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/doc-improvement-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/flaky-test-report.yml
- .github/ISSUE_TEMPLATE/improvement.yml
- .github/ISSUE_TEMPLATE/subtask.yml
- .github/ISSUE_TEMPLATE/umbrella.yml
Add issue template
Provide some issue templates for users 
No.
No need.
> Add issue template

- coordinator/src/main/java/org/apache/uniffle/coordinator/LowestIOSampleCostSelectStorageStrategy.java
Iterate Map by `Map.entrySet()` instead of `Map.keySet()` + `Map.get(key)`.
It's more efficient.
No.
CI.
> [MINOR] Fix inefficient map iteration

- common/src/main/java/org/apache/uniffle/common/exception/FileNotFoundException.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithLocalOfExceptionTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkClientWithLocalTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/ComposedClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileServerReadHandler.java
Fast fail when reading failed in ComposedClientReadHandler
It should fast fail on network failure when reading shuffle data from memory/localfile/hdfs in `ComposedClientReadHandler`. If not, it will throw inconsistent blockIds and make users confused.
No
UTs.
> Fast fail when reading failed in ComposedClientReadHandler

- .github/workflows/parallel.yml
Fix flaky test about kerberos #196 
Fix flaky test
No
No need.
> [ISSUE-196] Fix flaky test about kerberos

- deploy/kubernetes/docker/Dockerfile
- deploy/kubernetes/docker/build.sh
- deploy/kubernetes/docker/rss-env.sh
- deploy/kubernetes/operator/Makefile
- deploy/kubernetes/operator/pkg/controller/controller/process_rss_test.go
- deploy/kubernetes/operator/pkg/controller/controller/shuffle_server_test.go
- deploy/kubernetes/operator/pkg/controller/sync/shuffleserver/shuffleserver.go
- deploy/kubernetes/operator/pkg/webhook/inspector/rss.go
- deploy/kubernetes/operator/pkg/webhook/inspector/rss_test.go
For issue #48 
I add some unit test about validating rss objects in webhook components.
> [ISSUE-48][FEATURE][FOLLOW UP] add unit test for validating rss objects

- README.md
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssBypassWriter.java
Replace `：` by `: `.
No.
No need.
> [TYPO] Replace Chinese colon by ASCII colon

- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
- docs/coordinator_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorAssignmentTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
Introduce startup-silent-period mechanism to avoid partial assignments
When changing some coordinator's conf and then restart, coordinator will accept client getAssignment request immediately, but it will serve for jobs request based on the partial registered shuffle-servers, which will make some jobs gotten not enough required shuffle-servers and then slow the running speed.
I think we should make coordinator wait for more than one shuffle-server heartbeat interval before serving for client. During out-of-service, requests from client will fallback to slave coordinator.
Yes
UTs
> Introduce startup-silent-period mechanism to avoid partial assignments

- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
[ISSUE-244] Fix flaky test of CoordinatorGrpcTest.rpcMetricsTest
1. The gauge metric of `HEARTBEAT_METHOD` is hard to meansure due to async sending at background. So remove it
2. The gauge metric of `GET_SHUFFLE_ASSIGNMENTS_METHOD` may be not called `descCounter` when rpc finished, so remove it
No
Dont need
> [ISSUE-244] Fix flaky test of CoordinatorGrpcTest.rpcMetricsTest

- coordinator/src/test/java/org/apache/uniffle/coordinator/ClientConfManagerTest.java
For [https://github.com/apache/incubator-uniffle/actions/runs/3213433147/jobs/5253100348](https://github.com/apache/incubator-uniffle/actions/runs/3213433147/jobs/5253100348)
```Error:  dynamicRemoteByAppNumStrategyStorageTest  Time elapsed: 11.065 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <hdfs://host2/path2> but was: <hdfs://host3/path3>
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
at org.apache.uniffle.coordinator.ClientConfManagerTest.dynamicRemoteByA …
```
> Fix flaky test of ClientConfManagerTest

- client-mr/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java
- storage/src/main/java/org/apache/uniffle/storage/util/StorageType.java
- storage/src/test/java/org/apache/uniffle/storage/util/StorageTypeTest.java
[Refactor] Optimize creating shuffle handlers
When creating shuffle handler, the code is too duplicate and complex.
No
UTs
> [Refactor] Optimize creating shuffle handlers

- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
Use the original latest modification time to fix potenial missing reads of exclude nodes
I found that after doing `parseExcludeNodesFile(hadoopFileSystem.open(hadoopPath));`, the file was updated of adding the new nodes, in the current implementation, the newly added nodes wont be recognized.
No
Dont need
> Fix potenial missing reads of exclude nodes

- client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-mr/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java
1: In the RssMRUtils#getBlockId method, change the partitionId of int type to long, make sure no overflow
Fix #257 issue ,view this issue for details
org.apache.hadoop.mapreduce.RssMRUtilsTest#partitionIdConvertBlockTest
> [ISSUE-257] RssMRUtils#getBlockId change the partitionId of int type to long

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- integration-test/spark2/src/test/java/org/apache/uniffle/test/GetReaderTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
For issue#173, make the lifecycle of remoteStorage var scoped in the method of registerShuffle
This problem causes getShuffleResult to fail, which eventually causes the task to fail.
No
Existing UT
> [ISSUE-273][BUG] Get shuffle result failed caused by concurrent calls to registerShuffle

- common/src/test/java/org/apache/uniffle/common/config/ConfigOptionTest.java
Add enum type test about case insensitive
The enum type is the case insensitive. This PR is to add some test case to indicate this.
No.
UTs
> Add enum type test about case insensitive

- README.md
Remove code quality badge and add release badge in README.
1. LGTM.com will shut down in December 2022, and it's replaced by GitHub code scanning.
(Unfortunately I have no idea of how to enable it for this repository.)
2. Uniffle had just released its first version in the incubator. Let's display it in badges.
No.
https://github.com/kaijchen/incubator-uniffle/tree/badges-2#apache-uniffle-incubating
> Remove code quality badge and add release badge

- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
Upgrade Github actions for Node.js 16
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-java, actions/setup-java, actions/checkoutShow less
No.
https://github.com/kaijchen/incubator-uniffle/actions/runs/3359652583
> Upgrade Github actions for Node.js 16

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
Fix NPE:
```
22/11/03 03:36:08 ERROR Executor: Exception in task 4.0 in stage 1.0 (TID 5)
java.lang.NullPointerException
at org.apache.spark.shuffle.writer.WriteBufferManager.addRecord(WriteBufferManager.java:116)
at org.apache.spark.shuffle.writer.RssShuffleWriter.write(RssShuffleWriter.java:152)
at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
at org.apache.spark.scheduler.Task.run(Task.scala:131)
at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
at …
```
> Fix NPE in WriteBufferManager.addRecord

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- storage/src/main/java/org/apache/uniffle/storage/common/AbstractStorage.java
- storage/src/test/java/org/apache/uniffle/storage/common/LocalStorageTest.java
Fix AbstractStorage#containsWriteHandler
It is a bug, and it is obvious.
No
Feel unnecessary
> Fix AbstractStorage#containsWriteHandler

- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Add more test cases on LocalStorageManager.selectStorage
Currently, the method of LocalStorageManager.selectStorage lacks unit tests, which should be handle with care as storage corruption is involved
No
Dont need
> Add more test cases on LocalStorageManager.selectStorage

- common/pom.xml
- common/src/main/java/org/apache/uniffle/common/compression/Codec.java
- common/src/main/java/org/apache/uniffle/common/compression/SnappyCodec.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- common/src/test/java/org/apache/uniffle/common/compression/CompressionTest.java
- docs/client_guide.md
- pom.xml
This PR adds the support of snappy compression/decompression based on the example of https://github.com/apache/incubator-uniffle/pull/254. 
Add a new feature.
No
UT
> [ISSUE-283][FEATURE] Support snappy compression/decompression

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
This PR makes `RPC_SERVER_PORT` and `JETTY_HTTP_PORT` in RSS conf as optional by setting up default values into the config entries. 
Feature.
NO
UT
> [ISSUE-290] Make RpcNodePort and HttpNodePort optional

- common/src/main/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitter.java
- common/src/test/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitterTest.java
1. Merge continuous ShuffleDataSegment into single one
2. Throw exception when reading the discontinuous blocks into segments directly
Currently, the LocalOrderSegmentSplitter will split the index file into 
multiple shuffleDataSegments. But the split scope is limited in the range of local order.
For example:
The blocks are as follow
```
block-a (taskId-1)
block-b (taskId-2)
block-c (taskId-1)
block-d (taskId-2)
```
When the reader want to get  the range of taskIds: [1, 3), the strategy will return
two shuffleDataSegments. But we'd better to merge them into single one to 
reduce the network interaction times, because they are continuous.
No
1. UTs
> [ISSUE-301][Subtask][Improvement][AQE] Merge continuous ShuffleDataSegment into single one

- client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java
- client/src/test/java/org/apache/uniffle/client/ClientUtilsTest.java
1. Replace raw `RuntimeException` with proper specific subclass of `RuntimeException`.
2. Cleanup the logic in `ClientUtils#fetchRemoteStorage()`.
1. Throwing `RuntimeException` is not a good practice because it's difficult to catch (without catching other RE).
2. For clearity and easier to understand.
No.
ClientUtilsTest is modified to assert more specific exceptions.
> Cleanup RuntimeException and fetchRemoteStorage logic in ClientUtils

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
Fix bug of "Comparison method violates its general contract"
If not, it will throw the exception when using the timsort.
No
Dont need
> Fix bug of "Comparison method violates its general contract"

- common/src/main/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitter.java
- common/src/test/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitterTest.java
1. Fix potenial bug when merging continuous segments
2. Show more details when throwing discontinuous blocks to better debug
In current codebase, while expected task id is 230 but splitting the index taskId seq of (229, 230, 221, 229, 230), it will throw exception of discontinuous check.
This PR is to fix this
No
1. UTs
> [AQE][LocalOrder] Fix potenial bug when merging continuous segments

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileQuorumClientReadHandler.java
1. Fix wrong param of expectedTaskIds in `LocalOrderSegmentSplitter`
2. Fix the `LOCAL_ORDER` type invalid when reading
In current codebase, the reads of `LOCAL_ORDER` is invalid. This PR is to fix it.
No
Existing UTs of `AQESkewedJoinWithLocalOrderTest` cover this case.
> [AQE][LocalOrder] Fix wrong param of expectedTaskIds in LocalOrderSegmentSplit

- common/src/main/java/org/apache/uniffle/common/segment/FixedSizeSegmentSplitter.java
- common/src/test/java/org/apache/uniffle/common/segment/FixedSizeSegmentSplitterTest.java
Fix potenial bug when the index reading offset equals to data length
If the reading length == data length in `FixedSizeSegmentSplitter`, it should involve this block. And if its length > data length. it should abort it.
No
UTs
> [Bug] Fix potenial bug when the index reading offset is greater than data length

- deploy/kubernetes/operator/pkg/controller/controller/process_rss_test.go
- deploy/kubernetes/operator/pkg/controller/util/util.go
- deploy/kubernetes/operator/pkg/controller/util/util_test.go
- deploy/kubernetes/operator/pkg/utils/util.go
fix #323 
I have modified it for time reasons, thanks for pointing this out.
I changed the owner of host paths as UID:GID.
Fix bug
No
UT
> [Bug] Fix invalid owner of host path volumes

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
If app expired, thrown a runtime exception with message
`reportShuffleResult` after app expired in shuffle server will throw NPE #329  
No
Added
> [ISSUE-329]Catch NPE in ShuffleTaskManager#addFinishedBlockIds

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerGrpcMetricsTest.java
Fix wrong method name.
Fix wrong method name cause `grpc_get_in_memory_shuffle_data_total` always 0.
No.
Already exists UT.
> [BUG] Fix wrong method name

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
Cleanup unused shuffle servers after stage completed
If there are many stages in one applicaiton, spark driver will send heartbeat to every shuffle servers, and it may cause app expired in shuffle server side. And if we support decommission in the future, it will cause shuffle difficult to exit. #328 
No
Added
> [ISSUE-328] Cleanup unused shuffle servers after stage completed

- common/src/main/java/org/apache/uniffle/common/RankValue.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AbstractSelectStorageStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AppBalanceSelectStorageStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/LowestIOSampleCostSelectStorageStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/RankValue.java
More standardized, and the class can be extended in the future.
No.
No need.
> [MINOR] Migrate RankValue to the package of the common class

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/WriteAndReadMetricsTest.java
Fix incorrect spark metrics
1. The corresponding shuffle-read records number and shuffle-write records number is not consistent in our internal cluster
2. Log wont show the correct fetch bytes, always return 0 like 
`22/11/15 13:54:53 INFO RssShuffleDataIterator: Fetch 0 bytes cost 30791 ms and 53 ms to serialize, 347 ms to decompress with unCompressionLength[274815736]
`
No
1. UTs
2. Online spark3 jobs test
> [BUG] Fix incorrect spark metrics

- common/src/main/java/org/apache/uniffle/common/segment/FixedSizeSegmentSplitter.java
- common/src/main/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitter.java
- common/src/test/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitterTest.java
1. Introduce the data length check in LocalOrder strategy
2. Add tests about keeping consistent with FixedSize Strategy when no skew optimization
More stability
No
UTs
> [Improvement][LocalOrder] Add tests about keeping consistent with FixedSize when no skew optimization

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- integration-test/spark2/src/test/java/org/apache/uniffle/test/GetReaderTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
Spark have multiple serializers. We support the spark serializer which supportsRelocationOfSerializedObjects.
You can see https://github.com/apache/spark/blob/25849684b78cca6651e25d6efc9644a576e7e20f/core/src/main/scala/org/apache/spark/serializer/Serializer.scala#L98
Spark have three kinds of serializer
org.apache.spark.serializer.JavaSerializer
org.apache.spark.sql.execution.UnsafeRowSerializer
org.apache.spark.serializer.KryoSerializer
Only org.apache.spark.serializer.JavaSerializer don't support RelocationOfSerializedObjects.
So when we find the parameters to use org.apache.spark.serializer.JavaSerializer, We should throw an exception.
No
test locally
> [ISSUE-342][Improvement] Check Spark Serializer type

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/test/java/org/apache/uniffle/server/buffer/BufferTestBase.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferTest.java
1. Create a extra reference copy of inFlushed blocks to avoid breaking down original sequence,  if not, it will cause missed data when reading due to the sequence reading when getting memory data.
Fix the bug of missed data due to block sorting
No
1. UTs
> [BUG][AQE][LocalOrder] Fix the bug of missed data due to block sorting

- .asf.yaml
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-AssigningexternalcollaboratorswiththetriageroleonGitHub
Projects may assign external (non-committer) collaborators the triage role for their repository.
The triage role allows people to assign, edit, and close issues and pull requests, without giving them write access to the code.
I add active contributors to the collaborators list.
It's convenient for the active contributors to manage issues.
No
No
> Add collaborators

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkIntegrationTestBase.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
Fix flaky test of AQESkewedJoinWithLocalOrderTest
1. The sparksession is not closed by `GetReaderTest.java`
No
> [BUG][FOLLOWUP] Fix flaky test of AQESkewedJoinWithLocalOrderTest

- common/src/main/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitter.java
- common/src/test/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitterTest.java
Remove check of discontinuous map task ids
In the [startMapIndex, endMapIndex) sequence, the index is not the map task id, which only indicate the range of the succeed map task ids set. 
So that means. if the range is [0, 5), it only indicate the number of tasks is 5. And the task id list may be as follows:
`[task-1, task-3, task-9, task-15, task-16]`
No
1. UTs
> [BUG][AQE][LocalOrder] Remove check of discontinuous map task ids

- client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java
- client/src/test/java/org/apache/uniffle/client/ClientUtilsTest.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendShuffleDataRequest.java
[Improvement] Task fast fail once blocks fail to send
1. In single replica mechanism, single one batch data sent failed should make task fast fail.
2. When some remaining block events in dataTransferPool wait to be sent, we should abandon it.
3. More precisely, we need to interrupt send requests belonged to failed tasks. (Using the `GrpcFuture` to cancel it)
1. When shuffle-sever is down, in current codebase, the shuffle-write client will block and retry too much times. Actually, it should fast fail once partial blocks fail to send.
2. When using the custom retry policy in rpc layer like #308 , this PR will solve the potential problem of waiting too long wait time when specifying the  1min  retry time.
After this patch, fail time is limited in 2min. Before, it will be for 10min+
No
1. UTs …
> [Improvement] Task fast fail once blocks fail to send

- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessQuotaChecker.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessCandidatesCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessClusterLoadCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/AccessQuotaCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/AccessCandidatesCheckerHdfsTest.java
1. Optimize the use of `QuotaManager`, use `QuotaManager` when checking the number of apps, and decouple with `ApplicationManager`.
2. For #356  The start of `QuotaManager` is controlled by the configuration of the checker.
More reasonable.
No.
Added new ut.
> [Improvement] Optimize the use of QuotaManager

- client-spark/spark3/pom.xml
1. We specified the version number of `protobuf-java` in the `client-spark/spark3/pom.xml` file.
More reasonable. https://github.com/apache/incubator-uniffle/issues/228
No
We compiled in the test environment and verified the correctness of the `rss-client-spark3-0.6.0-shaded.jar` package.
> [ISSUE-228] Fix the problem of protobuf-java incorrect dependency at compile time

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
Fix potential memory leak when encountering disk unhealthy
When encountering disk unhealthy and exceed the timeout of pendingDataShuffleFlushEvent, it will release memory. But in current codebase, it wont release the data reference and cause the memory leak.
No
> [BUG] Fix potential memory leak when encountering disk unhealthy

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- client/src/main/java/org/apache/uniffle/client/request/CreateShuffleReadClientRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetInMemoryShuffleDataRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferTest.java
- storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/request/CreateShuffleReadHandlerRequest.java
Support getting memory data skip by upstream task ids
In current codebase, when the shuffle-server memory is large and 
job is optimized by AQE skew rule, the multiple readers of the same 
partition will get the shuffle data from the same shuffle-server. 
To avoid reading unused localfile/HDFS data, the PR of #137 has 
introduce the LOCAL_ORDER mechanism to filter the most of data. 
But for the storage of MEMORY, it still suffer from this. So this PR is to avoid 
reading unused data for one reader, by expectedTaskIds bitmap to
filter.
And this optimization is only enabled when AQE skew is applied.
No
1. UTs
Table1: 100g, dtypes: Array[(String, String)] = Array((v1,StringType), (k1,IntegerType)). 
And all columns of k1 have the same value (value = 10)
Table2: 10 records, dtypes: …
> [Improvement][AQE] Support getting memory data skip by upstream task ids

- client-spark/common/src/test/java/org/apache/spark/shuffle/reader/RssShuffleDataIteratorTest.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java
Don't throw exception if blocks are corrupted but have multi replicas
If some blocks of one replica are corrupted, maybe other replicas are not corrupted, so exception should not be thrown here if blocks have multi replicas. #369 
No
UT
> [ISSUE-369] Don't throw exception if blocks are corrupted but have multi replicas

- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessQuotaChecker.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
Lock when reading and writing the map `appAndTimes`.
To resolve #376 .
No.
Passed origin uts.
> [ISSUE-376] Fix concurrency problems may occur when the ApplicationManager register app

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
[ISSUE-392] Fix the bug in the shuffle data cleanup checker that causes false reports of disk corruption #393
Fix the bug in the shuffle data checker that causes false reports of disk corruption during cleanup.
```
[INFO] 2022-12-07 16:27:51,411 leakShuffleDataChecker ShuffleTaskManager checkLeakShuffleData - Start check leak shuffle data
[INFO] 2022-12-07 16:27:51,416 leakShuffleDataChecker LocalFileDeleteHandler delete - Delete shuffle data for appId[check] with /data1/uniffle/data/check cost 0 ms
[INFO] 2022-12-07 16:27:51,420 leakShuffleDataChecker LocalFileDeleteHandler delete - Delete shuffle data for appId[check] with /data2/uniffle/data/check cost 0 ms
[INFO] 2022-12-07 16:27:51,420 leakShuffleDataChecker LocalFileDeleteHandler delete - Delete shuffle data for appId[check] with …
```
> [ISSUE-392] Fix the bug in the shuffle data cleanup checker that causes false reports of disk corruption

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHdfsTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemoryTest.java
- storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java
- storage/src/main/java/org/apache/uniffle/storage/handler/ClientReadHandlerMetric.java
- storage/src/main/java/org/apache/uniffle/storage/handler/api/ClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/AbstractClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/ComposedClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MultiReplicaClientReadHandler.java
1.Print how much data the client read from each server.
2.Print how much data skipped.
Currently, we do not know how much data the client read from each server and how much data skipped  #390 
No
Run Uts and check logs
> [ISSUE-390] Print more infos after read finished

- common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
- common/src/main/java/org/apache/uniffle/common/rpc/MonitoringServerTransportFilter.java
Fix incorrect usage of `GRPCMetrics#setGauge`
It is a bug #244 #388 
No
No need
> [ISSUE-388][ISSUE-244][Bug] Fix incorrect usage of `GRPCMetrics#setGauge`

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandler.java
If there is no data flush to hdfs, return directly instead of throw exception as follow:
```shell
22/12/12 17:03:34 ERROR HdfsClientReadHandler: Can't list index file in  hdfs://xxx/application_1668750926041_8177885_1670835601240/0/155-155
java.io.FileNotFoundException: File hdfs://xxx/application_1668750926041_8177885_1670835601240/0/155-155 does not exist.
at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:795)
at org.apache.hadoop.hdfs.DistributedFileSystem.access$700(DistributedFileSystem.java:106)
at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:853)
at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:849)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLink …
```
> [MINOR]  If there is no data flush to hdfs, return directly instead of throw exception

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
Fix incorrect metrics of event_queue_size and total_write_handler
In current codebase, there are bugs on above metrics.
1. The metric of total_write_handler won't desc when exception happened on flushing to file
2. The metric of event_queue_size won't show the correct wait queue size. In original logic, if all events are waiting to be operated in flush thread pool, the flushQueue is always 0 and the metric value also will be 0. This is wrong.
No
Don't need.
> Fix incorrect metrics of event_queue_size and total_write_handler

- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
Fix flaky test QuorumTest#case1
Improve QuorumTest#case1 integration test cases stability   
No
No need
> [ISSUE-402] Flaky Test: QuorumTest#case1

- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
Fix flaky test QuotaManagerTest#testDetectUserResource
The process of parsing quota file is asynchronous.
https://github.com/apache/incubator-uniffle/actions/runs/3695326069/jobs/6257565865
No
No need
> Fix flaky test QuotaManagerTest#testDetectUserResource

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
1. Remove unused data structure and method
1. Save memory
No
Don't need.
> Remove unused data structure and method

- storage/src/main/java/org/apache/uniffle/storage/common/AbstractStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/HdfsStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/Storage.java
1. Remove unused methods in Storage interface
1. Remove it to make more clear.
No
Don't need
> [FOLLOWUP] Remove unused methods in Storage interface

- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/AppBalanceSelectStorageStrategyTest.java
To avoid the possible exception of reading and writing hdfs files during the test, we must ensure that `hdfs://path1` and `hdfs://path2` Are all normal paths.
for issue #430 
No.
Passed uts.
> Flaky Test: AppBalanceSelectStorageStrategyTest#selectStorageTest

- common/src/test/java/org/apache/uniffle/common/rpc/GrpcServerTest.java
Move GrpcServerTest to common.rpc package.
GrpcServer is in common.rpc package.
No.
CI.
> [Minor] Move GrpcServerTest to common.rpc package

- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/AppBalanceSelectStorageStrategyTest.java
When testing, close the scheduler thread detectStorageScheduler.
When testing, in order to ensure that multiple paths are normal, the method of manually scheduling `detectStorage` is used.
```
applicationManager.getRemoteStoragePathRankValue().get(remotePath1).getCostTime().set(0);
applicationManager.getRemoteStoragePathRankValue().get(remotePath2).getCostTime().set(0); 
```
The original repair may still fail to write the hdfs file later.
No.
origin uts.
> Fix Flaky Test: AppBalanceSelectStorageStrategyTest#selectStorageTest

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandler.java
[Improvement] Read HDFS data files with random sequence to distribute pressure #452
In PR https://github.com/apache/incubator-uniffle/pull/396 to support concurrently writing single partition's data into multiple HDFS files, it's better to randomly read HDFS data files to distribute stress in client side.
No
Existing UTs
> [ISSUE-451][Improvement] Read HDFS data files with random sequence to distribute pressure

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
Lazily create `uncompressedData`.
Save memory. #455 
No
The existing UTs is enough
> [ISSUE-455] Lazily create uncompressedData

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskInfoTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Record every partition data size for one app
This is a subtask for #378
No
1. UTs
> [ISSUE-378][HugePartition][Part-1] Record every partition data size for one app

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
If `Resource` had been removed, avoid remove twice.
When some appIds' removeResource took too much time, the `expiredAppCleanupExecutorService` in ShuffleTaskManager
would check and detect the same appId is expired multiple times. Therefore the same appId might be added to `expiredAppIdQueue` multiple times. This PR fixes #456 
No
UT
> [ISSUE-456] Avoid removeResources for multiple times

- common/pom.xml
- common/src/main/java/org/apache/uniffle/common/storage/StorageInfo.java
- common/src/main/java/org/apache/uniffle/common/storage/StorageInfoUtils.java
- common/src/main/java/org/apache/uniffle/common/storage/StorageMedia.java
- common/src/main/java/org/apache/uniffle/common/storage/StorageStatus.java
- common/src/test/java/org/apache/uniffle/common/storage/StorageInfoUtilsTest.java
- common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ServerNodeTest.java
- docs/server_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/MultiStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/StorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/StorageMediaFromEnvProvider.java
- server/src/main/resources/META-INF/services/org.apache.uniffle.storage.common.StorageMediaProvider
- server/src/test/java/org/apache/uniffle/server/LocalSingleStorageTypeFromEnvProviderTest.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/StorageMediaProvider.java
- storage/src/test/java/org/apache/uniffle/storage/common/DefaultStorageMediaProviderTest.java
- storage/src/test/java/org/apache/uniffle/storage/common/LocalStorageTest.java
ShuffleServer reports local storage info about itself. 
This PR also defines a general message definition to extend remote distributed info.
To do better shuffle assignments and get more insight of shuffle server
This addresses #448 
No
Added UTs.
> [ISSUE-448][Feature] shuffle server report storage info

- storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileHandlerTestBase.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileServerReadHandlerTest.java
1. Reset the static variable to fix LocalFileServerReadHandlerTest#testDataInconsistent
Fix flaky test
No
> [ISSUE-472] Fix Flaky Test: LocalFileServerReadHandlerTest#testDataInconsistent

- server/src/main/java/org/apache/uniffle/server/ShuffleDataFlushEvent.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
1. Exposing more info for DataFlushEvent when logging
2. Add logs when storage selected is null
1. I found sometimes some events are flushed failed but have no related logs, maybe this is caused by the null storage selected. So let's add some logs firstly.
No
Don't need
> [Improvement] Add more logs about data flush

- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
1. Use the concurrentHashmap's computeIfAbsent to keep thread safe
1. To fix potential race condition when registering remote storage info
No
Existing UTs
> Fix potential race condition when registering remote storage info

- client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigUtils.java
- common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategy.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsFileWriter.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandler.java
We can simplify and standardize some of the code.
Fixes #489
No.
Existing CI.
> [ISSUE-489][Minor] Cleanup some code

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
replaced some unnecessary concurrenthashmp with hashmap
improve performance
No
Tested with repartition workload
> [ISSUE-475][Improvement] It's unnecessary to use ConcurrentHashMap for "partitionToBlockIds" in RssShuffleWriter

- common/src/main/java/org/apache/uniffle/common/util/TripleFunction.java
- docs/server_guide.md
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
1. Introduce memory usage limit for huge partition to keep the regular partition writing stable
2. Once partition is marked as huge-partition, when its buffer size is greater than `rss.server.single.buffer.flush.threshold` value,  single-buffer flush will be triggered whatever the single buffer flush is enabled or not
1. To solve the problems mentioned by #378 
Yes. 
1. UTs
> [ISSUE-378][HugePartition][Part-2] Introduce memory usage limit and data flush

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/ShuffleUnregisterWithHdfsTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/ShuffleUnregisterWithLocalfileTest.java
- server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/HdfsStorageManagerTest.java
When one app's partial shuffles are removed, it will make other shuffle fail of flushing data due to its missing storage referenced from its appId.
Fix accidentally remove the storage of appId when unregistering partial shuffle in HdfsStorageManager
NO
1. UTs
> [ISSUE-484] Fix accidentally remove the storage of appId when unregistering partial shuffle in HdfsStorageManager

- common/src/test/java/org/apache/uniffle/common/config/ConfigUtilsTest.java
Add ConfigUtilsTest.
Improve test coverage.
No.
CI.
> [Test] Add ConfigUtilsTest

- common/src/main/java/org/apache/uniffle/common/util/Constants.java
1. Make Constants class final.
2. Make public static fields in Constants final.
3. Make default constructor of Constants private.
Code quality.
No.
Existing CI.
> [Minor] Make Constants final

- docs/operator/install.md
- docs/uniffle-migration-guide.md
Fixes errors in doc header and operator install command
Fixes errors in doc header and operator install command
No
Don't need
> Fixes errors in doc header and operator install command

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskInfoTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Introduce more metrics about huge partition  
__counter__  
1. total_require_buffer_failed_for_huge_partition
2. total_require_buffer_failed_for_regular_partition
3. total_app_num
4. total_app_with_huge_partition_num
5. total_partition_num
6. total_huge_partition_num
__Gauge__  
1. huge_partition_num 
2. app_with_huge_partition_num
Having these metrics, we should observe the concrete influence from huge partition for regular partition and huge partition number in one shuffle-server
No
1. UTs
> [ISSUE-378][HugePartition][Part-3] Introduce more metrics about huge partition

- common/pom.xml
- pom.xml
1. Replace `slf4j-log4j12` with `slf4j-reload4j`.
2. Change dependency scope to `runtime`. 
Eliminate this warning from maven:
```
[WARNING] While downloading org.slf4j:slf4j-log4j12:1.7.36
This artifact has been relocated to org.slf4j:slf4j-reload4j:1.7.36.
```
No.
CI.
> [Deps] Switch to slf4j-reload4j

- .github/workflows/parallel.yml
Bump go version of `deploy/kubernetes/operator` to 1.17.
Fix #512.
No.
CI.
> [ISSUE-512][Operator] Bump golang to 1.17

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
Fix flaky test: ShuffleServerGrpcTest#clearResourceTest. Fix #514 
It is flaky test.
In this UT, `rss.server.preAllocation.expired=5000`, so `ShuffleTaskManager#checkResourceStatus` will be invoked for every 2.5 seconds and expired app may will not be removed until 7.5 seconds after stop heartbeat. So sleep 8 seconds may not be reliable.
No
No need
> [ISSUE-514] Fix flaky test: ShuffleServerGrpcTest#clearResourceTest

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/test/java/org/apache/uniffle/server/TestShuffleFlushManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
The reason is that the flush operation is asynchronous, the first block maybe been flushed when judging the memory size.
So the solution is to support active trigger flush.
Fix #509 Flaky Test: ShuffleBufferManagerTest#shuffleFlushThreshold.
No
No need
> [ISSUE-509] Fix Flaky Test: ShuffleBufferManagerTest#shuffleFlushThreshold

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
- common/src/main/java/org/apache/uniffle/common/ShuffleBlockInfo.java
Put unavailable shuffle servers to the end of the server list when sending shuffle data if replica=1.
If we use multiple replicas and the first shuffle server becomes unavailable, sending data will take a lot of time. Because the client will always send to the first shuffle server firstly. #468 
No
UT
> [ISSUE-468] Put unavailable servers to the end of the list when sending shuffle data

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Avoid remove buffer multiple times when clear resource
This will cause memory to be released multiple times, Fix #533 
No
No need
> [ISSUE-553] Avoid removing buffer multiple times when clearing resources

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
Fix error handling in `LocalFileWriteHandler#createBasePath()`.
Throw a `RssException` in case of failure.
The return value of `baseFolder.mkdirs()` was ignored.
No.
CI.
> Result of mkdirs() is ignored in LocalFileWriteHandler#createBasePath()

- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
Optimize ShuffleServerInfo#hashCode
For better performence.
No
No need
> [Minor] Optimize ShuffleServerInfo#hashCode

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/StatusCode.java
- server/src/test/java/org/apache/uniffle/server/StatusCodeTest.java
Ensure the elements of `StatusCode` and `RssProtos.StatusCode` are the same
It may cause bugs, Fix #542 
No
UTs
> [ISSUE-542] Ensure the elements of `StatusCode` and `RssProtos.StatusCode` are the same

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
Only report to the shuffle servers that owns the blocks
I found some unnecessary log is shown in the shuffle server's log, like this 
```
[INFO] 2023-02-02 10:59:04,045 Grpc-881 ShuffleServerGrpcService reportShuffleResult - Report 0 blocks as shuffle result for the task of appId[application_1672821343673_3878453_1675303644304], shuffleId[1619], taskAttemptId[1198007]
```
As shown above, there is no necessary to report 0 blocks to shuffle server for client. Let's remove this logic.
__Improvement__
1.  for shuffle server, it reduces the log size and make its more clear
2. for client, it speeds up the client reporting due to avoiding unnecessary rpc request
No
1. UTs
> [Improvement] Only report to the shuffle servers that owns the blocks

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessManager.java
Remove "throws RuntimeException" from method signature.
There is no need to declare "throws RuntimeException".
No.
CI.
> [Minor] Cleanup "throws RuntimeException"

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Followup #249. Cleanup code and unify interfaces.
Cleanup code and unify interfaces.
No.
CI.
> [Followup #249] refactor: cleanup code and unify interfaces

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
add a shuffle-server metric about read_used_buffer_size
Show more server's info for users.
No
Don't need.
> [#567] feat: add a shuffle-server metric about read_used_buffer_size

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHdfsTest.java
- storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/ComposedClientReadHandler.java
Add enum Tier, use EnumMap to replace switch-case in ComposedClientReadHandler.
Make the code more concise.
No.
Existing CI.
> [#575] refactor: replace switch-case with EnumMap in ComposedClientReadHandler

- .github/workflows/build.yml
- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
1. Cache maven dependencies with explicit `cache-key`.
2. Cache go dependencies based on `go.sum`.
3. Expand the sequential reusable workflow.
4. Remove `experimental` option, as it's no longer needed.
5. General cleanup.
Improve CI workflows. #580
No.
https://github.com/kaijchen/incubator-uniffle/actions/runs/4140385049
> [#580] chore: improve CI workflows

- common/src/main/java/org/apache/uniffle/common/config/Reconfigurable.java
- common/src/main/java/org/apache/uniffle/common/config/ReconfigurableBase.java
- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/access/checker/AccessClusterLoadChecker.java
- docs/coordinator_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorAssignmentTest.java
I refer to Hadoop implement. I design a hot reload process. We support nodeMax at first.
It's more convenient.
add `rss.reconfigure.interval.sec`.
UT
> [#410] feat: support the hot reload of coordinator's configuration

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- deploy/kubernetes/pom.xml
- pom.xml
1. Move `kubernetes` profile from `parallel.yml` to a standalone workflow.
2. Speed up `kubernetes` workflow by skipping java tests.
Sub-task of #580
1. Cleanup regular CI `parallel.yml`.
2. Speed up `kubernetes` CI.
No.
CI.
> [#580] chore: move deploy/kubernetes to a standalone workflow

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
Simplify `ShuffleWriteClientImpl#genServerToBlocks()`.
Simplify code logic. 
No.
Covered by `ShuffleWriteClientImplTest#testSendDataWithDefectiveServers()`.
> [MINOR] refactor: simplify ShuffleWriteClientImpl#genServerToBlocks()

- .github/workflows/build.yml
- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
- .github/workflows/single.yml
1. Split unit test and integration test
2. Enable maven parallel build (`-T1C`)
3. Do not use matrix in deploy/kubernetes workflow
4. Delay some secondary workflows 
Resolve #580
Make CI faster.
In case of failure, rerun the failed part only.
No.
https://github.com/kaijchen/incubator-uniffle/actions/runs/4180474332
> [#580] chore: speed up CI workflows

- docs/server_guide.md
correct the format of server_guide doc
The markdown format is wrong in original shuffle server guide doc
No
Dont need
> [MINOR] docs: correct the format of server_guide doc

- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
Fix flaky test SimpleClusterManagerTest#updateExcludeNodesTest
Flaky test.
If `updateNodesInterval` = 2000, the first scheduling time is 4 seconds later.
https://github.com/apache/incubator-uniffle/blob/7f9b5615162bd013426ab6d58f5054fa1cf68d0c/coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java#L96-L97
No
No need
> [#613] test: SimpleClusterManagerTest#updateExcludeNodesTest

- storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
- storage/src/test/java/org/apache/uniffle/storage/common/DefaultStorageMediaProviderTest.java
Allow `mountPoint` do not contains '/'
`mountPoint` is not always contains '/', such as `rootfs`
No
No need.
> [MINOR] fix: allow `mountPoint` not containing '/'

- .github/ISSUE_TEMPLATE/flaky-test-report.yml
- .github/PULL_REQUEST_TEMPLATE
Update flaky test template and pr template.
1. Flaky test template
* Title is not consistent with other templates.
* Default parent issue is invalid. 
2. PR template
* Make the instructions shorter to read.
* Let PR author remove the instructions so they will read (hopefully).
* Update instructions, and add example for PR title. (Resolves #551)
No.
No need.
> [#551] docs: update templates for flaky test and pull request

- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
- .github/workflows/single.yml
Disable parallel build in maven
```
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  org.apache.uniffle.server.ShuffleServerTest
```
https://github.com/apache/incubator-uniffle/actions/runs/4220729609/jobs/7327285796#step:6:1317
No.
CI.
> [#580] chore(ci): disable parallel build in maven

- deploy/kubernetes/operator/pkg/controller/sync/coordinator/coordinator.go
- deploy/kubernetes/operator/pkg/controller/sync/coordinator/coordinator_test.go
- deploy/kubernetes/operator/pkg/controller/sync/shuffleserver/shuffleserver.go
- deploy/kubernetes/operator/pkg/controller/sync/shuffleserver/shuffleserver_test.go
respect volumes for rss coordinator and shuffle server
This is a bug fix
Fix: #632
Admin of rss cluster could specify the volumes which could be used to configure 
hadoop conf for example
Added UTs.
> [#632]fix: respect volumes in rss spec

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- docs/client_guide.md
Disable the localShuffleReader by default in Spark3 client
in `RssShuffleManager`, the local shuffle reader should be disabled by default (`spark.sql.adaptive.localShuffleReader.enabled=false`), as it would cause too many random small IOs and network connections with shuffle servers.
Yes
Don't need
> [#630] feat(client): Disable the localShuffleReader by default in Spark3 client

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigUtils.java
- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
Fix or supress some unchecked conventions.
Improve code quality and make the build log cleaner.
No.
No tests are changed in this PR, existing tests should cover the change.
> [MINOR] refactor: address unchecked conversions

- client-spark/spark3/pom.xml
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTest.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- docs/client_guide.md
enable LOCAL_ORDER by default for Spark AQE 
Currently, the local_order data distribution type should be activated explicitly. It's better to enable it when using AQE by default.
Fix: #635
Yes
> [#635] feat(client): enable LOCAL_ORDER by default for Spark AQE 

- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/AppBalanceSelectStorageStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java
1、Increase the method execution timeout
2、Don't need to sleep for 2s to initialize, because we have manually closed the `detectStorageScheduler`
Fix: #576
No.
Fix uts.
> [#576] test: increase timeout and remove initialization time in storage strategy tests

- coordinator/pom.xml
- coordinator/src/test/java/org/apache/uniffle/coordinator/ClientConfManagerTest.java
Mini-cluster need take some time to initialize, after the current path detection is triggered manually, we do not need to manually write the file to mini-cluster. So we can remove the dependency of this mini-cluster in Coordinator.
Fix: #649
No.
Before:
```
[INFO] Running org.apache.uniffle.coordinator.ClientConfManagerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.28 s - in org.apache.uniffle.coordinator.ClientConfManagerTest
```
After:
```
[INFO] Running org.apache.uniffle.coordinator.ClientConfManagerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.071 s - in org.apache.uniffle.coordinator.ClientConfManagerTest
```
> [#649] test: remove mini-cluster in ClientConfManagerTest

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
set coordinator id before ApplicationMaster construction, otherwise uuid is used for ` AbstractSelectStorageStrategy`
Follow up of #647
No.
Manually verified
> [#647][FOLLOWUP] set coordinator id before ApplicationMaster

- server/src/main/java/org/apache/uniffle/server/ShuffleDataFlushEvent.java
fix NPE of ShuffleDataFlushEvent's underStorage in some cases
Fix: #659
No.
Existing UTs
> [#659] fix(server): fix NPE of ShuffleDataFlushEvent's underStorage in some cases

- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Cleanup shuffleServer instance for each test
When digging into the root cause of #612, I found some problems that the shuffle server instance should be released after each test case is finished.
No.
Don't need
> [#612] test: cleanup shuffleServer instance for each test

- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
Fix memory check failure due to the execution sequence in ShuffleBufferManagerTest#bufferSizeTest
Flaky test fix: #408
No.
Existing UTs
> [#408] test: fix memory check failure in ShuffleBufferManagerTest#bufferSizeTest

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/NullOfKeyOrValueTest.java
keep consistent with vanilla spark when key or value is null
Fix: #665 
The PR of https://github.com/apache/incubator-uniffle/pull/296 has fixed the bug of NPE of value. But in some cases of production, the key also could be null. So this corner case also should keep consistent with vanilla spark.
And to prevent this logic reverting, the corresponding tests have been attached.
No.
1. Unit tests
> [#665] fix(client): keep consistent with vanilla spark when key or value is null

- client-mr/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/reader/RssShuffleReaderTest.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/TestUtils.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/reader/RssShuffleReaderTest.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- common/src/test/java/org/apache/uniffle/common/segment/LocalOrderSegmentSplitterTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/CombineByKeyTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/TestUtils.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/WriteAndReadMetricsTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetShuffleReportForMultiPartTest.java
Address unchecked conversions in tests.
Reduce warnings in build log.
No.
CI.
> [MINOR] test: address unchecked conversions in tests

- common/src/main/java/org/apache/uniffle/common/ServerStatus.java
- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
- common/src/main/java/org/apache/uniffle/common/rpc/StatusCode.java
- common/src/test/java/org/apache/uniffle/common/ServerStatusTest.java
- common/src/test/java/org/apache/uniffle/common/rpc/StatusCodeTest.java
- coordinator/pom.xml
- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorFactory.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/ServerNodeTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcServerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerInternalGrpcTest.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleServerInternalClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerInternalGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssCancelDecommissionRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssDecommissionRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssCancelDecommissionResponse.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssDecommissionResponse.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerFactory.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerInternalGrpcService.java
Add RPC logic and heartbeat logic for decommisson
Support shuffle server decommission. It is a part of #80
No.
UT
> [#80][Part-2] feat: Add RPC logic and heartbeat logic for decommisson

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
When disk detection is enabled, we can use multiple threads to read and write.
Although the detection time is relatively short, the overall acceleration is about 30%.
No.
Origin uts.
> [MINOR] Use multithreading to detect multiple disks

- docs/coordinator_guide.md
Add the usage of `AccessQuotaChecker`
Fix: #397
No.
No need.
> [#397] docs: add the usage of `AccessQuotaChecker`

- bin/rss-env.sh
- bin/start-shuffle-server.sh
Add MaxDirectMemorySize option for shuffle Server. It will be convenient for Netty.
Fix: #585 
Yes. I will add the entire document of rss-env.sh in the future.
Manual test
> [#585] feat(netty): Add MaxDirectMemorySize option for shuffle Server

- coordinator/src/test/java/org/apache/uniffle/coordinator/metric/CoordinatorMetricsTest.java
Do not start quotaManager when performing ut test of indicators.
Fix: #691
No.
Fix ut.
> [#691] test :fix flaky test CoordinatorMetricsTest#testCoordinatorMetrics

- bin/start-shuffle-server.sh
If unset the var of `MAX_DIRECT_MEMORY_SIZE`, the error of `unbound variable` will be thrown when executing the start-shuffle-server.sh
Use the ${xxx:-} to check its existence. refer to : https://bnikolic.co.uk/blog/bash-unbound-variable
No.
Tested in production env
> [#585] fix: avoid unbound variable errors in start-shuffle-server.sh

- common/src/main/java/org/apache/uniffle/common/compression/ZstdCodec.java
chore: remove unused log info
chore: remove unused log info
No.
Don't need
> chore: remove unused log info

- deploy/kubernetes/docker/base/centos/Dockerfile
- deploy/kubernetes/docker/base/debian/Dockerfile
Use JDK11 as the default java version in Dockerfile when deploying shuffle servers on K8s.
As the GC problems mentioned in #674, I upgraded the JVM version from JDK8 to JDK11 for shuffle server. And after benchmark, I found the effect of the upgrade is remarkable. And it also works well with Hadoop3.1.1
Based on above practice, it's better to use JDK11 as the default java version to improve stability
Yes
Have tested in production env.
> [#674] feat(docker): use JDK11 as the default java version in Dockerfile

- common/src/test/java/org/apache/uniffle/common/ServerStatusTest.java
- common/src/test/java/org/apache/uniffle/common/metrics/TestUtils.java
- common/src/test/java/org/apache/uniffle/common/rpc/StatusCodeTest.java
- coordinator/pom.xml
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/Response.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/request/CancelDecommissionRequest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/request/DecommissionRequest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/BaseServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/CancelDecommissionServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/DecommissionServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/NodesServlet.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/metric/CoordinatorMetricsTest.java
- docs/coordinator_guide.md
- integration-test/common/pom.xml
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
Add REST API for decommisson
Support shuffle server decommission. It is a part of #80
Env:
* Server IP: 127.0.0.1
* HTTP port: 19998
* RPC port: 19999
Decommission example:
```shell
curl -XPOST -H "Content-type:application/json" "http://127.0.0.1:19998/api/server/decommission" -d '{"serverIds:": ["127.0.0.1:19999"]}'
```
Cancel decommission example:
```shell
curl -XPOST -H "Content-type:application/json" "http://127.0.0.1:19998/api/server/cancelDecommission" -d '{"serverIds:": ["127.0.0.1:19999"]}'
```
Get server list:
```shell
curl  "http://127.0.0.1:19998/api/server/nodes?status=DECOMMISSIONING"
curl  "http://127.0.0.1:19998/api/server/nodes?status=ACTIVE"
```
UT
> [#80][Part-3] feat: add REST API for decommisson

- integration-test/common/src/test/java/org/apache/uniffle/test/DiskErrorToleranceTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/HealthCheckCoordinatorGrpcTest.java
fix UTs
Makes integration tests passed on local machines
No.
Manually verified.
> [MINOR] test: fix static field initialized before TempDir field injected

- common/src/test/java/org/apache/uniffle/common/KerberizedHdfs.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- storage/src/test/java/org/apache/uniffle/storage/HdfsTestBase.java
- storage/src/test/java/org/apache/uniffle/storage/util/ShuffleHdfsStorageUtilsTest.java
Do not assume hostname in hdfs URL.
Also, let exception be thrown in `ShuffleHdfsStorageUtilsTest` to print verbose message.
Fix #708 
No.
Tested manually
> [#708] test: do not assume hostname of hdfs mini-cluster

- common/src/test/java/org/apache/uniffle/common/KerberizedHdfs.java
- common/src/test/java/org/apache/uniffle/common/KerberizedHdfsBase.java
Use JUnit 5 managed `@TempDir` in `KerberizedHdfs` test.
The tempdir created by `KerberizedHdfs` is leaking.
It may cause test failures in some condition.
No.
Before:
```console
$ mvn test -Dtest=HadoopFilesystemProviderTest
...
$ find . -name 'serverKS.jks'
./common/target/tmp/kerberizedDfsBaseDir1821275617120252168/serverKS.jks
```
After:
```console
$ mvn test -Dtest=HadoopFilesystemProviderTest
...
$ find . -name 'serverKS.jks'
```
> [MINOR] test: fix tempdir leak in KerberizedHdfs tests

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManagerFallbackTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManagerTest.java
Rename some tests:
* SparkSQLWithDelegationShuffleManagerFallback.java => SparkSQLWithDelegationShuffleManagerFallbackTest.java
* SparkSQLWithDelegationShuffleManager.java => SparkSQLWithDelegationShuffleManagerTest.java
test class name should end with Test
No.
CI.
> [MINOR] test: test class name should end with Test

- .github/workflows/build.yml
- pom.xml
Bump `maven-shade-plugin` to `3.4.1`.
Test compile with `java.version` set to `11` and `17` in CI.
Test build in java 11 and java 17.
No.
Manually.
> [MINOR] chore(ci): test compile in java 11 and 17 with source/target version set

- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Detect SSD on Linux platform, and Assert local storage info accordingly.
Fix: #733
No.
Tested on Linux+SSD, Linux+HDD, and macOS+SSD.
```console
$ mvn test -Dtest=LocalStorageManagerTest
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.uniffle.server.storage.LocalStorageManagerTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.843 s - in org.apache.uniffle.server.storage.LocalStorageManagerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
...
```
> [#733] test: fix LocalStorageManagerTest#testGetLocalStorageInfo on Linux SSD platform

- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
Fix CoordinatorGrpcTest#shuffleServerHeartbeatTest on Linux SSD platform
```
[INFO] Results:                                                                                                                     
[INFO]                                                                                                                              
[ERROR] Failures:                                                                                                                   
[ERROR]   CoordinatorGrpcTest.shuffleServerHeartbeatTest:240 expected: <HDD> but was: <SSD>                                         
[ERROR] Errors:                                                                                                                     
[ERROR] …
```
> [MINOR] test: fix CoordinatorGrpcTest#shuffleServerHeartbeatTest on Linux SSD platform

- client-spark/spark2/src/main/java/org/apache/spark/network/util/NettyUtils.java
- common/pom.xml
- common/src/main/java/org/apache/uniffle/common/netty/IOMode.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/Encodable.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/Message.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/RpcResponse.java
- common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java
- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
- common/src/main/java/org/apache/uniffle/common/util/NettyUtils.java
- common/src/main/java/org/apache/uniffle/common/util/ThreadUtils.java
- common/src/test/java/org/apache/uniffle/common/util/ByteBufUtilsTest.java
- common/src/test/java/org/apache/uniffle/common/util/JavaUtilsTest.java
- common/src/test/java/org/apache/uniffle/common/util/NettyUtilsTest.java
- pom.xml
Add netty utils.
Add netty utils for netty replace grpc.
No.
UT.
> [#133] feat(netty): Add Netty Utils

- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Refresh application when reading memory data.
In the current logic, application will not be refreshed when reading memory data. In this case, If timeout occurs when spark driver sends heartbeat to shuffle server, the application will be expired.
Fix: #669 
No.
No need,
> [#669] improvement: refresh application when reading memory data

- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHdfsShuffleWriteHandler.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/PooledHdfsShuffleWriteHandlerTest.java
best effort to write same hdfs file when no race condition in `PooledHdfsShuffleWriteHandlerTest`
1. Reduce the file number for one partition to reduce HDFS pressure.
No.
1. UTs
> [#736] feat(storage): best effort to write same hdfs file when no race condition

- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
Fix remoteStorage path in fallbackWrittenWhenMultiStorageManagerEnableTest
Untracked files created in fallbackWrittenWhenMultiStorageManagerEnableTest
No.
Before:
```console
$ mvn test -Dtest=ShuffleFlushManagerTest#fallbackWrittenWhenMultiStorageManagerEnableTest
...
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
server/test/
nothing added to commit but untracked files present (use "git add" to track)
$ ls server/test
fallbackWrittenWhenMultiStorageManagerEnableTest/
```
After:
```console
$ mvn test -Dtest=ShuffleFlushManagerTest#fallbackWrittenWhenMultiStorageManagerEnableTest
...
$ git status
On branch fix-leak
nothing to commit, working tree clean
```
> [MINOR] test: untracked files created in ShuffleFlushManagerTest

- common/src/test/java/org/apache/uniffle/common/util/ExitUtilsTest.java
- common/src/test/java/org/apache/uniffle/common/web/JettyServerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
- storage/src/test/java/org/apache/uniffle/storage/common/ShuffleFileInfoTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsClientReadHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/KerberizedHdfsClientReadHandlerTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/KerberizedHdfsShuffleReadHandlerTest.java
Extract test from unnecessary `try-catch` blocks:
```java
@Test
public void test() throws Exception {
try {
// test
} catch (Exception e) {
e.printStackTrace();
fail();
}
}
```
It's unnecessary to wrap tests in `try-catch` block.
And it's hard to see outputs of `e.printStackTrace()` in CI.
No.
CI.
> [MINOR] test: do not wrap test in try-catch block

- storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
- storage/src/test/java/org/apache/uniffle/storage/common/DefaultStorageMediaProviderTest.java
If the storage path is not exist, get file store for its parent.
Fix: #762 
No.
UT
> [#762] If the storage path is not exist, get file store for its parent.

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/AddBlockEvent.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/TestUtils.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- common/src/main/java/org/apache/uniffle/common/util/ThreadUtils.java
- common/src/test/java/org/apache/uniffle/common/util/ThreadUtilsTest.java
1.  Introduce the `DataPusher` to replace the `eventLoop`, this could be as general part for spark2 and spark3.
2. Implement the `spill` method in `WriterBufferManager` to avoid memory deadlock.
In current codebase, if having several `WriterBufferManagers`, when each other is acquiring memory, the deadlock will happen. To solve this, we should implement spill function to break this deadlock condition.
Fix: #706 
No.
2. Newly added UTs
> [#706] Implement spill method to avoid memory deadlock

- common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java
- common/src/test/java/org/apache/uniffle/common/security/HadoopSecurityContextTest.java
1. To avoid memory leak by caching of proxy user UGI.
Fix: #772 
The Hadoop filesystem instance will be created too many time in cache, 
which will cause the shuffle server memory leak.
As we know, the filesystem cache's key is built by the scheme、authority and UGI. 
The scheme and authority are not changed every time. But for UGI, if we invoke the 
createProxyUser, it will always create a new one, that means the every invoking `Filesystem.get()`,
it will be cached due to different key.
No.
2. Added tests
> [#772] fix(kerberos): cache proxy user ugi to avoid memory leak

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHdfsShuffleWriteHandler.java
1. Remove unnecessary log
2. Make some unimportant log with debug level.
3. Remove extra spaces
Avoid too much noisy log in client side when running spark jobs
No.
Don't need
> [MINOR] chore(spark): remove noisy log in client side

- coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java
`map.getOrDefault()` => `map.computeIfAbsent()`
If do not define the user and app num  in the quota configuration file, it will appear that the `defaultUserApps` does not have the corresponding app number for this user, because we did not include the `quotaAppNum` in the `defaultUserApps`. 
**before** :
The log from coordinator is `[ERROR] 2023-03-28 19:24:11,18 Grpc-260 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 3, default app num is: null.`
**after** :
The log from coordinator is `[ERROR] 2023-03-31 14:32:21,228 Grpc-240 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 3, default app num is: 3.`
No.
Origin uts.
> [MINOR] Avoid returning null in `defaultUserApps` when quota file does't config user

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerServerFactory.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/ShuffleManagerServerFactoryTest.java
- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/main/java/org/apache/uniffle/common/rpc/RPCServerType.java
- common/src/main/java/org/apache/uniffle/common/rpc/ServerType.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorFactory.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorConfTest.java
- coordinator/src/test/resources/coordinator.conf
- server/src/main/java/org/apache/uniffle/server/ShuffleServerFactory.java
- server/src/test/java/org/apache/uniffle/server/MockedShuffleServerFactory.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerConfTest.java
1. make RPC_SERVER_TYPE an enum
2. remove ServerType definition in various places
This resolves #782
No.
Existing UTs
> [#782]refactor: restrict rss.rpc.server.type to an enum

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerOnKerberizedHdfsTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/TestShuffleFlushManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
Assign the correct shuffle server id
#720 follow-up pr
No.
Existing UTs
> [#720][FOLLOW-UP] Correct the shuffle server id

- deploy/kubernetes/operator/pkg/webhook/inspector/pod.go
- deploy/kubernetes/operator/pkg/webhook/inspector/pod_test.go
- deploy/kubernetes/operator/pkg/webhook/inspector/rss_test.go
Support delete ShuffleServer pod with Evicted status
When ShuffleServer pod is Evicted, we can't delete it.
Fix: #794 
No.
Manual testing
> [#794] feat(operator): support delete ShuffleServer pod with Evicted status

- bin/start-coordinator.sh
- bin/start-shuffle-server.sh
Ignore unrecognized jvm options and use some gc options in jdk11 to replace that of jdk8
When use jdk11, the startup scripts will fail 
No.
Just use jdk11 & jdk8 to startup the scripts without any failure
> [BUG][MINOR] Fix scripts compatible with jdk8 & jdk11

- common/src/test/java/org/apache/uniffle/common/rpc/GrpcServerTest.java
Increasing a little bit wait time.
This test is flakily fails. I run this test many times and it makes assertion fails. The failure message is as follows.
Failure:
[INFO] Running org.apache.uniffle.common.rpc.GrpcServerTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.185 s <<< FAILURE! - in org.apache.uniffle.common.rpc.GrpcServerTest
[ERROR] testGrpcExecutorPool  Time elapsed: 0.142 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2.0> but was: <0.0>
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:70)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:65)
at …
> [MINOR] test: Fix the flaky test `GrpcServerTest`

- coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java
`map.getOrDefault()` => `map.computeIfAbsent()`
If do not define the user and app num  in the quota configuration file, it will appear that the `defaultUserApps` does not have the corresponding app number for this user, because we did not include the `quotaAppNum` in the `defaultUserApps`. 
**before** :
The log from coordinator is `[ERROR] 2023-03-28 19:24:11,18 Grpc-260 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 3, default app num is: null.`
**after** :
The log from coordinator is `[ERROR] 2023-03-31 14:32:21,228 Grpc-240 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 3, default app num is: 3.`
No.
Origin uts.
> [MINOR][0.7] Avoid returning null in defaultUserApps when quota file does't config user 

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHdfsShuffleWriteHandler.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/PooledHdfsShuffleWriteHandlerTest.java
lazy initialization of `hdfsShuffleWriteHandler` when per-partition concurrent write is enabled
Without this PR, it will create too much unnecessary, when enable the 
concurrent write of per-partition and no-race condition.
This PR is to reduce unnecessary handler creation.
No.
1. UTs
> [#416] feat(hdfs): lazy initialization of hdfsShuffleWriteHandler when per-partition concurrent write is enabled

- common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java
- common/src/test/java/org/apache/uniffle/common/security/HadoopSecurityContextTest.java
1. To avoid memory leak by caching of proxy user UGI.
Fix: #772
The Hadoop filesystem instance will be created too many time in cache, which will cause the shuffle server memory leak.
As we know, the filesystem cache's key is built by the scheme、authority and UGI. The scheme and authority are not changed every time. But for UGI, if we invoke the createProxyUser, it will always create a new one, that means the every invoking `Filesystem.get()`, it will be cached due to different key.
No.
2. Added tests
> [#772][0.7] fix(kerberos): cache proxy user ugi to avoid memory leak (#773)

- deploy/kubernetes/docker/Dockerfile
Add `WORKDIR` for DOCKERFILE.
After entering the Docker, you can directly enter the home directory like https://github.com/apache/spark/blob/1820b18eea940cf7c93e6cb0e1d1d294d2d20d28/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile#L55
No.
No need.
> [MINOR] Add `WORKDIR`

- common/src/main/java/org/apache/uniffle/common/metrics/EmptyGRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/MetricsManager.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- common/src/test/java/org/apache/uniffle/common/metrics/MetricsManagerTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorGrpcMetrics.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerGrpcMetricsTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Add `tag` as label in the metrics.
So that we can separate the metrics in Grafana.
Fix: #778 
No.
fix uts.
> [#778] feat: Separate `ShuffleServer` metrics through tags

- integration-test/common/src/test/java/org/apache/uniffle/test/MultiStorageHdfsFallbackTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/MultiStorageLocalFileFallbackTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Remove unused config `SHUFFLE_EXPIRED_TIMEOUT_MS`.
No.
No need.
> [MINOR] Remove unused config `SHUFFLE_EXPIRED_TIMEOUT_MS`

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
Disable the memory spill operation.
In #714 , the memory spill is introduced to solve the dead lock. For a pity,
these part code should be handled carefully, including concurrency and data
consistency, like the fix PR #811 . And this part has bugs and I will fix these in
the next days. 
Currently, I want to revert the PR #714. But the partial refactor of #714 is still meaningful. So
I submit this PR to disable the memory spill.
No.
Don't need
> fix(client): disable spark memory spill

- common/src/main/java/org/apache/uniffle/common/config/ConfigOption.java
- common/src/main/java/org/apache/uniffle/common/config/FallbackKey.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/test/java/org/apache/uniffle/common/config/ConfigOptionTest.java
Support deprecated and fallback keys for ConfigOptions
#841 . To achieve better compatibility, it's time to support deprecated keys for ConfigOptions .
After this PR, the configOption will have the fallback and deprecated keys. Like this
```java
final ConfigOption<Integer> intConfig = ConfigOptions
.key("rss.main.key")
.intType()
.defaultValue(100)
.withFallbackKeys("rss.fallback.key1")
.withDeprecatedKeys("rss.deprecated.key1");
```
No.
2. Newly UTs
> [#841] feat(config): Support deprecated and fallback keys for ConfigOptions

- common/src/main/java/org/apache/uniffle/common/compression/ZstdCodec.java
- common/src/test/java/org/apache/uniffle/common/compression/CompressionTest.java
Fix Zstd compress dest ByteBuffer position
ZstdCodec compress method called with src&dest on Heap ByteBuffer, the dest ByteBuffer position will not update. should keep consistent with others Codec.
Fix: #593
No.
UT
> [#593][FOLLOWUP] Fix zstd compress dest ByteBuffer position

- docs/operator/install.md
Fix the metadata.annotations: Too long in `install.md`
Solve the error message encountered below when using `kubectl apply -f`
`The CustomResourceDefinition "remoteshuffleservices.uniffle.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
`
Fix: #774 
No.
No.
> [#774] docs: Fix the metadata.annotations: Too long in `install.md`

- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
Support comments in exclude node files for easy annotation of changes.
Fix: #863 
No.
Updated UT: SimpleClusterManagerTest
> [#863] feat(coordinator): support comments in exclude node files

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
We should immediately remove the `WriteBuffer` after  we use the method `createShuffleBlock` to create `ShuffeBlock`. Otherwise we will have the compressed data and uncompressed data at the same time in the memory. JVM's GC can't collect the memory of uncompressed data, because the data have the reference in the map `buffers`.
Reduce the usage of memory.
No.
CI passed.
> [MINOR] refactor: Reduce the usage of memory in the `ShuffleWriter`

- server/src/main/java/org/apache/uniffle/server/storage/SingleStorageManager.java
- storage/src/main/java/org/apache/uniffle/storage/common/HdfsStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
- storage/src/main/java/org/apache/uniffle/storage/common/Storage.java
- storage/src/test/java/org/apache/uniffle/storage/common/LocalStorageTest.java
1. Remove the meta lock, this lock is used for upload shuffle function.
2. Remove the meta of upload shuffle function.
Simplify our logic
No.
GA passed.
> [MINOR] Remove unused code of shuffle upload

- common/src/main/java/org/apache/uniffle/common/ShuffleDataResult.java
- common/src/main/java/org/apache/uniffle/common/ShufflePartitionedBlock.java
- common/src/main/java/org/apache/uniffle/common/netty/client/TransportClient.java
- common/src/main/java/org/apache/uniffle/common/netty/client/TransportClientFactory.java
- common/src/main/java/org/apache/uniffle/common/netty/client/TransportContext.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/BaseMessageHandler.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/MessageHandler.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/TransportChannelHandler.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/TransportRequestHandler.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/TransportResponseHandler.java
- common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- common/src/test/java/org/apache/uniffle/common/ShufflePartitionedBlockTest.java
- common/src/test/java/org/apache/uniffle/common/util/ByteBufUtilsTest.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/main/java/org/apache/uniffle/server/netty/StreamServer.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferTest.java
- server/src/test/java/org/apache/uniffle/server/storage/MultiStorageManagerTest.java
- server/src/test/java/org/apache/uniffle/server/storage/StorageManagerFallbackStrategyTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
- storage/src/test/java/org/apache/uniffle/storage/HdfsShuffleHandlerTestBase.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileHandlerTestBase.java
Implement ShuffleServer interface.
For #133.
No.
existing UTs.
> [#133] feat(netty): Implement ShuffleServer interface.

- client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
Make sure finishShuffle after send all shuffle data.
If type without MEMORY, some data will never flush.
I test in two mode:
* Tez local debug mode
* MR on yarn mode
Add new UT
> [#886] fix(mr): MR Client may lost data or throw exception when rss.storage.type without MEMORY.

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
The ByteBuf.release() of the block should be called after clearInFlushBuffer is called, otherwise there will be a certain probability of IllegalReferenceCountException at `ShuffleBuffer#updateShuffleData -> data.addComponent(true, block.getData().retain());`
1.Fix IllegalReferenceCountException, 
2.Added ByteBuf.release() when remove resources.
Fix: #133 
No.
existing UTs.
> [#133] feat(netty): Fix IllegalReferenceCountException.

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Fix LocalStorageManager divide by zero exception when all local disks corrupted.
No.
UT.
> [MINOR] fix: Fix LocalStorageManager divide by zero exception

- client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java
- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
- common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java
- common/src/test/java/org/apache/uniffle/common/KerberizedHadoop.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/BaseServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/CancelDecommissionServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/DecommissionServlet.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/NodesServlet.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandlerTest.java
Hi @zuston @advancedxy
Any comments and suggestions would be appreciated if you are available, thank you.
Eliminate `raw use of parameterized class`
Fix: #417
No.
current UT
> [#417] refactor: Eliminate raw use of parameterized class

- .github/workflows/sequential.yml
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
- client-tez/src/test/java/org/apache/tez/common/TezIdHelperTest.java
Fix tez workflow
For now, workflow does not build tez client.
> [MINOR] refactor: Fix tez workflow and checkstyle

- .github/workflows/parallel.yml
https://github.com/apache/incubator-uniffle/actions/runs/5141497645/jobs/9254329542?pr=916 fail, but error logs upload fail, so we can't analyze the cause.
Upload logs are below: 
```
Run actions/upload-artifact@v3
With the provided path, there will be 53 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Error: Artifact name is not valid: test-reports-mr:hadoop3.2. Contains the following character:  Colon :
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash / …
```
> [MINOR] fix: Error logs upload fail

- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
Add @Test to activate test case
Just for Add @Test to activate test case
No.
unit test
> [MINOR] improvement(mr): Add @Test to activate test case

- README.md
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- deploy/kubernetes/operator/examples/configuration.yaml
- docs/server_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/test/resources/server.conf
Eleminate rss.server.heartbeat.timeout replaced with rss.server.heartbeat.interval
https://github.com/apache/incubator-uniffle/issues/927
Yes, `rss.server.heartbeat.timeout` will effect nothing
UnitTest
> [#927] Improvement: improve the control of server heartbeat

- client-tez/pom.xml
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/test/java/org/apache/tez/common/GetShuffleServerResponseTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/TezRemoteShuffleManagerTest.java
1. RssDAGAppMaster will start rpc server and process getShuffleAssignments requests(assign uniffle works)   from map/reduce task to shuffle write/read
2. Keep those uniffle works heatbeat with coordinator in application lifecycle
Fix: #819 
No.
UT
> [#819 ] feat(operator): Tez ApplicationMaster supporting RemoteShuffle

- common/src/main/java/org/apache/uniffle/common/rpc/MonitoringServerTransportFilter.java
Fix incorrect metric grpc_server_connection_number
Fix: #933 
No.
Existing UT
> [#933][0.7] fix: incorrect metric grpc_server_connection_number

- .asf.yaml
Add new collaborators:
lifeSo
zhengchenyu
xumanbu
Collaborators can run the workflow without committer's approval and manage issues.
1. lifeSo is responsible for Apache Tez framework. 
2. zhengchenyu is responsible for the support of Hadoop 3.2.
3. xumanbu is responsible for the support of Netty.
They have contributed some features and improvements.  It will be more convenient for them to become collaborators.
No.
No need.
> [MINOR] Add new collaborators

- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssSimpleFetchedInputAllocator.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/RssSimpleFetchedInputAllocatorTest.java
Add Simple Fetched Allocator to allcation memory or disk for shuffle data
Fix: https://github.com/apache/incubator-uniffle/issues/854
No.
unit test case
> [#854][FOLLOWUP] feat(tez): Add Simple Fetched Allocator to allocation memory or disk for shuffle data

- common/src/main/java/org/apache/uniffle/common/ShuffleDataResult.java
- common/src/main/java/org/apache/uniffle/common/netty/MessageEncoder.java
- common/src/main/java/org/apache/uniffle/common/netty/buffer/FileSegmentManagedBuffer.java
- common/src/main/java/org/apache/uniffle/common/netty/buffer/ManagedBuffer.java
- common/src/main/java/org/apache/uniffle/common/netty/buffer/NettyManagedBuffer.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/GetLocalShuffleDataResponse.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/Transferable.java
- common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
part-1: 
1. add a ManagedBuffer instead ByteBuf to hold ShuffleData.
2. ShuffleResultData & GetLocalShuffleDataResponse use ManagedBuffer instead of ByteBuf
3. MessageEncoder write support sendfile
Fix: #590 
No.
Integration Testing
> [#590][part-1] ManagedBuffer instead ByteBuf to hold ShuffleData 

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/reader/RssShuffleReaderTest.java
support read and write serialized columnar data
Fix: #940
No.
UnitTest, it's covered by the existing test
> [#940] feat: Support columnar shuffle with gluten

- common/src/main/java/org/apache/uniffle/common/ServerStatus.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/NodesServlet.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Obtain the list of ServerNodes whose heartbeat is lost from a Coordinator Server
Obtain the list of ServerNodes whose unhealthy from a Coordinator Server
There is no interface for viewing lost and unhealthy lists
Fix: #937
Updated UT: SimpleClusterManagerTest
> [#937] feat: Add rest api for servernode list of losing connection and unhealthy

- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssConcatenatedMergedKeyValueInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssConcatenatedMergedKeyValuesInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssOrderedGroupedInputLegacy.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssOrderedGroupedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssOrderedGroupedMergedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssUnorderedKVInput.java
- client-tez/src/test/java/org/apache/tez/runtime/library/input/RssOrderedGroupedKVInputTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/input/RssSortedGroupedMergedInputTest.java
Add Rss Input Class to begin Tez input task
Fix: https://github.com/apache/incubator-uniffle/issues/854
No.
unit test
> [#854][FOLLOWUP] feat(tez): Add Rss Input Class to begin Tez input task

- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
since https://github.com/apache/incubator-uniffle/issues/755, the thread name should not written with %d, or else will throw exception.
> [MINOR] fix(tez): fix thread factory name

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
1. Make it possible to extend  uniffle in spark3.
2. Optimize the shuffleMetric when use columnar shuffle
https://github.com/apache/incubator-uniffle/issues/940
No.
Unit test
> [#940] improvement: Optimize columnar shuffle integration

- cli/src/main/java/org/apache/uniffle/cli/CLIContentUtils.java
- cli/src/test/java/org/apache/uniffle/cli/CLIContentUtilsTest.java
- cli/src/test/resources/CLIContentResult
Provides a tool class to format CLI output content.
Fix: #978
The CLI command display is more beautiful.Similar to：
Added UT.
> [#978][Improvement] Provides a tool class to format CLI output content

- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/common/UmbilicalUtils.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutput.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/TezRemoteShuffleManagerTest.java
Three improvement about configuration will be done in this issue.
- 1 For now, tez client use rss_conf.xml to delivery configuration. As https://github.com/apache/incubator-uniffle/pull/966 is applied, we can delivery configuration by edge conf.
- 2 delivery dynamic configuration from coordinator, then override the tez client configuration.
- 3 delivery configuration from client side.
- 1. rss_conf.xml is unnecessary.
- 2. dynamic configuration from coordinator are not applied.
- 3. config in client side can not delivery to input/ouput.
integration test, unit test, test in yarn cluster, test in tez local mode.
> [#983] improvement(tez): Optimize tez client delivery configuration

- client-tez/src/main/java/org/apache/tez/common/InputContextUtils.java
- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTask.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffle.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssOrderedGroupedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssUnorderedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutput.java
- client-tez/src/test/java/org/apache/tez/common/InputContextUtilsTest.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManagerTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleSchedulerTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/input/RssOrderedGroupedKVInputTest.java
Optimize the method of obtain the vertex id.
For now, vertex id is extract from vertex name. This way only support the vertex name like "Map 0", "Reduce 1", generally generated from hive.
For tez examples, the vertex name is arbitrary, so we can't get the vertex id. So we need a new way to get vertex id.
Fix: #986
integration test, unit test, test in yarn cluster, test in tez local mode.
> [#986] improvement(tez): Optimize the method of obtain the vertex id.

- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/test/java/org/apache/tez/runtime/library/output/OutputTestHelpers.java
- client-tez/src/test/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutputTest.java
set the partition class for RssUnorderedKVOutput.
If the partition class is not set for RssUnorderedKVOutput, will throw error:
```
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2534)
  at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2499)
  at …
```
> [#989] fix(tez): parition class is not set for RssUnorderedKVOutput.

- common/src/main/java/org/apache/uniffle/common/web/CoalescedCollectorRegistry.java
- common/src/main/java/org/apache/uniffle/common/web/resource/BaseMetricResource.java
- common/src/main/java/org/apache/uniffle/common/web/resource/MetricResource.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/metric/CoordinatorMetricsTest.java
- docs/coordinator_guide.md
- docs/index.md
- docs/metrics_guide.md
- docs/server_guide.md
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Support get all metrics by one request
Fix: #1001 
`/metrics` and `/prometheus/metrics` will return all metrics of the server
UT
> [#1001] improvement: support get all metrics by one request

- .github/workflows/parallel.yml
- common/pom.xml
- integration-test/common/pom.xml
- integration-test/tez/pom.xml
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezCartesianProductTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezHashJoinTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezIntegrationTestBase.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezJoinIntegrationTestBase.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezOrderedWordCountTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezSimpleSessionExampleTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezSortMergeJoinTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountTest.java
- pom.xml
- server/pom.xml
- storage/pom.xml
Add integration test for tez
To construct tez test pipeline, we need integration test.
integration test.
> [#957] feat(tez): Tez examples integration test

- client-tez/src/main/java/org/apache/tez/common/UmbilicalUtils.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/main/java/org/apache/tez/dag/app/security/authorize/RssTezAMPolicyProvider.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutput.java
- client-tez/src/test/java/org/apache/tez/dag/app/TezRemoteShuffleManagerTest.java
support secure cluster.
issue: #991
unit test, test on yarn cluster.
> [#991] Improvement(tez): TezRemoteShuffleManager support secure cluster.

- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
When we convert task attempt id to long, consider real taskAttemptID = taskAttemptID - (appAttemptId - 1) * 1000, the logical only apply to mr. tez should remove this.
If appAttemptId is 2, taskattemptid will be normalized to negative value, it is unexpected.
Fix: #992
> [#992] fix(tez): convertTaskAttemptIdToLong should not consider appattemptId

- client-tez/src/test/java/org/apache/tez/dag/app/TezRemoteShuffleManagerTest.java
Add storage type configs in TezRemoteShuffleManagerTest
StorageType defaults to null, which blocks #980.
No.
Tested with #980.
> [MINOR] test(tez): add storage type configs in TezRemoteShuffleManagerTest

- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
Add output mapOutputByteCounter metrics
add this metrics to fix reducing the number of tasks
Fix: #972 
No.
ut
> [#972 ] fix(tez): Add output mapOutputByteCounter metrics

- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
- common/src/test/java/org/apache/uniffle/common/rpc/GrpcServerTest.java
I observed a previous fix injected some delay to fix the flaky test, but I believe that fix might be unstable in a CI environment or when run on different machines, given the dependency on some constant wait time. I suggest a new way to fix the test by adding some synchronization for the test execution only. I at first identify the source code location whose slow execution leads to the flaky test failure, where if common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java#157 slows the grpcMetrics.incGauge() and grpcMetrics.setGauge(), then the test fails (https://github.com/apache/incubator-uniffle/blob/master/common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java#L157 and https://github.com/apache/incubator-uniffle/blob/master/common/src/main/java/org/apache/uniffle/c …
> [#388][FOLLOWUP] fix: Fix the flaky test GrpcServerTest

- bin/uniffle
- bin/uniffle-function.sh
We support starting and stopping services using CLI commands.
- Command 1: uniffle --daemon start coordinator
```
coordinator start success, is running as process 61743.
```
- Command 2: uniffle --daemon stop coordinator
```
coordinator stop success.
```
- Command 3: uniffle --daemon status coordinator
> If the service is started
```
coordinator is running as process 62087.
```
> If the service is stoped
```
coordinator is stopped.
```
Supporting service start and stop functionality using CLI commands is part of this PR.
No.
Testing environment verification.
> [#846] feat(cli): Service's start & stop & restart through Cli.

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Make shuffle manager client RPC timeout configurable
Fix: #973 
No.
current UT and Integration testing
> [#973] improvement: Make shuffle manager client RPC timeout configurable

- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
- client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- server/src/test/java/org/apache/uniffle/server/MockedShuffleServerGrpcService.java
feat #477 
support getShuffleResult throws FetchFailedException.
No.
Exiting UTs, Already added getShuffleResult failed, see `MockedShuffleServerGrpcService`.
> [#477] feat(spark): support getShuffleResult throws FetchFailedException.

- client-tez/src/test/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutputTest.java
tez-client, RssOrderedPartitionedKVOutputTest add close func unit test
tez-client, RssOrderedPartitionedKVOutputTest add close func unit test
Fix: #1019  
No.
unit test.
> [#1019] test(tez) RssOrderedPartitionedKVOutputTest add close func unit test

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
1. Guarantees thread safe by only allowing spills to be triggered by the current thread
2. Using  the same logic of processing blocks in the `RssShuffleWriter` and `WriteBufferManager` to ensure the data consistency
Fix: #808 
In this PR, we use the two ways to solve the concurrent problem for `addRecord` and `spill` function
1. For the same thread, the spill will be invoked when adding  records and unsuffcient memory. This case could ensure 
thread safe. So it will do the spill sync.
2. When spill is invoked by other consumers, it will do nothing in this thread and just set a signal to let owner to release when adding record.
After this, we could avoid lock(may cause performance regression, like #811 did) to keep thread safe 
No.
1. UTs
> [#808] feat(spark): ensure thread safe and data consistency when spilling

- client-tez/src/test/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutputTest.java
tez-client, RssUnorderedPartitionedKVOutputTest add close func unit test
tez-client, RssUnorderedPartitionedKVOutputTest add close func unit test
Fix: #1018 
No.
unit test.
> [#1018] test(tez) RssUnorderedPartitionedKVOutputTest add close func ut

- common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/NettyMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/RPCMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerNettyMetrics.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/main/java/org/apache/uniffle/server/netty/StreamServer.java
- server/src/main/java/org/apache/uniffle/server/netty/StreamServerMetricHandler.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
add NettyMetrics for StreamSever 
Fix: #640
No.
UT
> [#640] feat(netty): Metric system for netty server

- .asf.yaml
Stop forwarding GitHub issues to dev mail list,
instead, forwarding them to issues mail list.
Many contributors are not subscribed to the dev mail list,
probably because it's noisy (~200 emails per month).
Let's leave dev mail list for the most important (or general) messages, 
such as: votes, announcements, general discussions, user feedbacks. 
Users still wishing to receive all GitHub issues updates through email
should subscribe to `issues@uniffle.apache.org`, or alternatively,
watch the GitHub repository. 
No need.
> [MINOR] chore(asf): stop forwarding GitHub issues to dev mail list

- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- docs/client_guide.md
- integration-test/tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterForWordCountWithFailures.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezIntegrationTestBase.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountWithFailuresTest.java
Avoid recompute succeeded task. Detailed information see #1011
Here only 2.a, 2.b, 2.c is solved. 2.d will not be solved in this PR.
Fix: #1011
New config 'rss.avoid.recompute.succeeded.task' was introduced, default value is false. If set to true, we won't recompute the succeed task when the reason of recompute is about node failed.
>Note: I suggest change default value to true after running on production cluster some months.
integration test and test in yarn cluster.
> [#1011] feat(tez): Avoid recompute succeeded task.

- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
Currently the number of threads in the send data thread pool in WriteBufferManager is fixed at 1, making it configurable.
Fix: #[1064](https://github.com/apache/incubator-uniffle/issues/1064)
No.
Existing tests can cover it.
> [#1064] improvement(tez): Make shuffle data send thread pool configurable in WriteBufferManager.

- README.md
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
When configured as README.md, MapReduce will throw these errors. It is not helpful for beginner.
```
Exception in thread "main" java.lang.IllegalArgumentException: mapreduce.rss.client.retry.max(100) * mapreduce.rss.client.retry.interval.max(10000) should not bigger than mapreduce.rss.client.send.check.timeout.ms(600000)
at org.apache.hadoop.mapreduce.RssMRUtils.validateRssClientConf(RssMRUtils.java:307)
at org.apache.hadoop.mapreduce.v2.app.RssMRAppMaster.main(RssMRAppMaster.java:189)
```
and
```
Exception in thread "main" java.lang.IllegalArgumentException: The value of null should be one of [GRPC_NETTY, GRPC]
at org.apache.uniffle.client.util.ClientUtils.validateClientType(ClientUtils.java:144)
at org.apache.hadoop.mapreduce.v2.app.RssMRAppMaster.main(RssMRAppMaster.java:141)
```
test …
> [MINOR] fix(mr): fix default value

- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
Currently, it only checks for blocks that failed to send after all buffer data has been sent. This check also needs to be moved forward into the addRecord method, allowing it to fail fast.
Fix: # ([1068](https://github.com/apache/incubator-uniffle/issues/1068))
No.
Add more test case in WriteBufferManager.
> [#1068] improvement(tez): Fail fast in WriteBufferManager when failed to send shuffle data to shuffle sever.

- pom.xml
Add the JDK 11 removed jar package.
Fix:  #1066
No.
Tested in our cluster.
> [#1066] fix: The Jetty server fails to start when compiled with JDK 8 but runtime version is JDK 11.

- README.md
I have added the Slack link to the README.md to make it easier for anyone to get access to the Slack workspace.
Without the Slack link it was confusing if anyone wanted to contact the team.
Fix: #1095
No.
N/A
> [#1095] doc: Add slack link to the readme.md

- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/resources/log4j.properties
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
Currently, it only checks for blocks that failed to send after all buffer data has been sent. This check also needs to be moved forward into the addRecord method, allowing it to fail fast.
Fix: https://github.com/apache/incubator-uniffle/issues/1100
No.
Add more test cases.
> [#1100] improvement(mr): Fail fast in SortWriteBufferManager when failed to send shuffle data to shuffle server.

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/test/java/org/apache/uniffle/server/LocalStorageCheckerTest.java
- server/src/test/java/org/apache/uniffle/server/StorageCheckerTest.java
Currently, the local_storage_used_space will show the disks used total size. 
But if it is in the colocation with Yarn Nodemanager, this is not enough.
So this issue is to introduce the metric of local_storage_uniffle_used_space to 
show the uniffle used space.
Fix: #1074 
No.
1. UTs
> [#1074] feat: Introduce the metric of `local_storage_uniffle_used_space`

- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
Add output mapOutputRecordCounter metrics
Add this metrics to fix reducing the number of tasks
Fix: #972 
No.
ut
> [MINOR] fix(tez): Add output mapOutputRecordCounter metrics

- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- integration-test/tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterForWordCountWithFailures.java
Only when the JVM is about to exit, the server resources will be released. In some scenarios, it will occupy server resources for a long time. For example, when enable history logging service and timeline service.
Fix: https://github.com/apache/incubator-uniffle/issues/1101
No.
Existing tests can cover it.
> [#1101] improvement(tez): Release server resources as soon as possible in RssDAGAppMaster.

- common/src/main/java/org/apache/uniffle/common/metrics/MetricReporterFactory.java
- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
New utility method to cover dynamic class loading in RSSUtils
Fix: #434 
No.
CI passed.
> [#434] refactor: New utility method to cover dynamic class loading in RSSUtils

- client-tez/pom.xml
- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTask.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/TezRemoteShuffleManagerTest.java
- pom.xml
Apply remote storage configuration.
Reduce does not load remote storage path. If shuffle data have flushed to remote storage, reduce can not read. 
Fix: #1081
test in cluster.
> [#1081] fix(tez): shuffle can not read the data which is flushed to hdfs

- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
tez application should use login ugi to  communicate with shuffle sever, but not applicationid ugi.
Fix: #1109
No.
test in real cluster.
> [#1109] fix(tez): Fix the user of remote storage.

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Introduce the hdfs host as the total_hadoop_write_data metric label
We will write apps of different businesses apps into different HDFS.
For further iterative optimization, we need to expose the write capacity of 
different HDFS to evaluate the total write capacity of different business lines.
Yes. More metrics are exposed.
1. UTs
> [#1114] feat: introduce hdfs host as the total_hadoop_write_data metric label

- docs/client_guide.md
Add the document for tez-client.
Fix: #1124 
No.
> [#1124] docs: modify the document for tez-client

- common/src/test/java/org/apache/uniffle/common/KerberizedHadoop.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/KerberizedShuffleTaskManagerTest.java
Fix the bug that shuffle server can not delete remote storage path in security hdfs.
Fix: #1111
unit test and test in cluster.
> [#1111] fix: Shuffle server can not delete remote storage path in security cluster

- deploy/kubernetes/docker/Dockerfile
- deploy/kubernetes/docker/build.sh
- deploy/kubernetes/pom.xml
Add the HADOOP_VERSION for Docker image.
Fix: #951 
No.
By hand.
> [#951] build(operator): Add the HADOOP_VERSION for Docker image.

- docs/client_guide.md
Add the document for tez-client.
Fix: #1124 
No.
> [#1124] docs(tez): Add the document for tez-client

- README.md
Fix: #1143
Before:
After:
No.
Screenshots attached.
> [#1143] docs: Correct sequence number text by reducing paragraph indentation by 1 space

- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
- client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
Unregister shuffle explicitly when Spark application is stopped.
Fix: https://github.com/apache/incubator-uniffle/issues/1132
No.
Add more test cases.
> [#1132] improvement(spark): Unregister shuffle explicitly when Spark application is stopped.

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
The principle of data being released is that the data has been sent. 
However, under the current implementation, all blocks will be released in the last event. 
Once executed out of order, the unsent block data will be released prematurely, which is wrong.
Fix: #1127 
No.
1. existing UTs
> [#1127] fix(netty): incorrect bytebuf release for ShuffleBlockInfo data in client side

- .asf.yaml
Remove leixm from collaborators.
@leixm has become committer
No.
No need.
> [MINOR] Remove leixm from collaborators

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
Add labels with disk path for local storage total_localfile_write_data metrics.
Fix: https://github.com/apache/incubator-uniffle/issues/1108
No.
Add more unit test case.
> [#1108] feat(server): Add labels with disk path for local storage total_localfile_write_data metrics.

- common/src/test/java/org/apache/uniffle/common/util/ChecksumUtilsTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithKerberizedHadoopTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RepartitionTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/ContinuousSelectPartitionStrategyTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetShuffleReportForMultiPartTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Hi @kaijchen @zuston @jerqi @xianjingfeng 
Any comments and suggestions would be appreciated if you are available, thank you.
Cleanup residue files in tmp directory after tests
Fix: #722 
No.
current UT
> [#722] test: cleanup residue files in tmp directory after tests

- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileClientReadHandler.java
If we use the off heap memory and then we use the method `getData`, we will copy the off heap memory to heap data memory. So we should avoid using it in the Netty mode.
Fix: #1161
No.
Code Review
> [#1161] improvement: Reduce the data copy

- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
Generally, one application will execute multiple DAGs, and there is no correlation between the DAGs. Therefore, after completing the execution of a DAG, you can unregister the relevant shuffle data. Otherwise, when there are many DAGs, an application will occupy a large amount of resources for a long period of time.
Fix: https://github.com/apache/incubator-uniffle/issues/1165
No.
Existing test cases.
> [#1165] improvement(tez): Unregister shuffle data after completing the execution of a DAG. 

- common/src/main/java/org/apache/uniffle/common/ShuffleDataResult.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferTest.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileHandlerTest.java
Exposing `ShuffleDataResult.getDataLen` method for being invoked by metrics and tests.
Exposing `ShuffleDataResult.getDataLen` method for being invoked by metrics and tests.
Fix: #1164 
No.
No need.
> [#1164] refactor: Exposing the getDataLen method for ShuffleDataResult

- README.md
- docs/client_guide.md
before:
after:
If the wrong `spark.serialier` is set, the above error will be reported in registerShuffle, and `spark.serializer` should actually be used.
No.
Screenshots attached.
> [MINOR] docs: Fix spark.serializer in README and client_guide

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Use callback and queue to optimize the write time.
Fix: #1177
No.
CI passed.
> [#1177] improvement: Reduce the write time of tasks

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
1、reget a transportClient in ShuffleServerGrpcNettyClient.sendShuffleData RetryCmd
2、add ShuffleServerGrpcNettyClient construct with maxRetryAttempts (but in this pr init ShuffleServerGrpcNettyClient with default maxRetryAttempts(3))
Fix: #1175
No.
Existing UT.
> [#1175] fix(netty): Retry failed with StacklessClosedChannelException after channel closed

- deploy/kubernetes/operator/pkg/controller/config/config.go
get namespace from user configuration
Fix: #1182 
No.
Tested in our cluster.
> [#1182] fix(operator): The LeaderElectionNamespace of the rss-controller is hard-coded to kube-system.

- README.md
- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java
- common/src/main/java/org/apache/uniffle/common/security/SecurityConfig.java
- common/src/main/java/org/apache/uniffle/common/security/SecurityContextFactory.java
- common/src/test/java/org/apache/uniffle/common/KerberizedHadoopBase.java
- common/src/test/java/org/apache/uniffle/common/security/HadoopSecurityContextTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
add `RSS_SECURITY_HADOOP_KERBEROS_PROXY_USER_ENABLE` with default true,
if set false, shuffle data storing in security hdfs use UGI user.
Fix:  #1192
add `RSS_SECURITY_HADOOP_KERBEROS_PROXY_USER_ENABLE` with default true
add `HadoopSecurityContextTest.testSecuredDisableProxyUser()`  test case
> [#1192] improvement: Add RSS_SECURITY_HADOOP_KERBEROS_PROXY_USER_ENABLE conf for storing shuffle data

- common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
zerocopy from Protobuf's ByteString to Netty's ByteBuf
#1198 . Improve the performance when using the GRpc
No.
existing unit tests
> [#1198] improvement: zerocopy from Protobuf's ByteString to Netty's ByteBuf

- docs/server_guide.md
- server/src/main/java/org/apache/uniffle/server/HealthScriptChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/test/java/org/apache/uniffle/server/HealthScriptCheckerTest.java
- server/src/test/resources/healthy-script1.sh
- server/src/test/resources/healthy-script2.sh
- server/src/test/resources/healthy-script3.sh
- server/src/test/resources/healthy-script4.sh
add HealthScriptChecker for execute special health check shell script
ref: https://github.com/apache/hadoop/blob/trunk/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/health/NodeHealthScriptRunner.java
Fix:  #1202
`rss.server.health.checker.script.path` : The health script file path for HealthScriptChecker, if script file should have execute permission.
`rss.server.health.checker.script.exe.timeout`: The health script file execute timeout seconds
add ut
> [#1202] improvement: Add HealthScriptChecker for execute special health check shell script

- deploy/kubernetes/operator/Makefile
The ci pipeline use the latest revive package. But the version v1.3.4 will cause the failure of CI. So I use the older version package to pass the CI pipeline
https://github.com/apache/incubator-uniffle/actions/runs/6273740844/job/17060784342
Fix: #1204
No.
CI passed.
> [ISSUE-1204] chores(ci): Fix the ci pipeline of Kubernetes

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
Optimize cleanupStorageSelectionCache method in LocalStorageManager.
Fix: https://github.com/apache/incubator-uniffle/issues/1209
No.
Exist UTs.
> [#1209] improvement(server): Optimize cleanupStorageSelectionCache method in LocalStorageManager.

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/KerberizedShuffleTaskManagerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Check again if the App has expired when removing resources.
Fix: https://github.com/apache/incubator-uniffle/issues/1211
No.
Add more tests.
> [#1211] fix: Unexpectedly removing resources even though the App has re-registered shuffle later.

- cli/src/main/java/org/apache/uniffle/client/RestClientImpl.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBuffer.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssRemoteMergeManagerImpl.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-tez/src/main/java/org/apache/tez/common/TezClassLoader.java
- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- common/src/main/java/org/apache/uniffle/common/filesystem/HadoopFilesystemProvider.java
- common/src/main/java/org/apache/uniffle/common/netty/client/TransportClientFactory.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/TransportRequestHandler.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/access/checker/AccessCandidatesChecker.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileServerReadHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
Improve invoking LOG.debug when LOG.isDebugEnabled() is true .
Fix: #1201
No.
> [#1201] improvement: only invoking LOG.debug when LOG.isDebugEnabled() is true

- client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/AssignmentStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/BasicAssignmentStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategy.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorAssignmentTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleAssignmentsRequest.java
- proto/src/main/proto/Rss.proto
We need to provide an RPC interface for reassigning ShuffleServer, with support for excluding some ShuffleServer lists.
2, the Task of Stage starts, solid steps, in accordance with the green by ShuffleManager Client RPC interface gets to be written for shuffleIdToShuffleHandleInfo …
> [#825][part-1] feat(spark): Add the RPC interface for reassigning ShuffleServer

- README.md
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleDataIo.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleDriverComponents.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkIntegrationTestBase.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
Implement ShuffleDataIo
https://github.com/apache/incubator-uniffle/issues/802
Yes. To use spark dynamicAllocation, user should set `spark.shuffle.sort.io.plugin.class` to `org.apache.spark.shuffle.RssShuffleDataIo`, otherwise spark3.5 will fail
Integration test
Manual test
> [#802] feat(spark): Implement ShuffleDataIo

- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
- client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/AssignmentWithTagsTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorAssignmentTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
As the title
https://github.com/apache/incubator-uniffle/issues/1091
No.
unit test
> [#1091] refactor: Refactor the writer code with builder pattern

- .gitignore
Follow up #1218 
For #1206 
No.
Needn't
> [#1206] chore(rust): ignore generated proto code in git

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/WriteAndReadMetricsTest.java
Add a little wait time before verify the result
Usually this happens in spark2.3 integration test
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.317 s <<< FAILURE! - in org.apache.uniffle.test.WriteAndReadMetricsTest
Error:  test  Time elapsed: 28.47 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <55> but was: <54>
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
at org.apache.uniffle.test.SparkIntegrationTestBase.verifyTestResult(S …
```
> [#1219] fix(test): Fix the flaky test `WriteAndReadMetricsTest`

- client-tez/pom.xml
- client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssInMemoryMerger.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssMergeManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffle.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssInMemoryMergerTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssMergeManagerTest.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezIntegrationTestBase.java
Add new merger manager for remote spill.
In a cloud scenario, the storage of the machine that performs the job is very small. The merge phase often uses disk. The remote spill allows remote shuffle service job to use as little disk as possible.
Fix: #1231
| config | description |
| --- | --- |
| tez.rss.reduce.remote.spill.enable | Whether to enable remote spill |
| tez.rss.remote.spill.storage.path | the remote spill path |
| rss.reduce.remote.spill.replication | the replication of remote fs |
| rss.reduce.remote.spill.retries | try times for remote fs |
unit test, integration test, tez examples on cluster.
> [#1231] feat(tez): Support remote spill in merge stage.

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/TestUtils.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/response/SendShuffleDataResult.java
The ShuffleServer corresponding to the block that failed to be sent needs to be reported.
3. In the …
> [#825][part-2] feat(spark): Report failed blocks and a list of ShuffleServer

- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleTest.java
> [#1254] fix(test): Fix the flaky test RssShuffleTest.

- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/EventFetcherTest.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleAssignmentsRequest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
1. Some empty collections are only for read, so replace it with Collections.emptyList(), Collections.emptySet(), Collections.emptyMap().
2. In spark, writer client construct a new List prepared for shuffleBlockInfos per record, But in most case there is no blocks produced.
3. Set proper initial value.
https://github.com/apache/incubator-uniffle/issues/1256
No.
unit test
> [#1256] refactor: optimize collections contruction

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Pass InterruptedException in requestExecutorMemory.
Fix:  #1261
No.
> [#1261] fix(spark): Throw out InterruptedException for sleep in requestExecutorMemory

- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleTest.java
> [#1254][FOLLOWUP] fix(test): Fix the flaky test RssShuffleTest.

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/TestUtils.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/response/SendShuffleDataResult.java
As title
```
[INFO] Running org.apache.uniffle.test.ContinuousSelectPartitionStrategyTest
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 59.195 s <<< FAILURE! - in org.apache.uniffle.test.ContinuousSelectPartitionStrategyTest
Error:  resultCompareTest  Time elapsed: 55.751 s  <<< ERROR!
org.apache.spark.SparkException: 
Job aborted due to stage failure: Task 6 in stage 1.0 failed 1 times, most recent failure: Lost task 6.0 in stage 1.0 (TID 16) (fv-az391-410.nf14wd45lyte3l5gjbhk121dmd.jx.internal.cloudapp.net executor driver): org.apache.uniffle.common.exception.RssException: Timeout: Task[16_0] failed because 9 blocks can't be sent to shuffle server in 30000 ms.
at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:350)
at …
```
> [#825][part-2][followup] fix(writer): Apply a thread safety way to track the blocks sending result

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/reader/RssShuffleReaderTest.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/reader/RssShuffleReaderTest.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RSSStageResubmitTest.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleManagerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssPartitionToShuffleServerRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssPartitionToShuffleServerResponse.java
- proto/src/main/proto/Rss.proto
ShuffleReader and ShuffleWriter get the ShuffleServer corresponding to the partition from ShuffleManager
2, the Task of Stage starts, solid steps, in accordance with the green by ShuffleManager Client RPC interface gets to be written for shuffleIdToShuffleHandleInfo ShuffleServer …
> [#825][part-3] feat(spark): Get the ShuffleServer corresponding to the partition from ShuffleManager

- pom.xml
- release/asf-settings.xml
- release/publish_maven_artifacts.sh
add scripts for publishing maven releases
Fix: #1275
No.
CI
> [#1275] chore: add scripts for publishing maven releases

- build_distribution.sh
Building spark shaded modules in `build_distribution.sh`
Spark shaded clients will be miss without this pr.
No.
Manually execute `build_distribution.sh`
> [MINOR] fix: missing to build spark shaded modules

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleManagerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleWriteFailureRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssReportShuffleWriteFailureResponse.java
- proto/src/main/proto/Rss.proto
Send the write exception to the ShuffleServer to the ShuffleManager.
3. In the Stage, if Task fails to …
> [#825][part-4] feat(spark): Report write failures to ShuffleManager

- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/RemoteFetchedInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssSimpleFetchedInputAllocator.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssTezBypassWriter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssUnorderedKVInput.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/RssSimpleFetchedInputAllocatorTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssTezBypassWriterTest.java
- common/src/main/java/org/apache/uniffle/common/RemoteStorageInfo.java
When unordered input fetch data from shuffle server, if the fetched data is too large, will spill data to local filesystem.
This PR provide another way: spill data to remote filesystem.
Fix: #1246 
No.
unit test and tez example test on cluster.
> [#1246] feat(tez): Support remote spill for unordered input.

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerServerFactory.java
- common/src/main/java/org/apache/uniffle/common/metrics/EmptyGRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/NettyMetrics.java
- common/src/main/java/org/apache/uniffle/common/metrics/RPCMetrics.java
- common/src/test/java/org/apache/uniffle/common/rpc/GrpcServerTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorGrpcMetrics.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcServerTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerNettyMetrics.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerGrpcMetricsTest.java
Change transportTime and processTime summary to Thread Pool Instead of block
Closes #1271
Change transportTime and processTime summary to Thread Pool Instead of block
Not block GRPC Thread
Fix: #1271 
No.
No
> [#1271] improvement(server): change transportTime and processTime summary to Thread Pool Instead of block

- release/create-package.sh
- release/publish_to_svn.sh
add scripts for publishing tarballs to svn
Publishing is more convenient
No.
Manually testing while publishing 0.8.0-rc2.
> [MINOR] chore: add scripts for publishing tarballs to svn

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleManagerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReassignServersRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssReassignServersReponse.java
- proto/src/main/proto/Rss.proto
Adds the RPC interface to reassign the ShuffleServer list.
3. In the Stage, if Task fails to write …
> [#825][part-5] feat(spark): Adds the RPC interface to reassign the ShuffleServer list.

- rust/experimental/server/src/app.rs
- rust/experimental/server/src/grpc.rs
From the past experience, I found the sync lock performance is better than the tokio lock,
especially on the critical path.
And the flatten `dashmap` will be faster than the multiple level `dashmap`.
So this PR is to improve above performance point in `app.rs` 
For better performance
No.
Existing UTs
> [#1296] improvement(rust): use std RWLock to replace tokio lock for better performance

- rust/experimental/server/src/grpc.rs
- rust/experimental/server/src/main.rs
- rust/experimental/server/src/metric.rs
introduce the unified grpc latency metrics for all requests
For #1294 
Currently, we calculate the request duration for every request in the service codebase, 
which is ugly and scattered everywhere.
BTW, the current request duration metrics is limited to critical paths.
So, it's necessary to use the tonic's layer mechanism to summary the grpc latency metrics.
And the reason of no deleting original latency metrics is the difference of each other, 
the metrics embedded in the layer will be greater than in the service code, 
because request will spend sometime to decoding the message, the diff time is valuable for observability.
Yes. After applying this patch, the latency metrics of request like P99 could be gotten like this.
`histogram_quantile(0.99, …
> [#1294] feat(rust): introduce the unified grpc latency metrics for all requests

- rust/experimental/server/src/app.rs
- rust/experimental/server/src/metric.rs
- rust/experimental/server/src/store/hybrid.rs
Add total_received_data metric
Currently, the total_received_data metric has been introduced, the total_read_data is also necessary
No.
> [#1293]feat(rust): Add total_read_data metric

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/exception/RssSendFailedException.java
- common/src/main/java/org/apache/uniffle/common/exception/RssWaitFailedException.java
Added logic that failed to send ShuffleServer.
3. In the Stage, if Task fails to write blocks to the …
> [#825][part-6] feat(spark): Added logic that failed to send ShuffleServer.

- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/Response.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/AppInfoVO.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/CoordinatorConfVO.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/UserAppNumVO.java
Add a web dashboard for uniffle, providing some dashboard apis
Provide data support for dashboard
Fix: #960 
Users can obtain relevant metrics information through the new API
Existing UT.
> [#960][part-1] feat(dashboard): Add some dashboard interfaces.

- rust/experimental/server/Cargo.lock
- rust/experimental/server/Cargo.toml
- rust/experimental/server/src/main.rs
- rust/experimental/server/src/signal.rs
Make each grpc service thread listens the socket to improve request throughput.
I‘m always digging the way to solve the request throughput when the writing concurrency is 400. And then I found the few people talk about this, which makes me confused until I see this https://github.com/hyperium/tonic/issues/1405#issuecomment-1805099818 .
From this blog https://medium.com/@fujita.tomonori/scalable-server-design-in-rust-with-tokio-4c81a5f350a3,
I try to do this optimization, and then do some terasort test. I found the peek receive data speed from 1.2G/s -> 2.0G/s, it works ! And the latency becomes low. And the whole processing time reduces from 20min -> 8.5min
No.
No need
> [#1307] feat(rust): make each thread listen the socket to improve throughput in tonic

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
In Spark2, after a write failure, ShuffleBlockInfo is not built using the new shuffle server after the shuffle server is reassigned.
Fix: #1309
No.
Existing UT.
> [#1309] fix(spark): WriteBufferManager in Spark2 does not use a reassigned shuffle server.

- client-mr/core/src/main/java/org/apache/hadoop/mapred/RssCombineOutputCollector.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBuffer.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
Support combine operation in map stage.
Fix: #1300 
No.
Tested by UT, especially `WordCountTest`
before this PR, Map Output
```
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 America 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
847 Chinese 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 Japan 0001
645 apple 0001
645 apple 0001
645 apple 0001
645 apple 0001
645 apple 0001
645 …
```
> [#1300]feat(mr): Support combine operation in map stage for mr engine. 

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RSSStageDynamicServerReWriteTest.java
- server/src/test/java/org/apache/uniffle/server/MockedShuffleServerGrpcService.java
Write Stage resubmit and dynamic shuffle server assign integration tests.
3. In the Stage, if Task …
> [#825][part-7] feat(spark): Write Stage resubmit and dynamic shuffle server assign integration tests.

- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
fix flaky test ShuffleTaskManagerTest#checkAndClearLeakShuffleDataTest.
*ShuffleTaskManagerTest.checkAndClearLeakShuffleDataTest:940 expected:
\<false\> but was: \<true\>*
The cause of the problem:
Application in `shuffleTaskInfos` is removed first, and then remove the directory in the local disk.
Refer: org.apache.uniffle.server.ShuffleTaskManager#removeResources
No.
Repeat it for 100 times in my development enviroment.
> [MINOR] test: flaky test ShuffleTaskManagerTest#checkAndClearLeakShuffleDataTest

- rust/experimental/server/src/store/memory.rs
add code to improve purge unit test to detect whether arc reference is 0
Fix: #1308 
No.
1. UT
> [#1308] improvement(rust): detect whether data has been purged in UT

- bin/start-dashboard.sh
- bin/stop-dashboard.sh
- build_distribution.sh
- common/pom.xml
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/JettyServerFront.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/config/DashboardConf.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/proxy/WebProxyServlet.java
- dashboard/src/main/webapp/src/api/api.js
- dashboard/src/main/webapp/src/components/ApplicationPage.vue
- dashboard/src/main/webapp/src/components/CoordinatorServerPage.vue
- dashboard/src/main/webapp/vue.config.js
- docs/dashboard_guide.md
- pom.xml
Provides a start-stop script for the dashboard.
Fix: #960 
Start and close the dashboar module using shell scripts.
UT.
> [#960][part-3] feat(dashboard): Provides a start-stop script for the dashboard.

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
record the appId and shuffleIds in the log when clearing resource fail
Fix: #1342
No.
Neen't
> [#1342] improvement(server): dump appId when clearing resource fails

- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
- .github/workflows/single.yml
This is a follow-up to eef0134. The change will (hopefully) invoke `./mvnw` (wrapper) instead of the `mvn` command in CI builds, making the local development builds and CI builds equivalent to the applied `maven` version. 
It's prudent to have the development builds as close to the ones executed by CI/CD system as possible.
No.
I believe having a PR builder pass should suffice.
> [MINOR] improvement: use mvn wrapper in CI builds.

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Specify name for dataTransferPool
`dataTransferPool` thread pool did not specify name.
No.
minor fix
> [MINOR] Specify name for dataTransferPool

- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Release bytebuf explicitly when `requiredId` is expired and cache failure occurs
Fix: #1335
No.
Internal production tests.
> [#1335] fix(server)(netty): release bytebuf explicitly when requiredId is expired and cache failed

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Fix NPE for ShuffleWriteClientImpl.unregisterShuffle.
Since the `id` of `RssShuffleManager` in Executor is assigned in `getWriter`, this means that the `id` may be null before `getWriter`, so this may cause NPE to occur in `ShuffleWriteClientImpl.unregisterShuffle`.
error log:
```
23/12/12 14:25:47 ERROR RssShuffleManager: Errors on closing shuffle write client
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.unregisterShuffle(ShuffleWriteClientImpl.java:751)
at org.apache.spark.shuffle.RssShuffleManager.stop(RssShuffleManager.java:591)
at org.apache.spark.SparkEnv.stop(SparkEnv.scala:90)
at org.apache.spark.executor.Executor.stop(Executor.scala:335)
at …
```
> [MINOR] fix(spark): Fix NPE for ShuffleWriteClientImpl.unregisterShuffle

- deploy/kubernetes/operator/Makefile
Specify the version of `goimports`.
fix kubernetes ci pipeline.
https://github.com/apache/incubator-uniffle/actions/runs/7190065186/job/19582604526
No.
CI passed.
> [MINOR] chore: fix kubernetes ci pipeline

- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Currently, the tags label is generated by self when registering metrics for shuffle-server. This is wrong, which will lack the GRPC or NETTY_GRPC tags.
Fix: #1348
No.
Neen't
> [#1348] improvement(metrics): Unify tags generation for shuffle-server metrics reporter

- bin/start-dashboard.sh
- bin/utils.sh
- dashboard/pom.xml
- docs/dashboard_guide.md
simplify dependency and correct the startup script.
Fix: #960 
No.
Needn't.
> [#960] fix(dashboard): simplify dependency and correct the startup script

- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Release bytebuf explicitly when `requiredId` is expired and cache failure occurs
Fix: #1335
No.
Internal production tests.
> [#1335][0.8] fix(server, netty): release bytebuf explicitly when requiredId is expired and cache failed #1357

- server/src/main/java/org/apache/uniffle/server/DirectMemoryUsageReporter.java
- server/src/main/java/org/apache/uniffle/server/NettyDirectMemoryTracker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
ShuffleServer add Direct Memory Metric for monitor
Fix: # (https://github.com/apache/incubator-uniffle/issues/1189)
No.
> [#1189] feat(server): Add netty used direct memory size metric

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/RemoteStorageInfo.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- docs/client_guide/spark_client_guide.md
Introduce the config to control whether to use local hadoop conf for remote storage by default
I want to deploy one uniffle cluster to serve for spark jobs in multiple hadoop clusters. So I hope the remote storage config could be loaded from the default hdfs-site.xml in the classpath.
Yes.
> [#1364] feat(client): introduce option to control whether to use local hadoop conf for remote storage by default

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
precheck bytebuffer whether is direct before uncompress, and rebuild the temp bytebuffer.
For #1358 . But this PR is not the fundamental solution
No.
> [#1358] fix(spark): pre-check bytebuffer whether is direct before uncompress

- README.md
- bin/start-coordinator.sh
- bin/start-shuffle-server.sh
- bin/utils.sh
- pom.xml
provide distribution jars with hadoop
Fix: #1369 
1. For `MEMORY_LOCALFILE` mode, there is no need to set HADOOP_HOME, which is hard for some users to set up this environment.
2. Using the embedded hadoop jars, it could has the higher version of hadoop to use the latest features.
Yes
> [#1369] feat: Provide distribution with Hadoop dependencies

- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
What changes were proposed in this pull request?
compatibility with jdk8 when call JavaUtils.newConcurrentMap
Why are the changes needed?
Fix: https://github.com/apache/incubator-uniffle/issues/1387
Does this PR introduce any user-facing change?
No.
How was this patch tested?
> [1387] improvement: compatibility with jdk8 when call JavaUtils.newConcurrentMap

- bin/start-coordinator.sh
- bin/start-dashboard.sh
- bin/start-shuffle-server.sh
Exit on OutOfMemoryError
Fix: https://github.com/apache/incubator-uniffle/issues/460
No.
> [#460] improvement: Exit on OutOfMemoryError

- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
The container does not exit because shuffleclient is not closed
The container does not exit because shuffleclient is not closed.
Fix: https://github.com/apache/incubator-uniffle/issues/1157
No.
unit test and prd runs.
> [#1157] fix(tez): Container not exit because shuffle client is not closed

- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Release the direct memory in the finally block to prevent memory leaks.
For [#1391](https://github.com/apache/incubator-uniffle/issues/1391)
No.
By running server successfully.
> [#1391] fix(server): Direct memory may leak in exceptional scenarios in shuffle server.

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Fixes exceptions that do not need to be returned.
Fix: #825 
No.
Existing UT.
> [#825][followup] fix(spark):Fix without returning an exception.

- rust/experimental/server/Cargo.lock
- rust/experimental/server/Cargo.toml
- rust/experimental/server/README.md
- rust/experimental/server/src/app.rs
- rust/experimental/server/src/error.rs
- rust/experimental/server/src/grpc.rs
- rust/experimental/server/src/lib.rs
- rust/experimental/server/src/main.rs
- rust/experimental/server/src/mem_allocator/mod.rs
- rust/experimental/server/src/store/hdfs.rs
- rust/experimental/server/src/store/hybrid.rs
- rust/experimental/server/src/store/localfile.rs
- rust/experimental/server/src/store/mem/mod.rs
- rust/experimental/server/src/store/mem/ticket.rs
- rust/experimental/server/src/store/memory.rs
- rust/experimental/server/src/store/mod.rs
- rust/experimental/server/tests/write_read.rs
To improve the rust based server performance and fix some bugs
Fix: #1407 
No.
Existing tests
> [#1407] improvement(rust): Some bug fix and optimization

- client-mr/core/pom.xml
- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
- client-tez/pom.xml
Fix a bug that was introduced from [#343](https://github.com/apache/incubator-uniffle/issues/343).
The Netty native libraries have never been successfully shaded. PR [#924](https://github.com/apache/incubator-uniffle/pull/924) is not working at all.
For [#1409](https://github.com/apache/incubator-uniffle/issues/1409)
No.
By running the RSS Netty client with Epoll mode successfully.
> [#1409] fix(client): Netty Epoll is unavailable for the RSS Client.

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleWriteClientImplTest.java
Fix a bug that was introduced from [#1228](https://github.com/apache/incubator-uniffle/pull/1228).
When the RssConf variable is not null, it gets overridden by a new RssConf, resulting in the loss of existing parameters within RssConf.
For [#1403](https://github.com/apache/incubator-uniffle/issues/1403)
No.
By setting RSS client configs successfully.
> [#1403] fix(client): RSS client configurations are not working.

- .github/workflows/rust.yml
- rust/experimental/server/Cargo.lock
- rust/experimental/server/Cargo.toml
- rust/experimental/server/README.md
- rust/experimental/server/build.rs
- rust/experimental/server/src/error.rs
- rust/experimental/server/src/store/hdfs.rs
Introduce hdfs-native crate as the native integration.
For: #1414 
Native rust hdfs client could simplify the hadoop dependency and avoid JNI invoking cost.
No.
Internal tests on Hadoop 3.1.2
> [#1414] feat(rust): introduce native hdfs client

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Add metrics of expired pre-allocated buffer size
Fix: https://github.com/apache/incubator-uniffle/issues/1356
No.
test on PRD
> [#1356] improvement: add metric of total expired pre-allocated buffers

- coordinator/src/main/java/org/apache/uniffle/coordinator/util/CoordinatorUtils.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/conf/LegacyClientConfParserTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/conf/YamlClientConfParserTest.java
- coordinator/src/test/resources/dynamicClientConf.legacy
- coordinator/src/test/resources/dynamicClientConf.yaml
As title
Fix: #974 
Before:
`rss.coordinator.remote.storage.cluster.conf hadoop-ns01,dfs.hosts=a,b,c,dfs.service=sssss`
will trigger a bug.
After:
`rss.coordinator.remote.storage.cluster.conf hadoop-ns01,dfs.hosts=a,b,c,dfs.service=sssss`
will work correctly.
Yes.
unit test
> [#974] fix(coordinator): Dynamic remote storage conf invalid for `LegacyClientConfParser`

- common/src/main/java/org/apache/uniffle/common/exception/NoBufferException.java
- common/src/main/java/org/apache/uniffle/common/exception/NoBufferForHugePartitionException.java
- common/src/main/java/org/apache/uniffle/common/exception/NoRegisterException.java
- common/src/main/java/org/apache/uniffle/common/rpc/StatusCode.java
- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- proto/src/main/proto/Rss.proto
- rust/experimental/server/src/grpc.rs
- rust/experimental/server/src/proto/uniffle.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Explicitly throw `BUFFER_LIMIT_OF_HUGE_PARTITION` instead of `NO_BUFFER`
Fix:  https://github.com/apache/incubator-uniffle/issues/1119
No.
unit test
> [#1119] improvement(client): Explicitly throw `BUFFER_LIMIT_OF_HUGE_PARTITION`

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- docs/client_guide/spark_client_guide.md
support custom hadoop config in client side
It's necessary to support user specify custom hadoop config in client side for remote storage.
For #1416 
Yes. 
The prefix key of `spark.rss.hadoop.*` for Hadoop conf. 
For Spark like that: `spark.rss.hadoop.fs.defaultFS=hdfs://rbf-x1`, 
this will be as `fs.defaultFS=hdfs://rbf-x1` for Hadoop storage
UTs
> [#1416] feat(spark): support custom hadoop config in client side

- conf/log4j.properties
Improve the log4j settings to avoid annoying messages, by adding separate loggers in the log4j.properties file.
For [#1435](https://github.com/apache/incubator-uniffle/issues/1435)
No.
By running the process successfully and check the log4j output.
> [#1435] improvement: Improve log4j settings to avoid annoying messages

- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
Add note that `processedBlockIds` can be a superset of `blockIdBitmap`. Add quick check if `processedBlockIds` is equal to `blockIdBitmap`. In that case, there is no need to clone and `AND` the bitmaps.
The logic is equivalent but more performant when `processedBlockIds` is not a superset of `blockIdBitmap` (when no other blocks than the `blockIdBitmap` are retrieved).
No.
Existing tests in `ShuffleReadClientImplTest` cover this.
> [MINOR] refactor: avoid unnecessary bitmap clone and AND

- server/src/main/java/org/apache/uniffle/server/HealthCheck.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Make state transitions in ShuffleServer robust.
Avoids the following race conditions / undesired state transitions:
- ShuffleServer is decommissioning, then getting unhealthy, which stops decommissioning
- ShuffleServer is in any non-active state, getting unhealthy, turns active when healthy
Fix: #1433
No.
Untested.
> [#1433] fix(server): Race conditions with ShuffleServer state

- server/src/main/java/org/apache/uniffle/server/NettyDirectMemoryTracker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Fix PR [#1363](https://github.com/apache/incubator-uniffle/pull/1363).
NettyDirectMemoryTracker will not be started currently.
It's a followup PR for [#1363](https://github.com/apache/incubator-uniffle/pull/1363).
No.
Existing UTs.
> [#1189][FOLLOWUP] fix(server): Start NettyDirectMemoryTracker.

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Save the previous exception in advance to prevent it from being lost during the next retry.
This is the follow up pr of  [#1344](https://github.com/apache/incubator-uniffle/pull/1344)
No.
Existing UTs.
> [#1267][followup] improvement(client): The previous exception may be discarded when OOM occurs

- pom.xml
Force to use the UNIX line ending when using spotless-maven-plugin.
For [#1453](https://github.com/apache/incubator-uniffle/issues/1453)
No.
By running `./mvnw spotless:apply -Pspark3 -Pspark2 -Ptez -Pmr -Phadoop2.8` on Windows.
> [#1453] improvement: Force to use the UNIX line ending when using spotless-maven-plugin

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManagerFallbackStrategy.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManagerFallbackStrategy.java
- server/src/main/java/org/apache/uniffle/server/storage/RotateStorageManagerFallbackStrategy.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/storage/HybridStorageManagerTest.java
allow specifying negative fallback threshold to avoid event being discarded
Fix: #1428 
No.
Unit tests
> [#1428] fix(server): fallback invalid when local storage can't write

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
- common/src/test/java/org/apache/uniffle/common/ShuffleServerInfoTest.java
Improve the error log message for checkBlockSendResult.
As described in [#1464](https://github.com/apache/incubator-uniffle/issues/1464), it will print out the shuffle server's IP and ports.
For [#1464](https://github.com/apache/incubator-uniffle/issues/1464)
No.
Manually.
> [#1464] improvement(spark): Improve the error log message for checkBlockSendResult

- common/src/main/java/org/apache/uniffle/common/util/JvmPauseMonitor.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
introduce the JvmPauseMonitor to detect the gc pause
Fix: #1466 
We have some loop check logic in shuffle-server, sometimes the GC pause will make some pre-allocated buffer  removed.
If we have this monitor, we will find out this reason rather than guess. Although the JVM metrics are also valid.
No.
Existing tests
> [#1466] feat(server): introduce the JvmPauseMonitor to detect the gc pause

- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
Release the memory when a flush event is dropped.
For [#1462](https://github.com/apache/incubator-uniffle/issues/1462)
No.
Existing UTs.
> [#1462] fix(server): Memory may leak when flushQueue is full

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java
introduce total hdfs write data size for huge partition:
1. `total_hadoop_write_data_for_huge_partition` is introduced
For #1467, it is to show the hdfs spill data size for huge partition
No.
> [#1467] feat(server): introduce total hdfs write data size metric for huge partition

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
The output of failed shuffle servers' result has not been successfully deduplicated.
It's a followup PR for [#1465](https://github.com/apache/incubator-uniffle/pull/1465).
No.
Existing UTs.
> [#1464][FOLLOWUP] improvement(spark): print abnormal shuffle servers that blocks fail to send

- rust/experimental/server/Cargo.lock
- rust/experimental/server/Cargo.toml
- rust/experimental/server/README.md
- rust/experimental/server/src/app.rs
- rust/experimental/server/src/config.rs
- rust/experimental/server/src/error.rs
- rust/experimental/server/src/grpc.rs
- rust/experimental/server/src/main.rs
- rust/experimental/server/src/store/hdfs.rs
- rust/experimental/server/src/store/hybrid.rs
- rust/experimental/server/src/store/local/disk.rs
- rust/experimental/server/src/store/localfile.rs
- rust/experimental/server/src/store/memory.rs
- rust/experimental/server/src/store/mod.rs
1. fix(rust): fast fail of writing to localfile when disk is unhealthy
2. fix(rust): incorrect failed buffer required cnt metrics
3. feat(rust): support fallback to hdfs when local store is invalid
4. btw: support huge partition flushing to hdfs directly
5. feat(rust): avoid setting hdfs config in server client
For #1407, hope bringing up this into production env.
No.
Unit tests.
> [#1407] feat(rust): support multiple spill policies and simplify hdfs config

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
Disable dynamic allocation shuffle tracking by default.
Fix: #1490
No.
> [#1490] improvement(spark3): Disable dynamic allocation shuffle tracking by default

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Method `ShuffleTaskManager.addFinishedBlockIds` should check the actual number of bitmaps matches the requested `bitmapNum`.
Calling `ShuffleTaskManager.addFinishedBlockIds(String appId, Integer shuffleId, …, bitmapNum)` initializes an array of bitmaps for the first call per `(appId, shuffleId)`, according to the `bitmapNum`. Subsequent calls must use the same `bitmapNum`, otherwise you get into trouble:
- with a larger `bimapNum` you would see an out-of-bound exception, e.g.: `java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3`
- a lower `bimapNum` would silently add the blocks to the wrong bitmap, potentially hiding them from shuffle read clients
No.
Test added to `ShuffleTaskManagerTest.testGetFinishedBlockIds`.
> [MINOR] fix: Assert actual number of bitmaps matches bitmapNum

- client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java
Make `ShuffleReadClientImplTest.writeDuplicatedData` call `ATOMIC_LONG.getAndIncrement`, rather than `ATOMIC_LONG.incrementAndGet`.
In `ShuffleReadClientImplTest`
- method `writeTestData` calls `ATOMIC_LONG.getAndIncrement()`
- method `writeDuplicatedData` calls `ATOMIC_LONG.incrementAndGet()`
Calling `writeTestData` after `writeDuplicatedData` produces a duplicate sequence number, which is unexpected. All code paths in `ShuffleReadClientImplTest` that increment `ATOMIC_LONG` should use the same order of get and increment.
No.
Manually.
> [MINOR] fix: Get and increment ATOMIC_LONG in that order everywhere

- client/src/test/java/org/apache/uniffle/client/TestUtils.java
Do not check for blocks that have already been found in data stream.
The method `TestUtils.validateResult` would pass check of a data stream returned by `readClient.readShuffleBlockData()` that contains duplicate blocks (let's say the first block in `expectedData`) while overall cardinality of blocks match expectation (let's say that first block is duplicated `expectedData.size()`-times). Such a situation should throw an assertion error.
Further, the inner loop can be left on match, which saves computation time.
No.
Not tested.
> [MINOR] fix: Identify duplicate blocks in TestUtils.validateResult

- .github/workflows/parallel.yml
- .github/workflows/sequential.yml
- .github/workflows/single.yml
- README.md
- build_distribution.sh
- pom.xml
The `dashboard` module should be moved into a profile and and **not build by default**.
It can be activated via `-Pdashbboard`.
Building and especially incrementally compiling during development always builds dashboard completely. All other modules finish in seconds, but dashboard takes minutes. This increases the iteration cycle from seconds to minutes.
Compiling Uniffle with `dashboard`:
```
./mvnw compile -Pdashboard
…
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Uniffle 0.9.0-SNAPSHOT:
[INFO] 
[INFO] Apache Uniffle ..................................... SUCCESS [  0.804 s]
[INFO] Apache Uniffle Protocols ........................... SUCCESS [  4.486 s]
[INFO] Apache Uniffle Common .............................. SUCCESS …
```
> [MINOR] build: Move dashboard module into profile

- rust/experimental/server/src/store/hdfs.rs
- rust/experimental/server/src/store/hybrid.rs
- rust/experimental/server/src/store/localfile.rs
- rust/experimental/server/src/store/memory.rs
- rust/experimental/server/src/store/mod.rs
Avoid checking storage type of spill in runtime to improve performance.
improve performance.
No.
Existing uts
> [#1407] fix(rust): avoid checking storage type in runtime

- rust/experimental/server/src/store/localfile.rs
fix(rust): dont panic when no available local disks
make spill data fallback to hdfs when no available local disks
No.
online tests
> [#1407] fix(rust): dont panic when no available local disks

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
avoid storage selection cache accidentally deleted
Fix: (#1501) 
No.
Unit tests
> [#1501] fix(server): storage selection cache accidentally deleted when clearing stage level data.

- rust/experimental/server/src/error.rs
- rust/experimental/server/src/store/hdfs.rs
If client using the `memory_local` type, but the server is using `memory_hdfs` type, 
server will panic when getting shuffle data. This PR is to avoid this.
This is the sub-tasks for #1407 .
No.
needn't
> [#1407] fix(rust): return error when getting data from hdfs by client

- .github/workflows/build.yml
- .github/workflows/parallel.yml
- .github/workflows/test-results.yml
Reports test results in Github UI.
Individual results of test failures are easier to access than scrolling through long job logs: [example](https://github.com/EnricoMi/incubator-uniffle/runs/21197842666)
Test stats are nicely presented in corresponding pull request: https://github.com/EnricoMi/incubator-uniffle/pull/2#issuecomment-1925719425
No.
Manual.
> [MINOR] CI: Report test results

- common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java
INFO log level should be used in RetryUtils. Because these log messages are not actual errors.
It's a followup PR for [#1411](https://github.com/apache/incubator-uniffle/pull/1411).
No.
Existing UTs.
> [#1267][FOLLOWUP] improvement(client): INFO log level should be used in RetryUtils

- rust/experimental/server/src/error.rs
- rust/experimental/server/src/metric.rs
- rust/experimental/server/src/store/hybrid.rs
drop events and release memory when errors happened
Drop events to release memory to ensure service stable
Sub tasks for #1407 
No.
Online tests
> [#1407] fix(rust): drop events and release memory when errors happened

- .github/workflows/build.yml
- .github/workflows/rust.yml
- .github/workflows/test-results.yml
Rework events that trigger `build` and `rust` workflows: the `push` event only triggers on branches `master`, `branch-*` and tags, not on any other branch. Other branches are already covered by the `pull_request` event.
Further, allows to trigger those workflows on branches and tags manually.
Currently you have both `push` and `pull_request` run on commits done to branches that have pull requests. Branches are eventually merged into one of the above branches via pull requests. Hence, running `push` on those branches is pretty redundant.
No.
Manually.
> [MINOR] CI: Rework build and rust workflow events

- rust/experimental/server/src/app.rs
- rust/experimental/server/src/grpc.rs
- rust/experimental/server/src/proto/uniffle.proto
Provide dedicated unregister app rpc interface for rust based server
Fix: #1476
No.
> [#1476] feat(rust): Provide dedicated unregister app rpc for rust based server

- deploy/kubernetes/integration-test/e2e/set-up-local-cluster.sh
- deploy/kubernetes/integration-test/e2e/start-e2e.sh
Do not invoke bash scripts via `sh ./SCRIPT.sh`, but `./SCRIPT.sh`.
These bash scripts are invoked via `sh ./SCRIPT.sh`, which overrides the shebang line in the script, effectively executing the scripts via `/bin/sh`. The scripts require `bash` though, so the invocation fails.
No.
Manually tested.
> [MINOR] fix(deploy): Fix invocation of kubernetes bash scripts

- server/src/main/java/org/apache/uniffle/server/NettyDirectMemoryTracker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
We need to know the exact direct memory usage of `PooledByteBufAllocator` in `Netty`.
So we should introduce metrics for Netty's `pinnedDirectMemory` and `usedDirectMemory`.
A sub PR for: https://github.com/apache/incubator-uniffle/pull/1519
No.
Existing UTs.
> [#1472][part-4] feature(server): Introduce metrics for Netty's pinnedDirectMemory and usedDirectMemory

- pom.xml
- server/pom.xml
Make missing `shuffle-server` dependencies explicit in `server/pom.xml`.
The `shuffle-server` module has dependencies that are not explicitly stated in the `pom.xml`, but transitively available. Notably, these are `commons-collections` and `hadoop-common`:
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java#L27-L29
Run
```
./mvnw dependency:tree -pl org.apache.uniffle:shuffle-server -am
```
to see the dependency tree:
```
[INFO] -----------------< org.apache.uniffle:shuffle-server >------------------
[INFO] Building Apache Uniffle Server 0.9.0-SNAPSHOT                      [6/6]
[INFO]   from server/pom.xml
[INFO] --------------------------------[ jar …
```
> [MINOR] fix(pom): Add missing shuffle-server dependencies to work with -Ptez

- common/src/main/java/org/apache/uniffle/common/netty/TransportFrameDecoder.java
- common/src/main/java/org/apache/uniffle/common/netty/buffer/NettyManagedBuffer.java
Improve the robustness of methods `ShuffleDataResult.release()` and `ShuffleIndexResult.release()` to fix occasional IllegalReferenceCountException issues in extremely rare scenarios.
A sub PR for: https://github.com/apache/incubator-uniffle/pull/1519
No.
Existing UTs.
> [#1472][part-3] fix(client): Fix occasional IllegalReferenceCountException issues in extremely rare scenarios

- common/src/main/java/org/apache/uniffle/common/netty/protocol/Decoders.java
Reuse ByteBuf when decoding shuffle blocks instead of reallocating it
A sub PR for: https://github.com/apache/incubator-uniffle/pull/1519
No.
Existing UTs.
> [#1472][part-2] fix(server): Reuse ByteBuf when decoding shuffle blocks instead of reallocating it

- rust/experimental/server/src/config.rs
- rust/experimental/server/src/main.rs
Server will start multiple grpc service to improve throughout, which will 
be executed by grpc runtime blocking threads, this is hard to configure the number of 
blocking threads.
Let's use the worker threads to start all tasks.
Subtask for #1407 
No.
Online tests.
> [#1407] fix(rust): use grpc runtime worker threads and adjust default runtime config

- build_distribution.sh
Allow to not build some modules when running `./build_distribution.sh`:
./build_distribution.sh --without-mr --without-tez --without-spark --without-dashboard
Some modules may not be needed and especially `dashboard` takes very long to build.
No.
Manually.
> [MINOR] feat(build): Allow to build distribution without some modules

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/FailingTasksTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RSSStageDynamicServerReWriteTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RSSStageResubmitTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkTaskFailureIntegrationTestBase.java
Use map index and task attempt number as the task attempt id in Spark3.
This requires to rework the bits of the blockId to maximize bit utilization for Spark3:
https://github.com/apache/incubator-uniffle/blob/b924acacb0c555370a593f3a069187cf8b8081d7/common/src/main/java/org/apache/uniffle/common/util/Constants.java#L30-L35
Ideally, the `TASK_ATTEMPT_ID_MAX_LENGTH` is set equal to `PARTITION_ID_MAX_LENGTH` + the number of bits required to store the largest task attempt number. The largest task attempt number is `maxFailures - 1`, or `maxFailures` if speculative execution is enabled (configured via `spark.speculation` and disabled by default). The `maxFailures` is configured via `spark.task.maxFailures` and defaults to 4. So by default, two bits are required to store the largest attempt …
> [#134] improvement(spark3): Use taskId and attemptNo as taskAttemptId

- dashboard/pom.xml
When building the dashboard from within an environment without direct internet access you may need to setup a mirror for node and npm download.
This change adds these as args to build like so: `-PnodeRepositoryUrl=https://nodeDownloadLocation -PnpmRepositoryUrl=https://npmDownloadLocation`
The defaults are added as the default args as per https://github.com/eirslett/frontend-maven-plugin
Enables build in more environments
Fix: # (issue)
No.
Tested build
> [MINOR] Update dashboard pom.xml to take arguments for node and npm download locations

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
Fix IllegalReferenceCountException issues when exceptions happened in clientReadHandler.readShuffleData().
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1522
No.
Existing UTs.
> [#1472][FOLLOWUP] fix(client): Fix IllegalReferenceCountException issues when exceptions happened in clientReadHandler.readShuffleData()

- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
Memory may leak in exceptional scenarios when flushing events
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1459
I found out that memory may leak in exceptional scenarios when flushing events.
Because the following code snippets have not been executed:
```
event.addCleanupCallback(
() -> {
this.clearInFlushBuffer(event.getEventId());
spBlocks.forEach(spb -> spb.getData().release());
}
);
```
and
```
event.addCleanupCallback(() -> releaseMemory(event.getSize(), true, false));
```
It can also lead to heap memory not being released, as `HybridStorageManager`.`eventOfUnderStorageManagers` will hold a large amount of unreleased heap memory. This is because the code `event.addCleanupCallback(() -> eventOfUnderStorageManagers.invalidate(event))` has not been executed. …
> [#1459][FOLLOWUP] fix(server): Memory may leak in exceptional scenarios when flushing events

- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBuffer.java
Only invoking LOG.debug when LOG.isDebugEnabled is true
For https://github.com/apache/incubator-uniffle/issues/1201
No.
Existing UTs.
> [MINOR] improvement(tez): Only invoking LOG.debug when LOG.isDebugEnabled is true

- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
NPE cound happen before uncompressing after #1360 
For https://github.com/apache/incubator-uniffle/issues/1546
No.
Existing UTs.
> [#1546] fix(spark): NPE could happen before uncompressing after #1360

- client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java
Explicitly uses partition id `0` or `1` where sensible. Also adds a test that writes and reads two partitions.
In `ShuffleReadClientImplTest`, partition id `0` is implicitly used though some tests use `HadoopShuffleWriteHandler` with partition id `1`, which is not realistic.
No.
Unit tests.
> [MINOR] test: Use sensible partition ids in ShuffleReadClientImplTest

- common/src/main/java/org/apache/uniffle/common/exception/FileNotFoundException.java
- common/src/main/java/org/apache/uniffle/common/exception/InvalidRequestException.java
- common/src/main/java/org/apache/uniffle/common/exception/NoBufferException.java
- common/src/main/java/org/apache/uniffle/common/exception/NoBufferForHugePartitionException.java
- common/src/main/java/org/apache/uniffle/common/exception/NoRegisterException.java
- common/src/main/java/org/apache/uniffle/common/exception/RssSendFailedException.java
- common/src/main/java/org/apache/uniffle/common/exception/RssWaitFailedException.java
Make custom exception classes in the `rss-common` module inherit from `RssException`.
For https://github.com/apache/incubator-uniffle/issues/1549
No.
Existing UTs.
> [#1549] fix(common): Uniformly throw RssException for external callers

- common/src/main/java/org/apache/uniffle/common/netty/protocol/SendShuffleDataRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Refresh `timestamp` when sending `SendShuffleDataRequest`.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1534
No.
Existing UTs.
> [#1472][part-6][FOLLOWUP] Fix Netty transport time when sending shuffle data requests

- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleServerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Override the `getClientInfo` method in `ShuffleServerGrpcNettyClient` and remove the unused `getDesc` method.
The code is cleaner, and the returned value of `getClientInfo` is more accurate.
No.
Existing UTs.
> [MINOR] improvement(client): Override getClientInfo method in ShuffleServerGrpcNettyClient and remove unused getDesc method

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriterBuffer.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Verify the number of written records to enhance data accuracy.
Make sure all data records are sent by clients.
Make sure bugs like https://github.com/apache/incubator-uniffle/pull/714 will never be introduced into the code.
A follow-up PR for https://github.com/apache/incubator-uniffle/pull/848.
No.
Existing UTs.
> [#808] improvement(spark): Verify the number of written records to enhance data correctness

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/WriteAndReadMetricsTest.java
Use a better computation logic for WriteAndReadMetricsTest without using reflection.
No need to use reflection, which will be quite confusing sometimes.
No.
Existing UTs.
> [MINOR] improvement(test): A better computation logic for WriteAndReadMetricsTest without using reflection

- rust/experimental/server/src/store/mem/ticket.rs
Use `i64` to fix overflow rather than `u64`
Fix: #1569. to fix `test_ticket_manager`
No.
Existing uts
> [#1569] fix(rust): flaky test for `test_ticket_manager`

- client-spark/spark2-shaded/pom.xml
- client-spark/spark2/src/main/java/org/apache/spark/network/util/NettyUtils.java
When we release the shaded client jar for Spark 2.x, the class `org.apache.spark.network.util.NettyUtils.class` should not be included in the package.
Fix https://github.com/apache/incubator-uniffle/issues/1567.
&
It's also a followup PR for https://github.com/apache/incubator-uniffle/pull/727.
When running in Spark 2.4, we will encounter exceptions as below:
```
24/03/07 16:34:37 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(tdwadmin); groups with view permissions: Set(); users  with modify permissions: Set(tdwadmin); groups with modify permissions: Set()
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.network.util.NettyUtils.createEventLoop(Lorg/apache/spark/network/util/IOMode;ILjava/lang/Stri …
```
> [#1567] fix(spark): Let Spark use its own NettyUtils

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/util/BlockIdLayout.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- docs/client_guide/spark_client_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RssShuffleManagerTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
The configuration of the block id layout for Spark2 and Spark3 can be simplified by only providing the maximal number of partitions. Increments `SHUFFLE_SERVER_VERSION` as the "new" Spark client requires to connect to a "new" shuffle server.
Currently, optimally configuring the block id layout for Spark is quite complex: https://github.com/apache/incubator-uniffle/pull/1528/files#diff-09ce7eaa98815d62ca00b2a8b0a45b0a922b047014c1f91dc17081b3fef8e7a8R106-R112
Three values have to be provided: the number of bits for sequence number, partition id and task attempt id. The task attempt id has to provide more bits than the partition id, in the sense that the maximal number of attempts can be stored. This requires to also account for speculative execution.
The RssShuffleManager can do the …
> [#731][FOLLOWUP] feat(Spark): Configure blockIdLayout for Spark based on max partitions

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Handle all the exceptions when spilling buffers.
Let users know when a TimeoutException occurs.
Fix https://github.com/apache/incubator-uniffle/issues/1572.
No.
Existing UTs.
> [#1572] fix(spark): Exceptions might be discarded when spilling buffers

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RssShuffleManagerTest.java
Fetches dynamic client config as early as possible, to be able to use dynamic client config to create the shuffle client with updated config.
Providing config or the shuffle client via coordinator is operationally useful as cluster-wide settings can be deployed through the cluster and changed over time. Clients and apps do not need to change configs.
Fixes Spark part of #1554
More configs can be provided via coordinators.
Existing and [follow-up](https://github.com/apache/incubator-uniffle/pull/1528/files#diff-ea644edb1c0bf0e80f9a960adbc1615c99cb6a3a0d5fe24f788307f1daf22f46R127-R131) unit tests.
> [#1554] feat(spark): Fetch dynamic client conf as early as possible

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
add client type when request shuffle assignment
Fix: (#1373)
No.
Not necessary.
> [#1373][followup] fix(client):Add client type when request shuffle assignment

- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
- server/src/main/java/org/apache/uniffle/server/ShuffleDataFlushEvent.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerOnKerberizedHadoopTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
In the implementation of the methods `flushBuffer`, `handleEventAndUpdateMetrics`, and `removeBufferByShuffleId`, read-write locks have been added to manage concurrency. This ensures that a `ShuffleBuffer` successfully converted into a `flushEvent` won't be cleaned up again by `removeBufferByShuffleId`, and a `ShuffleBuffer` already cleaned up by `removeBufferByShuffleId` won't be transformed back into a `flushEvent`. This effectively resolves the concurrency issue.
Fix https://github.com/apache/incubator-uniffle/issues/1571 & https://github.com/apache/incubator-uniffle/issues/1560 & https://github.com/apache/incubator-uniffle/issues/1542
The key logic of the PR is as follows:
Before this PR:
1. A `ShuffleBuffer` is turned into a `FlushEvent`, and **_its blocks and size are cleared_**
→ …
> [#1571] fix(server): Memory may leak when EventInvalidException occurs

- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- docs/server_guide.md
Provide the uniffle server deploy guide for those machines without hadoop env.
Leveraging from the #1379 and #1370 , we could setup uniffle shuffle-server without hadoop env.
This will simplify the quick start process.
Fix: #1576
No.
Existing tests
> [#1576] feat(doc): server deploy guide without hadoop-home env

- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
- pom.xml
Support Spark 3.5.1
The abstract class `TaskContext` introduced a new method `isFailed()` after Spark version 3.5.1. Due to this addition, it is not possible to compile the `MockTaskContext` class using Spark 3.5.1 without modifying the code. Consequently, we also added the `isFailed()` method to `MockTaskContext`. However, to maintain compatibility with versions of Spark prior to 3.5.1, we did not annotate this method with `@Override`.
Compiling old code with Spark 3.5.1 results in the following error: 
```error: MockTaskContext is not abstract and does not override abstract method isFailed() in TaskContext.```
Additionally, adding the `@Override` annotation leads to another error: 
```error: method does not override or implement a method from a supertype.```
Fix: #1591 
No.
Existing …
> [#1591] feat(spark): Support Spark 3.5.1

- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Calling `lock()` method outside try block to avoid unnecessary errors
In general, the `lock()` method should be placed outside the try block. The reason is that if the `lock()` method throws an exception, it indicates that the lock was not acquired, so there is no need to attempt to release it in the finally block. If the `lock()` method is placed within the try block and it throws an exception, the finally block will still be executed and attempt to release a lock that was never acquired, leading to errors.
No.
Existing UTs.
> [MINOR] refactor: Calling lock() method outside try block to avoid unnecessary errors

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
Release memory more accurately when failing to cache shuffle data.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1534.
No.
Existing UTs.
> [#1472][FOLLOWUP] improvement(server): Release memory more accurately when failing to cache shuffle data

- server/src/main/java/org/apache/uniffle/server/NettyDirectMemoryTracker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Fix the inaccurate `used_direct_memory_size` metric.
Also `used_direct_memory_size_by_netty` and `used_direct_memory_size_by_grpc_netty` metrics are added to provide more detailed indicators for locating and analyzing in production.
Fix https://github.com/apache/incubator-uniffle/issues/1598.
No.
Tested in our env.
> [#1598] fix(server) Fix inaccurate used_direct_memory_size metric

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
Fix task fail retry parameter not work and add task fail retry parameter in other locations
Fix: (#1373)
No.
Not necessary.
> [#1373][FOLLOWUP] fix(spark): shuffle manager rpc service invalid when partition data reassign is enabled

- client-spark/common/src/main/java/org/apache/spark/shuffle/ShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/ShuffleHandleInfoTest.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReassignFaultyShuffleServerRequest.java
- proto/src/main/proto/Rss.proto
1. Lock the `shuffleHandle` to ensure the thread safe when reassigning partial server for tasks
2. Only share the replacement servers for faulty servers in one stage rather than the whole app
3. Simplify the reassignment logic, like the single one replacement server which will be supported in the future, so let's remove it currently.
4. correct the `partitionIds` type from `string` to `int` in proto
Fix: #1608
In current implementation of partition reassignment, it will share the same reassignment servers for the different stages, which will crash for app without registry.
No.
UTs
> [#1608][part-1] fix(spark): Only share the replacement servers for faulty servers in one stage

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/AddBlockEvent.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/BlockFailureCallback.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/BlockSuccessCallback.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client/src/main/java/org/apache/uniffle/client/impl/FailedBlockSendTracker.java
- common/src/main/java/org/apache/uniffle/common/BlockCompletionCallback.java
- common/src/main/java/org/apache/uniffle/common/ShuffleBlockInfo.java
- common/src/main/java/org/apache/uniffle/common/exception/RssSendFailedException.java
- common/src/main/java/org/apache/uniffle/common/function/TupleConsumer.java
1. avoid releasing block previously when enable block resend
2. introduce the block max retry times
For: #1608
In the current codebase for partition reassignment, it has some bugs as follows
1. data has been released when resending.
2. if the blocks fail to resend, it may fast fail without retry again
No.
`RssShuffleWriterTest#blockFailureResendTest` is to test the resending block mechanism.
> [#1608][part-2] fix(spark): avoid releasing block in advance when enable block resend

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Fix: #1631 
No.
no test, obvious mistake
> [#1631] fix(server): ShuffleTaskInfo may leak when app is removed

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/storage/HybridStorageManager.java
Remove the meaningless eventOfUnderStorageManagers.
Fix https://github.com/apache/incubator-uniffle/issues/1626 & https://github.com/apache/incubator-uniffle/issues/1620.
It's also a follow-up PR for https://github.com/apache/incubator-uniffle/pull/383.
This cache only makes sense when the event retries after a failure. However, after the event fails, it is not appropriate to continue taking the original storageManager from the cache(because events usually fail due to high IO pressure or disk damage or disk full). In this case, the cache seems to be meaningless, so there is a contradiction here, we should remove it.
No.
Tested in our env.
> [#1626] fix(server): Remove the meaningless eventOfUnderStorageManagers cache

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
Print an error log when an event is dropped.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1461.
This way, it's easier to find error logs in the log, making it convenient for troubleshooting.
No.
Unnecessary.
> [#1459][FOLLOWUP] improvement(server): Print an error log when an event is dropped

- rust/experimental/server/src/store/mem/ticket.rs
Disable flaky test of test_ticket_manager
I haven't found the root cause of test flaky. so disable it until I fix this.
No.
needn't
> chore(rust): disable flaky test of test_ticket_manager

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Always executing the removeResources no matter whether blockIds remain.
Fix: #1634 
No.
Using existing unit tests, but additionally checking the app folder after app is expired.
> [#1634] fix(server): remove app folder if app is expired

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
Fix the issue of log variable printing.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1461.
No.
Unnecessary.
> [#1459][FOLLOWUP] fix(server): Fix the issue of log variable printing

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Add two metrics for each reading memory/index/local files:
1. Add a gauge metric for its threads number.
2. Add a gauge metric for its reading size.
Fix https://github.com/apache/incubator-uniffle/issues/1645.
No.
Existing UTs.
> [#1645] feat(server): Add gauge metrics for reading localfile data

- patch/spark/spark-3.2.1_dynamic_allocation_support.patch
- patch/spark/spark-3.3.1_dynamic_allocation_support.patch
- patch/spark/spark-3.4.1_dynamic_allocation_support.patch
Support dynamic allocation for Uniffle and Gluten when use spark3.2, spark3.3, spark3.4
ShuffleManager name in `https://github.com/apache/incubator-gluten/tree/main/gluten-uniffle` differs from `RssShuffleManager`
Fix: https://github.com/apache/incubator-uniffle/issues/1087
No.
manul integration test
> [#1087] feat(spark): Support dynamic allocation for Gluten Uniffle

- cli/pom.xml
- client-mr/core/pom.xml
- client-mr/hadoop2.8/pom.xml
- client-mr/hadoop3.2/pom.xml
- client-spark/common/pom.xml
- client-spark/spark2-shaded/pom.xml
- client-spark/spark2/pom.xml
- client-spark/spark3-shaded/pom.xml
- client-spark/spark3/pom.xml
- client-tez/pom.xml
- client/pom.xml
- common/pom.xml
- coordinator/pom.xml
- dashboard/pom.xml
- deploy/kubernetes/pom.xml
- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/spark2/pom.xml
- integration-test/spark3/pom.xml
- integration-test/tez/pom.xml
- internal-client/pom.xml
- pom.xml
- proto/pom.xml
- server/pom.xml
- storage/pom.xml
Bump version to `0.10.0-SNAPSHOT`.
sed -i "s%<version>0.9.0-SNAPSHOT</version>%<version>0.10.0-SNAPSHOT</version>%" $(grep -l "<groupId>org.apache.uniffle</groupId>" $(find . -name pom.xml))
Releasing 0.9.0 from `branch-0.9`.
Fix: #1655
No.
Not needed.
> [#1655] Bump version to 0.10.0-SNAPSHOT

- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBuffer.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferTest.java
The current implementation of the SortBufferIterator.getKey() and .getValue() methods in the SortWriteBuffer class assumes that keys and values are always stored within a single buffer. This assumption can lead to runtime exceptions, specifically ArrayIndexOutOfBoundsException, when keys or values span multiple WrappedBuffer instances.
In the current implementation, due to the execution of the `compact()`, the data of the key will not span buffers. However, the data of the value may be located on different buffers from the key and may span multiple buffers.
This PR update getKey() to use fetchDataFromBuffers() to retrieve the key data. And this PR update getValue() to first adjust the starting index and offset based on the length of the key and then use fetchDataFromBuffers() to retrieve …
> [#1341] fix(mr): Fix MR Combiner ArrayIndexOutOfBoundsException Bug.

- rust/experimental/server/src/store/localfile.rs
Disable the flaky test of local_store_test
I don't find out the flaky root cause for this test case, so disable it to avoid continous failure 
No.
Neen't
> [MINOR] chore(rust): disable flaky test of local_store_test

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Descrease the disk size  that calculated by local storage self on removing resources with AppPurgeEvent
Fix: #1678
No.
Unit tests
> [#1678] fix(server): disk size leak on removing resources by AppPurgeEvent

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/test/java/org/apache/uniffle/storage/common/LocalStorageTest.java
Use the disk size obtained from periodic check to determine whether the disk can be written.
The disk size obtained from metadata is unreliable.
Fix: #1684 
No.
Existing UTs
> [#1684] fix(server): use the diskSize obtained from periodic check to determine whether is writable

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/BlockIdManager.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/BlockIdSelfManagedShuffleWriteClient.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/RssShuffleClientFactory.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTest.java
- client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java
- docs/client_guide/spark_client_guide.md
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkIntegrationTestBase.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/ContinuousSelectPartitionStrategyTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetShuffleReportForMultiPartTest.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleManagerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleResultForMultiPartRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleResultRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleResultRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssGetShuffleResultResponse.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssReportShuffleResultResponse.java
- proto/src/main/proto/Rss.proto
Support report blockIds from shuffle-servers to spark driver optionally
Fix: #1538
Yes. `rss.client.blockId.selfManagedEnabled` is introduced, default value is false.
Integration tests.
> [#1538] feat(spark): report blockIds to spark driver optionally

- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
remoteShuffle -> removeShuffle
Fix spelling errors.
No.
Existing UTs.
> [MINOR] fix(typo): Correct the removeShuffle method name

- pom.xml
Bump Netty from 4.1.106.Final to 4.1.109.Final.
Fix: https://github.com/apache/incubator-uniffle/issues/1701.
No.
Existing UTs.
> [#1701] improvement(Netty): Bump Netty from 4.1.106.Final to 4.1.109.Final

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Verify the sent blocks count in write tasks for spark
For #1608.
After introducing the reassign menchanism, the blocks' stored location will be dynamiclly changed. 
To ensure possible or potenial bugs, it's necessary to introduce the block count.
No.
Existing tests are enough to ensure safe
> [#1608][part-6] improvement(spark): verify the sent blocks count

- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
Fix some flaky tests which may cause port conflicts sometimes.
Fix: https://github.com/apache/incubator-uniffle/issues/1675.
No.
Unnecessary.
> [#1675][FOLLOWUP] fix(test): Fix flaky tests which may cause port conflicts

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- docs/client_guide/spark_client_guide.md
- integration-test/spark3/src/test/java/org/apache/uniffle/test/PartitionBlockDataReassignBasicTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/PartitionBlockDataReassignMultiTimesTest.java
1. add docs about reassign mechanism
2. rename the config from "rss.client.blockSendFailureRetry.enabled" to "rss.client.reassign.enabled"
Fix: #1608
No.
Needn't
> [#1608][part-7] improvement(doc): add doc and optimize reassign config options

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/conf/AbstractRssClientConfApplyStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/conf/BypassRssClientConfApplyStrategy.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/conf/RssClientConfApplyManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/conf/RssClientConfFetchInfo.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/conf/RssClientConfApplyManagerTest.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssFetchClientConfRequest.java
- proto/src/main/proto/Rss.proto
Introduce pluggable ClientConfApplyManager for fetchClientConf rpc
For #1709 
Yes.
Unit tests
> [#1709] feat(coordinator): Introduce pluggable ClientConfApplyManager for fetchClientConf rpc

- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/BlockIdManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-tez/src/main/java/org/apache/tez/common/ShuffleAssignmentsInfoWritable.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- common/pom.xml
- coordinator/pom.xml
- coordinator/src/main/java/org/apache/uniffle/coordinator/AccessManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- pom.xml
- server/pom.xml
- server/src/main/java/org/apache/uniffle/server/HealthCheck.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java
Upgrade from commons-collections:commons-collections:3.2.2 to org.apache.commons:commons-collections:4.4.
Fix: https://github.com/apache/incubator-uniffle/issues/1699.
No.
Existing UTs.
> [#1699] improvement: Upgrade from commons-collections:commons-collections:3.2.2 to org.apache.commons:commons-collections:4.4

- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/main/java/org/apache/uniffle/common/netty/handle/TransportResponseHandler.java
- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Speed up ConcurrentHashMap#computeIfAbsent by checking key existence.
A followup pr for https://github.com/apache/incubator-uniffle/issues/519.
No.
Existing UTs.
> [#519][FOLLOWUP] Speed up ConcurrentHashMap#computeIfAbsent

- coordinator/src/main/java/org/apache/uniffle/coordinator/conf/YamlClientConfParser.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/conf/YamlClientConfParserTest.java
- coordinator/src/test/resources/dynamicClientConf.yaml
fix classCastExpection of boolean->String with yaml style remote client conf
Fix: #1721 
No.
Unit tests
> [#1721] fix(coordinator): classCastExpection of boolean->String with yaml style remote client conf

- README.md
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- docs/coordinator_guide.md
Update outdated config: rss.writer.send.check.timeout -> rss.client.send.check.timeout.ms.
The `rss.writer.send.check.timeout` configuration has been renamed to `rss.client.send.check.timeout.ms`, no longer in use.
No.
No need.
> [MINOR] fix(docs): Update outdated config: rss.writer.send.check.timeout -> rss.client.send.check.timeout.ms

- common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/test/java/org/apache/uniffle/common/ReconfigurableConfManagerTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Introduce the reconfigurable conf for server or other componts.
Fix: #1711
No.
Unit tests.
> [#1711] feat(server): Introduce the reconfigurable conf

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Introduce disks timeout metrics.
For https://github.com/apache/incubator-uniffle/issues/1728.
No.
> [#1728] feat(server): Introduce disks timeout metrics

- common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategyTest.java
- integration-test/common/pom.xml
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorAssignmentTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/DiskErrorToleranceTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RpcClientRetryTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/tez/pom.xml
- pom.xml
Fix various flaky tests:
1. After using `SimpleClusterManager`, release resources at once, which might cause tests to fail sometimes.
2. The compiler machine may not necessarily have a valid broadcast address (maybe in a pod created by K8S, and the broadcast address could be 0.0.0.0). Unit tests should running successfully on such machines. We need to support this scenario.
3. Refactor the `URI.create` logic in `SimpleClusterManagerTest` to support cross-platform operation, such as running tests on Windows.
4. Use `IntegrationTestBase#shutdownServers` to reduce duplicated codes.
For https://github.com/apache/incubator-uniffle/issues/1675.
No.
Unnecessary.
> [#1675][FOLLOWUP] fix(test): Fix various flaky tests

- dashboard/pom.xml
Upgrade the versions of NodeJS and npm.
The dashboard on MacOS does not support the M-chip of Node14, resulting in a local compilation failure, and you need to upgrade to Node16 or npm8 or later.
Fix: #1706 
No.
No testing required.
> [#1706] improvement: Upgrade the default NodeJS and npm versions of dashboard.

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Use warn log when unable to acquire memory.
No need to use error log, because clients will retry for many times.
No.
No need.
> [MINOR] fix(server): Use warn log when unable to acquire memory

- build_distribution.sh
- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/tez/pom.xml
- pom.xml
We adjust the memory arguments refer to Spark's [pom.xml](https://github.com/apache/spark/blob/master/pom.xml):
> -ea -Xmx4g -Xss4m -XX:MaxMetaspaceSize=2g -XX:ReservedCodeCacheSize=${CodeCacheSize} ${extraJavaTestArgs}
and [make-distribution.sh](https://github.com/apache/spark/blob/master/dev/make-distribution.sh):
> export MAVEN_OPTS="${MAVEN_OPTS:--Xss128m -Xmx4g -XX:ReservedCodeCacheSize=128m}"
This is more reasonable.
Fix: https://github.com/apache/incubator-uniffle/issues/1698.
After https://github.com/apache/incubator-uniffle/pull/1726, I found that the issue may still exist.
No.
Unnecessary.
> [#1698][FOLLOWUP] fix(test): Increase stability of tests

- coordinator/src/test/java/org/apache/uniffle/coordinator/ApplicationManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/access/AccessManagerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/checker/AccessCandidatesCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/checker/AccessClusterLoadCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/checker/AccessQuotaCheckerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/conf/DynamicClientConfServiceTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/assignment/BasicAssignmentStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/AppBalanceSelectStorageStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/web/UniffleJavaProcess.java
- integration-test/common/src/test/java/org/apache/uniffle/test/AccessCandidatesCheckerHadoopTest.java
Fix various flaky tests:
1. After using `ApplicationManager`, release resources at once, which will let `ScheduledExecutorService` work background to cause unexpected behaviors.
2. Release `DynamicClientConfService` after using it.
3. Release `SimpleClusterManager` everytime after using it. Since the execution order of JUnit test methods is random, unless we specifically set the execution order. So it is better not to initialize the `SimpleClusterManager` object globally.
4. Wait for a while to ensure the port is released in `UniffleJavaProcess`.
5. Always call `stopServer` after `new CoordinatorServer()` to shut down multiple `ExecutorService` from running in background, which could cause unexpected behaviors.
For https://github.com/apache/incubator-uniffle/issues/1675.
No.
Unnecessary.
> [#1675][FOLLOWUP] fix(test): Explicitly close resources to avoid unexcepted behaviors

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
1. When the spill ratio is `1.0` , the process of calculating target spill size will be ignored to avoid potential race condition that the `usedBytes` and `inSendBytes` are not thread safe. This could guarantee that the all data is flushed to the shuffle server at the end of task.
2. Adding the `bufferManager's` buffer remaining check
Due to the #1670 , the partial data held by the bufferManager will not be flushed to shuffle servers in some corner cases, 
this will make task fail fast rather than silently data loss that should thanks the #1558 
No.
> [#1755] fix(spark): Avoid task failure of inconsistent record number

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Add block number check on getting shuffle result 
Data validation, ensure data stable and correct
No.
> [#1757] feat(server): Add block number check on getting shuffle result

- common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/test/java/org/apache/uniffle/common/ReconfigurableConfManagerTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/access/checker/AccessClusterLoadChecker.java
- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorReconfigureNodeMaxTest.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
1. Make the health checker execution timeout reconfigurable
2. Introduce the `rssConf.getReconfigurableConf` to use the reconfigurable conf.
For #1711
No.
> [#1711] feat(server): Make the health checker execution timeout reconfigurable

- dashboard/src/main/webapp/src/utils/common.js
Display the registration time in 24-hour format.
The current displayed registration time follows the system time of the machine. If the system is set to a 12-hour format, then the page will display the time in a 12-hour format. If the system is set to a 24-hour format, then the page will display the time in a 24-hour format. It's not clear in the UI whether it's AM or PM when the Linux machine uses the 12-hour format.
No.
Existing UTs.
> [MINOR] fix(dashboard): Display the registration time in 24-hour format

- client-mr/core/pom.xml
- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
- client-tez/pom.xml
Add `commons-collections4` dependencies in shaded clients.
After https://github.com/apache/incubator-uniffle/pull/1700, in some old versions of Spark, the `commons-collections4` dependency could be missing. Add the potential missing dependency to improve robustness.
No.
Existing UTs. Tested in our env.
> [#1699][FOLLOWUP] fix(client): Add commons-collections4 dependencies in shaded clients

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Method `ThreadUtils.executeTasks` expects milliseconds, but seconds are given.
Requests are interrupted before the configured timeout passes.
Fix: #1764
Configured timeout is respected.
Manually tested.
> [#1764] fix(client): Fix timeout time unit for unregister requests

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleManagerClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleManagerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReassignOnBlockSendFailureRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssReassignServersResponse.java
- proto/src/main/proto/Rss.proto
1. Output more task level logs (like taskId, executorId and so on) in driver side
2. Fix typo of `ReassignServersResponse`
For better seeing the more contexts when reassign happens
No.
Needn't
> [#1608] improvement(spark3): Output more task level infos in driver side when reassigning on block sent failure

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
1. Rework the blockId number check in client side after all blocks are sent
The subtask of #1608
No.
> [#1608][part-6][FOLLOWUP] improvement(client): Check blockId num after blocks all sent

- bin/start-shuffle-server.sh
Increase the IHOP value to avoid frequent garbage collection.
For https://github.com/apache/incubator-uniffle/issues/1770.
No.
> [#1770] improvement(server): Increase the InitiatingHeapOccupancyPercent value of G1 option to avoid frequent garbage collection

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Output the reassign logs in client side
For #1608
No.
Needn't
> [#1608] improvement(spark3): Output the reassign logs in client side

- client-mr/core/pom.xml
- common/pom.xml
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- common/src/main/java/org/apache/uniffle/common/util/GrpcNettyUtils.java
- internal-client/pom.xml
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/GrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Introduce configs to reduce the chunkSize of the gRPC internal Netty's PooledByteBufAllocator to reduce memory usage on the client-side.
When enabling Netty, the changes for gRPC internal Netty's configs will be as follows:
`io.netty.allocator.pageSize`: 8192 -> 4096 (bytes)
`io.netty.allocator.maxOrder`: 11 -> 3
`io.netty.allocator.smallCacheSize`: 128 -> 1024
Note: `chunkSize` = `pageSize` * 2^`maxOrder`, 
Thus, the `io.netty.allocator.chunkSize`: 2MB -> 32KB
For https://github.com/apache/incubator-uniffle/issues/1773.
No. This PR will not change anything when using GRPC. It will only take effect when using GRPC_NETTY.
Adds configs: `rss.client.rpc.netty.pageSize`, `rss.client.rpc.netty.maxOrder`, `rss.client.rpc.netty.smallCacheSize`
> [#1773] improvement(client): Reduce chunkSize of gRPC Netty's PooledByteBufAllocator to reduce memory usage

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleDeleteHandler.java
Skip retries for absent HDFS app directory to speed up resource removal
For better performance.
Fix: #1784 
No.
Manual testing
> [#1784] improvement(server): Skip retries for absent HDFS app directory to speed up resource removal

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/BufferManagerOptions.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
reduce minor logs
a lot of minor rss logs are printed in spark executor.
No.
minor fix
> [MINOR] refactor: Reduce minor logs

- common/src/main/java/org/apache/uniffle/common/netty/client/TransportClientFactory.java
`TransportClientFactory` should check whether `handler` is `null` when creating client.
For: https://github.com/apache/incubator-uniffle/issues/1794.
No.
Existing UTs.
> [#1794] improvement(netty): TransportClientFactory should check whether handler is null when creating client

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskInfoTest.java
1、ShuffleTaskInfo add isHugePartition funtion used by hugePartitionTags
2、ShuffleBuffleManger# isHugePartition utilizes ShuffleTaskInfo#isHugePartition, it may be more efficient and faster.
Fix: #1807 
No.
add UT
> [#1807] improvement(server): Avoid repeating judgment of partition whether is huge

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/ReassignAndStageRetryTest.java
- server/src/test/java/org/apache/uniffle/server/MockedShuffleServerGrpcService.java
Ensure the compatiblity of reassign and stageRetry. 
To improve the job stability if having reassign and stage retry.
For #1608
No.
Unit tests
> [#1608] feat(spark3): Ensure the compatiblity of reassign and stageRetry

- .github/workflows/parallel.yml
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
- pom.xml
Support compiling Spark client against Scala 2.13 dependencies.
Starting with Spark 4, Scala 2.13 is required.
Fix: #1805
No.
CI
> [#1805][part-1] build: Support Scala 2.13

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTest.java
- common/src/main/java/org/apache/uniffle/common/config/ConfigOption.java
Introducing the independent fine grained switch for fetch/write failure on stage retry mechanism
1. The stage retry of write failure is supported recently, which is not stable. Independent switch will benifit users using the fetch failure stage retry which won't bring too much risk.
2. Leveraging the partition reassign mechanism, the importance of write failure stage retry is decreasing.
Yes. The detailed doc will be added in the next following stage retry improvement PRs.
> [#1787] feat(spark): Fine grained stage retry switch for fetch/write failure

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Add a missing bracket in log when getting shuffle index using Netty.
A better log format.
No.
No need.
> [MINOR] fix: Add a missing bracket in log when getting shuffle index using Netty

- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTask.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssOrderedGroupedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/input/RssUnorderedKVInput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutput.java
- common/src/main/java/org/apache/uniffle/common/netty/MessageEncoder.java
- common/src/main/java/org/apache/uniffle/common/netty/TransportFrameDecoder.java
- common/src/main/java/org/apache/uniffle/common/netty/client/TransportClientFactory.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/Message.java
- common/src/main/java/org/apache/uniffle/common/storage/StorageMedia.java
- common/src/main/java/org/apache/uniffle/common/storage/StorageStatus.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Replace assertions with exception-throwing codes to make them work in production.
For: https://github.com/apache/incubator-uniffle/issues/1668.
This will make the exception checks work and make the code more reliable.
No.
Existing UTs.
> [#1668] fix: Replace assertions with exception-throwing codes

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RepartitionWithHadoopHybridStorageRssTest.java
Correct rss storage basePath configuration
rss.storage.basePath should be configured as separated path list.
No.
Fixed test case
> [MINOR] fix(test): Use standard way to set storage basePath in `RepartitionWithHadoopHybridStorageRssTest`

- build_distribution.sh
Fix two compilation issues: 
1) Ineffectiveness of specifying multiple `--without` options.
2) Correct Hadoop profile not being used despite being specified, with default profile being used instead.
For: https://github.com/apache/incubator-uniffle/issues/1826.
No.
Existing UTs.
> [#1826] fix(build): Fix multiple '--without' options and correct Hadoop profile usage

- build_distribution.sh
Revert the incorrect shift shell statements deletion in https://github.com/apache/incubator-uniffle/pull/1827.
A follow-up PR for https://github.com/apache/incubator-uniffle/pull/1827.
No.
Existing UTs.
> [#1826][FOLLOWUP] fix(build): Revert incorrect shift statements deletion in build_distribution.sh

- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkIntegrationTestBase.java
Disable Spark UI for Spark integration tests.
Spark UI is not necessary for test cases.
No.
Existing UTs.
> [MINOR] improvement(test): Disable Spark UI for Spark integration tests

- dashboard/src/main/webapp/src/pages/serverstatus/ActiveNodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/DecommissionednodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/DecommissioningNodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/LostNodeList.vue
- dashboard/src/main/webapp/src/pages/serverstatus/UnhealthyNodeListPage.vue
The `RegistrationTime` in the dashboard shuffle-server page can make us confuse, I think it could be better to be  `HeartbeatTime`.
Make the displayed title more meaningful.
WebUI of dashboard
> [MINOR] fix(dashboard): Correct RegistrationTime to HeartbeatTime

- server/src/main/java/org/apache/uniffle/server/buffer/AbstractShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipListTest.java
Remove `capacity` and related codes within `AbstractShuffleBuffer`.
Fix: #1847.
No.
Existing UTs.
> [#1847] refactor: Remove capacity and related codes within AbstractShuffleBuffer

- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Display the human-readable time format in application page.
A long type timestamp really hard to get information from it.
Format the update time to human-readable.
> [MINOR] Improvement(dashboard): Support display human-readable time format for app page

- cli/src/main/java/org/apache/uniffle/cli/UniffleCLI.java
- common/src/main/java/org/apache/uniffle/common/Application.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/AppInfo.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/AppInfoVO.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Add Reg time to AppInfo and Application
Fix: #1860
`bin/uniffle  client-cli -app -host localhost -port 19998` and dashboard app page will display registrationTime of each application.
```Console
bin/uniffle  client-cli -app -host localhost -port 19998
host:localhost,port:19998
+--------------------------------------------------------------------------------------------------------------+
|                                             Uniffle Applications                                             |
+---------------------------------------+------+---------------------+---------------------+-------------------+
|             ApplicationId             | User |    Registration Time    | Last HeartBeatTime  | RemoteStoragePath |
+---------------------------------------+------+------------------ …
```
> [#1860] feat(CLI/Coordinator/Dashboard): Add Reg time to AppInfo and Application

- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
- dashboard/src/main/webapp/src/pages/ShuffleServerPage.vue
Remove the ugly underline on the shuffle server page.
Fix: #1401 
Yes.
No testing required.
> [#1401] improvement(dashboard): Remove the ugly underline in the shuffle server page

- bin/start-shuffle-server.sh
- common/src/main/java/org/apache/uniffle/common/AuditType.java
- conf/log4j2.xml
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
Add audit log support for write and delete operations.
Introduce a switch `rss.server.audit.log.enabled`, the default value is `false`.
For https://github.com/apache/incubator-uniffle/issues/1873.
No.
For write operations, the audit.log will be:
```
w|application_1716779728283_7775663_1720409662460|1|858_858|local|/data7/rssdata|56401402|2024-07-08 11:36:32|2024-07-08 11:36:32|85
w|application_1716779728283_7775663_1720409662460|1|860_860|local|/data13/rssdata|56365595|2024-07-08 11:36:32|2024-07-08 11:36:32|76
w|application_1703049085550_15349071_1720381124695|0|520_520|qy-xxx-30-v3|hdfs://qy-xxx-30-v3/rss/online|203300442|2024-07-08 03:41:11|2024-07-08 03:41:14|2543
```
For delete operations, the audit.log will be:
``` …
```
> [#1873] feat(server): Add audit log support for write and delete operations

- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- dashboard/src/main/webapp/src/pages/serverstatus/ActiveNodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/DecommissionednodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/DecommissioningNodeListPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/LostNodeList.vue
- dashboard/src/main/webapp/src/pages/serverstatus/UnhealthyNodeListPage.vue
Add reg time to ServerNode, and update method to update ServerNode when server heartbeat to coordinator rather than replace serverNode object.
Fix: #1471
User can get registrationTime from dashboard server page.
> [#1471] feat(server/dashboard): Add Reg time to ServerNode

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
Relocate all package name of client dependencies. Excepts for the following cases:
- Package belongs to uniffle
- Package provided by spark and hadoop env, something like
- spark
- hadoop
- dependencies belongs to the above, like lz4 belongs to spark.
- log4j related.
- part of javax package belongs to jdk
Fix: #1735
Before this change
After this change
No.
- Tested by a simple spark-shell which involved shuffle data writing and reading.
- Tested by a spark sql which product huge pressure of our uniffle cluster.
> [#1735] fix(client): Shade spark client grpc/jetty and others dependencies

- pom.xml
Change the default value of `rss.shade.packageName` from `org.apache.uniffle` to `org.apache.uniffle.shaded`.
Without this change, we cannot distinguish a class is relocated to  `org.apache.uniffle.xxx` or named `org.apache.uniffle.xxx` originally.
No.
Not needed.
> [MINOR] Improvement(client): Rename rss.shade.packageName from org.apache.uniffle to org.apache.uniffle.shaded

- dashboard/src/main/java/org/apache/uniffle/dashboard/web/JettyServerFront.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/proxy/WebProxyServlet.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/utils/DashboardUtils.java
I use rest api without given `targetAddress`, the NPE encountered.
```Console
➜  ~ curl 'http://localhost:19988/api/server/nodes?status=active'
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/server/nodes. Reason:
<pre>    java.lang.NullPointerException</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.24.v20180605</a><hr/>
</body>
</html>
```
Fix the NPE.
No.
```Console
curl 'http://localhost:19988/api/server/nodes?status=active'
```
> [MINOR] fix(dashboard): Fix NPE when targetAddress is null for /api/server/nodes

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Release `usedMemory` as soon as possible after the buffer is released.
For better performance.
Fix: #1885 
No.
Manual testing.
> [#1885] improvement(server): release usedMemory as soon as possible after buffer is released

- coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java
- dashboard/pom.xml
- dashboard/src/main/webapp/src/api/api.js
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
- dashboard/src/main/webapp/src/utils/http.js
Support deleting lost shuffle servers:
If some shuffle servers are lost, they need to go offline and the Coordinator has been in the lost state. 
Add the delete function to delete these servers in the memory.
Fix: #1401 
Yes.
Add UT.
> [#1401] feat:(dashboard): Support deleting lost shuffle servers

- dashboard/src/main/webapp/src/pages/ShuffleServerPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
1、To change the status label of the shuffle server, the number of servers must be updated simultaneously. Otherwise, the number in the status list may be inconsistent with that in the status statistics.
2、When removing lost servers, you should also update the number of lost servers.
Fix: #1401
Yes.
Deploy page Click Test.
> [#1401] improvement:(dashboard): The list of servers and the number of states are updated synchronously.

- bin/uniffle
Fix uniffle script cannot start issue, which is blocked by #1149
Cannot start uniffle script
No.
Executing `bin/uniffle` successfully.
> [#1149][FOLLOWUP] fix(coordinator): Fix coordinator startup issues

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Add partitionIds and shuffleId to `RequireBufferRequest`.
Without this changes, server cannot check limitHugePartition.
```java
public long requireBuffer(
String appId, int shuffleId, List<Integer> partitionIds, int requireSize) {
ShuffleTaskInfo shuffleTaskInfo = shuffleTaskInfos.get(appId);
if (null == shuffleTaskInfo) {
LOG.error("No such app is registered. appId: {}, shuffleId: {}", appId, shuffleId);
throw new NoRegisterException("No such app is registered. appId: " + appId);
}
for (int partitionId : partitionIds) {
long partitionUsedDataSize = getPartitionDataSize(appId, shuffleId, partitionId);
if (shuffleBufferManager.limitHugePartition(
appId, shuffleId, partitionId, partitionUsedDataSize)) {
String errorMessage =
String.format(
"Huge partition is limited to writing. appId: %s, …
```
> [MINOR] fix(client/netty): ShuffleServerGrpcNettyClient missing to send shuffleId and partitionIds for requirePreAllocation request

- conf/log4j2.xml
From the log4j document, we should not print out the method name into the log4j properties.
Fix: #1910
No.
Needn't
> [#1910] fix: Remove the method name from the log

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
We can start server and specific arguments System.properties
No.
Add jvm args `-Drss.dashboard.http.port=19987` to start dashboard process, we can see it take effect through the log.
```
[2024-07-15 21:56:55.942] [main] [INFO] AbstractConnector.doStart - Started ServerConnector@26be6ca7{HTTP/1.1,[http/1.1]}{0.0.0.0:19987}
```
> [MINOR] feat(common): Support set args from SystemProperties

- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Extract a method to release resources including Netty buffers and memory metrics when handling SendShuffleDataRequest.
Fix: #1917
No.
Tested on our test cluster
> [#1917] fix(server,netty): Fix memory leak issues when handling SendShuffleDataRequest

- .github/workflows/docker.yml
- common/src/main/java/org/apache/uniffle/common/merger/KeyValueIterator.java
- common/src/main/java/org/apache/uniffle/common/merger/MergeState.java
- common/src/main/java/org/apache/uniffle/common/merger/Merger.java
- common/src/main/java/org/apache/uniffle/common/merger/Recordable.java
- common/src/main/java/org/apache/uniffle/common/merger/Segment.java
- common/src/main/java/org/apache/uniffle/common/merger/StreamedSegment.java
- common/src/test/java/org/apache/uniffle/common/merger/MergerTest.java
- common/src/test/java/org/apache/uniffle/common/serializer/SerializerUtils.java
Introduce merger to merge multiple data streams according to key. Minimum heap K-way merge sorting is used to merge and sort the data streams that have been partially sorted.
Fix: #1747
No.
unit test and test in cluster.
> [#1747] feat(remote merge): Introduce common merger to merge multiple data streams.

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerOnRandomPortTest.java
Fix flaky test ShuffleServerOnRandomPortTest.
The random port may be 40000.
https://github.com/apache/incubator-uniffle/actions/runs/10087508746/job/27891800095?pr=1952
No.
CI
> [MINOR] fix(test): fix flaky test ShuffleServerOnRandomPortTest

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/main/java/org/apache/uniffle/common/web/resource/Authorization.java
- common/src/main/java/org/apache/uniffle/common/web/resource/AuthorizationRequestFilter.java
- common/src/test/java/org/apache/uniffle/common/metrics/TestUtils.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java
- docs/coordinator_guide.md
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
Support authentication for decommission interface.
For more safety.
Fix: #1947
Set `rss.rest.authorization.credentials` to a not empty string.
UT
> [#1947] feat(server): Support authentication for decommission interface

- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
Fix flaky test ServletTest.testUnhealthyNodesServlet.
In the original logic, `shuffleIds` will have three elements when only one unhealthy node is obtained for the first time.
https://github.com/apache/incubator-uniffle/actions/runs/10086923444/job/27890257649?pr=1948
No.
CI
> [MINOR] fix(test): fix flaky test ServletTest.testUnhealthyNodesServlet

- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Display app reg time in dashboard.
Fix typo error introduced by #1868 
User can see app reg time from dashboard.
Open a dashboard ui and submit an application and check the app reg time.
> [FOLLOWUP] [#1401] Fix(dashboard): Fix the display of app reg time on app page

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleHandle.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/SimpleShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/StageAttemptShuffleHandleInfo.java
- common/src/main/java/org/apache/uniffle/common/RemoteStorageInfo.java
- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
- storage/src/main/java/org/apache/uniffle/storage/common/FileBasedShuffleSegment.java
Add serialVersionUID to each class that implements Serializable, to avoid encountering the `local class incompatible` issue.
Not specifying serialVersionUID in Java can cause Incompatible Serialization, changes in class definition without updating serialVersionUID can lead to InvalidClassException. The automatically generated serialVersionUID may differ across different Java platforms, which can lead to problems during serialization and deserialization between different platforms. Besides, sometimes, compiler optimizations may change the generated serialVersionUID.
In a word, explicitly defining serialVersionUID ensures serialization compatibility and data integrity. This is a good practice.
Fix: #1961
No.
NO need
> [#1961] Fix(client/spark): Add serialVersionUID to each class that implements Serializable

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
Prevent file deletion hang in case of disk corruption.
Fix: #1956
Yes.
Unit tests
> [#1956] fix(server): Prevent file deletion hang in case of disk corruption

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
Avoid load missing key from system properties
Fix: Followup work of #1909
Without this PR, all jvm args will be displayed in dashboard, it can be noisy and useless.
No.
Tested locally.
added jvm args `-Dmissing.key=xxx -Drss.coordinator.app.expired=50000 -Drss.rpc.metrics.enabled=false`
then, check the result.
> [#1909] [FOLLOWUP] improve(common): Avoid load missing key from system properties

- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
Remove useless code from ServletTest.testRequestWithWrongCredentials.
The logic of sleep is useless. This is a mistake.
No.
CI
> [MINOR] fix(test): remove useless code from ServletTest.testRequestWithWrongCredentials

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Server send start time to coordinator through heartbeat.
Get each server start time to know well which server ever restarted.
User can the the server start time from rest api.
curl http://<COORDINATOR_HOST>: <COORDINATOR_JETTY_PORT>/api/server/nodes
> [MINOR] feat(server/coordinator): Heartbeat server startTimeMs to coordinator

- dashboard/src/main/webapp/package.json
- dashboard/src/main/webapp/src/mock/applicationpage.js
- dashboard/src/main/webapp/src/mock/coordinatorserverpage.js
- dashboard/src/main/webapp/src/mock/excludenodelist.js
- dashboard/src/main/webapp/src/mock/index.js
- dashboard/src/main/webapp/src/mock/layoutpage.js
- dashboard/src/main/webapp/src/mock/nodelistpage.js
- dashboard/src/main/webapp/src/mock/shuffleserverpage.js
- docs/dashboard_guide.md
When the Dashboard front-end development needs to show some effects, it is necessary to start the backend to provide the corresponding interface to see the effect. After the mock data is added, you can see the page effect by intercepting the network request and directly using the mock data of the front-end.
Fix: #1401 
Yes.
Develop UT.
>  [#1401] feat(dashboard): Add mock data to the Dashboard front end.

- dashboard/src/main/webapp/src/components/LayoutPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
This submission fixes these two problems:
1. When the browser refreshes the address bar directly, the server list is not displayed;
2. The menu item cannot be correctly selected;
Fix: #1985 
Yes.
Interface view.
>  [#1985] fix(dashboard):  Cannot display server info when refreshing the server page

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Fix typo of ShuffleManagerGrpcService#shuffleWrtieStatus
Fix typo.
No.
No need.
> [MINOR] fix(spark-common) Fix typo of ShuffleManagerGrpcService#shuffleWrtieStatus and ShuffleBufferWithXXX

- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
What changes were proposed in this pull request?
Display version and git commit id in dashboard
Why are the changes needed?
The version and git commit id can be used to easily locate whether the component has been upgraded and troubleshoot problems.
Does this PR introduce any user-facing change?
User can view version and git commit id from dashboard
How was this patch tested?
Use the latest version, open the dashboard ui, and you can see the version and git commit id on the Coordinator and Shuffle server pages.
Submit a task, and you can see the version and git commit id of each application task in the Apps module on the Application page. 
Issue: #1977 
Prev PR: #1964
> [#1977][FOLLOWUP] fix(coordinator): When resolving merge conflicts, some changes were reverted

- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
Display start time of servers within server page of dashboard.
Just show the start time. Let users know when the server has been restarted.
Display start time of servers within server page of dashboard.
> [#1975][FOLLOWUP] feat(dashboard): Support displaying the start time of server in dashboard

- bin/start-dashboard.sh
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/Dashboard.java
- dev/intellij/runConfigurations/Dashboard.run.xml
Rename the dashboard entry from `JettyServerFront` to `Dashboard`.
The name `JettyServerFront` is too generic. Renaming it to `Dashboard` could improve clarity and understanding.
No.
Start dashboard process nornally.
> [MINOR] improvement(dashboard): Rename JettyServerFront to Dashboard

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/Dashboard.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
Display the version and commitId for each process.
- I don't know clearly about the version of uniffle client current running within spark from spark.log, we cost much time to check the version and related code.
- After our colleague send us a log file, we don't know the version and related code, we have to ask him and wait reply.
It is easy to print the version to each process, and make it convenient for troubleshooting.
User can know the version of uniffle client from spark log
Run each Process and find the version output.
```
[2024-08-03 10:00:53.377] [main] [INFO] CoordinatorServer - CoordinatorServer version: 0.10.0-SNAPSHOT-4473d13d
[2024-08-03 10:26:25.865] [main] [INFO] ShuffleServer - ShuffleServer version: 0.10.0-SNAPSHOT-4473d13d
[2024-08-03 10:27:20.404] [main] [INFO] …
```
> [MINOR] feat(client-spark/coordinator/sever/dashboard):Show version and commit id for each Process for easy troubleshooting

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
Fix the RssShuffleManager to use the correct config.
Fix bug.
No.
No need.
> [MINOR] fix(client-spark): Fix to use correct options for enable rssStageRetry

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/audit/CoordinatorRPCAuditContext.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/audit/ServerRPCAuditContext.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Add return value for server rpc audit log
With the return value, we can know clear about the effect of the rpc call.
E.g. A bundle of `requireBuffer` calls appear in the rpc audit log, then followed some `sendShuffleData` rpc call with `requireBufferId`, but we don't know which `requireBuffer` call match the sendShuffleData call.
With this PR, we record the requireBufferId also which generated by `requireBuffer` call, and search the sendShuffleData call with the `requireBufferId`, this can be possible.
No.
Test Locally.
> [MINOR] improve(server): Add return value to server rpc audit log

- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java
- dashboard/src/main/webapp/src/mock/applicationpage.js
- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Display the total number of applications in the dashboard and update the original `total app num` to `current app num`.
We want to view the number of running and completed applications from the beginning until now.
- Display the total number of applications in the dashboard
- Update the original `total app num` to `current app num`
Start the cluster, run a Spark application, and check the dashboard.
> [MINOR] feat(dashboard/coordinator): Display total app num in dashboard

- client-mr/core/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/EventFetcherTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java
- client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTask.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedKVOutput.java
- client-tez/src/main/java/org/apache/tez/runtime/library/output/RssUnorderedPartitionedKVOutput.java
- client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/impl/RssSorterTest.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorterTest.java
- client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java
- client/src/test/java/org/apache/uniffle/client/ClientUtilsTest.java
- common/src/main/java/org/apache/uniffle/common/util/BlockId.java
- integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountWithFailuresTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/BufferTestBase.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleReadHandlerTest.java
Before this PR, in MR and TEZ engine:
1. attemptId is in sequenceNo of BlockId instead of taskAttemptId.
2. attempId is fixed 6 bit.
After this PR:
1. attemptId is in taskAttemptId. This is more reasonable.
2. attempId is calculated from max num of allowed failures and whether speculative execution is enabled.
Fix: #1398
No.
Existing UT and integrated tests.
> [#1398] fix(mr)(tez): Make attempId computable and move it to taskAttemptId in BlockId layout. (#1418)

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Add partitionIds and shuffleId to `RequireBufferRequest`.
Without this changes, server cannot check limitHugePartition.
```java
public long requireBuffer(
String appId, int shuffleId, List<Integer> partitionIds, int requireSize) {
ShuffleTaskInfo shuffleTaskInfo = shuffleTaskInfos.get(appId);
if (null == shuffleTaskInfo) {
LOG.error("No such app is registered. appId: {}, shuffleId: {}", appId, shuffleId);
throw new NoRegisterException("No such app is registered. appId: " + appId);
}
for (int partitionId : partitionIds) {
long partitionUsedDataSize = getPartitionDataSize(appId, shuffleId, partitionId);
if (shuffleBufferManager.limitHugePartition(
appId, shuffleId, partitionId, partitionUsedDataSize)) {
String errorMessage =
String.format(
"Huge partition is limited to writing. appId: %s, …
```
> [MINOR] fix(client/netty): ShuffleServerGrpcNettyClient missing to send shuffleId and partitionIds for requirePreAllocation request (#1913)

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
Upgrade from commons-collections:commons-collections:3.x to org.apache.commons:commons-collections:4.x
Fix: #1699
No.
Existing UTs.
> [#1699][FOLLOWUP] fix(client): Using collection4 instead of collection3

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java
- dashboard/src/main/webapp/src/pages/CoordinatorServerPage.vue
Add start time of coordinator in dashboard
Without this PR, I don't know whether the coordinator has been restarted.
Add start time of coordinator in dashboard
> [MINOR] feat(coordinator/dashboard): Show start time of CoordinatorServer to dashboard

- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleSchedulerTest.java
In fact, we use allEventsReceived to determine whether all upstream tasks are completed, but allEventsReceived may be abnormal due to multiple events occurring in multiple attempts for the same task. So we need to count the number of tasks, do not count the duplicate task attempts.
Fix: #1987
No.
test in cluster
> [#1987] fix(tez): Application may get stuck when exception occurs.

- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/reader/AbstractRssReaderTest.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/reader/RssShuffleDataIteratorTest.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcher.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssTezShuffleDataFetcher.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java
- common/src/main/java/org/apache/uniffle/common/compression/Codec.java
- common/src/main/java/org/apache/uniffle/common/util/ByteBufferUtils.java
- common/src/test/java/org/apache/uniffle/common/compression/CompressionTest.java
add a NONE type to compression.codec
Allow disabling rss client compression when spark.shuffle.compress is enabled
Fix: #2056
yes. add a none compression type
existing unit tests
> [#2056] feat(common): add a NONE type to compression.codec

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
- dev/scripts/checkshade.sh
Add a check after build spark shaded plugin, to check whether there are new coming unshaded content.
Without this, we cannot prevent to merge some PR which will break the shade client.
No.
CI Tests.
> [MINOR] chore(ci): Add a shade check step after build spark shade jar

- common/src/test/java/org/apache/uniffle/common/port/PortRegistry.java
- common/src/test/java/org/apache/uniffle/common/web/JettyServerTest.java
Introduce PortRegistry and applied to JettyServerTest
Fix: #2068
No.
Existing UTs.
> [#2068] Introduce PortRegistry and applied to JettyServerTest

- common/src/test/java/org/apache/uniffle/common/log/TestLoggerExtension.java
- common/src/test/java/org/apache/uniffle/common/log/TestLoggerParamResolver.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/HybridStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/main/java/org/apache/uniffle/server/storage/StorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Fix clear leak shuffle data accidentally remove data of new coming appId issue
Fix: #1972
No.
No need.
> [#1972] fix(server): Fix clear leak shuffle data accidentally remove data of new coming appId issue

- common/src/main/java/org/apache/uniffle/common/compression/NoOpCodec.java
- common/src/test/java/org/apache/uniffle/common/compression/CompressionTest.java
Corrected buffer offsets in NoOpCodec.decompress
Make NoOpCodec.decompress logic consistent with other codecs.
Fix: # (issue)
No.
added unit tests
> [#2072] improvement: Corrected buffer offsets in NoOpCodec.decompress

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/impl/FailedBlockSendTracker.java
- client/src/test/java/org/apache/uniffle/client/impl/FailedBlockSendTrackerTest.java
Replace LinkedList with CopyOnWriteArrayList to store the sending status
Fix: #2090
No.
CI
> [#2090] fix(client): use thread-safe list to store the sending status

- .gitignore
- deploy/kubernetes/operator/pkg/webhook/config/config.go
- deploy/kubernetes/operator/pkg/webhook/manager.go
- deploy/kubernetes/operator/pkg/webhook/manager_test.go
In this PR, we set a flag to open or close leader election of webhook of rss-operator.
We set the default value to false because leader election is only involved when synchronizing configuration objects used by webhook. Even if leader election is disabled, there will be no conflicts because the configuration objects rarely change. We plan to consider removing leader election completely in the future.
Fix: #2087 
No.
Added ut or Manually verified.
> [#2087] feat(operator): support closing leader election of webhook of rss-operator

- common/src/main/java/org/apache/uniffle/common/util/GrpcNettyUtils.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/GrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Use a static allocator for GrpcClient
Fix: #2096
No.
Tested in real cluster.
> [#2096] fix(client): Share Netty's memory allocators in gRPC

- integration-test/common/src/test/java/org/apache/uniffle/test/RpcClientRetryTest.java
In unit tests for RpcClientRetryTest, compiling a long null pointer error.
Fix: #2101 
No.
UT.
> [Bug] Fixed the UT null pointer of RpcClientRetryTest.

- common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java
When flush block and getInMemoryShuffleData occur together, may cause data reading errors. Because there may be two threads reading data at the same time, and the readIndex of ByteBuf will be inconsistent. So we should use duplicated when read bytes from ByteBuf.
Fix: #2103 
No.
unit test.
> [#2103] fix(server): Potential bytebuf offset race condition when flushing and getting data

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
As title.
Fix: #2065
No.
Existing UTs.
> [#2065] Fix QuorumTest to use random port

- common/src/main/java/org/apache/uniffle/common/web/JettyServer.java
- common/src/test/java/org/apache/uniffle/common/web/JettyServerTest.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
Display the port while in use
Help to find the in use port and its process.
```
16:29:02.179 [main] ERROR org.apache.uniffle.common.web.JettyServer - Terminating with exit status 1: Fail to start jetty http server, port is 9528
java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_251]
at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_251]
at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_251]
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_251]
```
UTs.
> [MINOR] improve(common/server/coordinator): Display the port in use port

- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
Enable BLOCK_SIZE_METRIC config.
Enable block size metrics collect for `blockSizeMetricsTest`
No.
UT `blockSizeMetricsTest`
> [MINOR] fix(test): Enable BLOCK_SIZE_METRIC to enable blockSizeMetricsTest

- dashboard/src/main/webapp/src/mock/nodelistpage.js
- dashboard/src/main/webapp/src/mock/shuffleserverpage.js
- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
Enlarge the app table and server table height in the application page
The existing height is too too small that we can only view 2 application info.
No.
Tested local.
> [MINOR] Enlarge the app/server table height in the application page

- common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
- common/src/test/java/org/apache/uniffle/common/ReconfigurableConfManagerTest.java
Support Update the RssConf while reload config from config file
Fix: #2120
User can get the reconfigured value from dashboard.
Tested by dashboard conf button.
```
rss.server.huge-partition.size.hard.limit 700000
-->
rss.server.huge-partition.size.hard.limit 800000
-->
rss.server.huge-partition.size.hard.limit 900000
-->
```
> [#2120] Support Update the RssConf while reload config from config file

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
Do not relocate javax to avoid NoClassDefFoundError issue.
Fix: #2030
No.
Thanks for the verify check by @zhengchenyu . This is not reproduced on my env.
> [#2030] fix(client-spark): Remove javax and logging from relocation list to solve NoClassDefFoundError

- server/src/main/java/org/apache/uniffle/server/HugePartitionUtils.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/AbstractShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
fix potential huge partition limit invalid when flushing is slow
Fix: #2130
No.
Unit tests
> [#2130] fix(server): Potential huge partition limit invalid when flushing is slow

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
Do not include the lo4j dependencies to the shaded uber jar.
The log4j related dependencies should be provided by spark environment. Without this PR, the classes included to the shaded jar which is not expected.
And the check shaded script found this issue.
```
[exec] checkShaded:/home/runner/work/incubator-uniffle/incubator-uniffle/client-spark/spark3-shaded/target/rss-client-spark3-shaded-0.10.0-SNAPSHOT.jar
[exec] unshaded count: 11
[exec] unshaded content:
[exec] org/apache/logging/slf4j/Log4jEventBuilder.class
[exec] org/apache/logging/slf4j/Log4jLogger.class
[exec] org/apache/logging/slf4j/Log4jLoggerFactory.class
[exec] org/apache/logging/slf4j/Log4jMDCAdapter$1.class
[exec] org/apache/logging/slf4j/Log4jMDCAdapter$ThreadLocalMapOfStacks.class
[exec] …
```
> [#2030][FOLLOWUP] Exclude log4j dependencies from shaded plugin

- coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java
Change to get coordinator appCurrent value from metrics
Keep consistent with `appTotality`, and in case of incorrect result returned from `getAppIds`.
No.
No need.
> [MINOR] fix: Change to get coordinator appCurrent value from metrics

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Release duplicate block.  #2016 solve this problem in client side. I think sendShuffeData may be retried, duplicated block still be reproduce.
Fix: #2105
No.
test in cluster.
> [#2105] fix(server): Fix memory leak caused by duplicate blocks when using ShuffleBufferWithSkipList.

- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Clear metrics in case of other test update the metrics value.
Fix the flaky test.
```
Error:  Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.046 s <<< FAILURE! - in org.apache.uniffle.server.ShuffleServerMetricsTest
Error:  testStorageCounter  Time elapsed: 0.008 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1.0> but was: <3.0>
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:86)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:81)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1010)
at org.apache.uniffle.server.ShuffleServerMetricsTest.testStorageCount …
```
> [MINOR] test: Fix flaky test about ShuffleServerMetricsTest#testStorageCounter

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
Reduce the empty size server in the reassignResult.
Reduce the log size.
Without this PR, the size of driver log is huge. There are large size log content like this.
```
{
192.168.1.100-19977-17000={818=[], 819=[], 803=[], 968=[], 857=[], 906=[], 826=[], 939=[], 956=[], 845=[]}, 
192.168.1.101-19977-17000={193=[], 65=[], 3=[], 68=[], 134=[], 135=[], 139=[], 76=[], 12=[], 78=[], 17=[], 82=[], 19=[], 151=[], 91=[], 29=[], 94=[], 160=[], 33=[], 167=[], 168=[], 173=[], 177=[], 178=[], 115=[], 183=[], 58=[]}, 
192.168.1.102-19977-17000={288=[], 294=[], 262=[], 361=[], 267=[], 332=[], 333=[], 238=[], 270=[], 207=[], 336=[], 241=[], 372=[], 278=[], 280=[], 282=[], 380=[], 221=[], 349=[], 318=[]}, 
192.168.1.103-19977-17000={1187=[], 1096=[], 1097=[], 1130=[], 1003=[], 1197=[], 1006=[], 1199=[], …
```
> [MINOR] improve(client): Reduce reassignResult log size within driver

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MultiReplicaClientReadHandler.java
fix log content of MultiReplicaClientReadHandler#readShuffleData to different content for last server and others.
The existing log can make user stress, as we have multi replica or servers to handle shuffle data read, so we should warn to user until we cannot get all blocks from last server.
Yes, the read task log will be more friendly.
Test locally.
> [MINOR] fix: fix log content of MultiReplicaClientReadHandler#readShuffleData

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
- server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java
Fixed block duplication bug.
Fix: #2119 
No.
Existing UT.
> [#2119] fix(server): Duplicate blockId causes shuffle Server network to be full.

- common/src/main/java/org/apache/uniffle/common/metrics/MetricsManager.java
- common/src/main/java/org/apache/uniffle/common/metrics/SupplierGauge.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Introduce block count in buffer pool metrics.
Fix: #2117
Yes. `block_count_in_buffer_pool` metrics introduced.
- "block_count_in_buffer_pool"
- "buffer_count_in_buffer_pool"
- "shuffle_count_in_buffer_pool"
By dashboard server metrics popup page.
> [#2117] feat(server): Introduce bufferPool related metrics(block/buffer/shuffle count)

- integration-test/common/src/test/java/org/apache/uniffle/test/AccessClusterTest.java
Disable AccessClusterTest until solve this flaky test
This test is failed recently, and can not find the reason.
No.
UT
> [#2157] test: Disable AccessClusterTest until solve this flaky test

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipListTest.java
Fix memory leak issue after the data structure of `blocks` changed from `list` to `set`.
Fix: #2105
No.
No need.
> [FOLLOWUP][#2105] Fix memory leak caused by duplicate blocks when using ShuffleBufferWithLinkedList

- common/src/main/java/org/apache/uniffle/common/PartitionInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Log more before server remove resource
Clearly and easily to view the job partitons blocks info, help to find the biggest partition.
No.
```
[2024-09-20 23:31:36.211] [clearResourceThread] [INFO] ShuffleTaskManager - Remove app info: appId: app-20240920233127-0046_1726846285810 shuffleId: 0 contains partition/block: 3/19
The maxSizePartitionInfo: [id=1, shuffleId=0, size=624, blockCount=16]
```
```
[2024-09-21 11:06:40.011] [clearResourceThread] [INFO] ShuffleTaskManager - Remove app info: appId: application_1703049085550_21177982_1726887839406 
shuffleId: 0 contains partition/block: 1/193
shuffleId: 2 contains partition/block: 1/4
The …
```
> [MINOR] improve(server): Log more before server remove resource

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Correct the warning log.
The shuffle data could be exist in the buffer pool and have not flush to local disk yet, so the log is not correct.
Fix: # (issue)
No.
No need.
> [MINOR] fix(server): Correct warning log for missing index when getLocalShuffleIndex

- client-mr/core/pom.xml
- client-mr/core/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBuffer.java
- client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/MRMetricsReporter.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RMRssShuffle.java
- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
- client-mr/core/src/main/java/org/apache/uniffle/client/shuffle/MRCombiner.java
- client-mr/core/src/main/java/org/apache/uniffle/client/shuffle/RecordCollector.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/RMRssShuffleTest.java
- client-mr/core/src/test/java/org/apache/uniffle/client/shuffle/MRCombinerTest.java
- client-mr/core/src/test/java/org/apache/uniffle/client/shuffle/RecordCollectorTest.java
- client/src/main/java/org/apache/uniffle/client/util/RssClientConfig.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/MRIntegrationTestBase.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/RMWordCountTest.java
MapReduce support remote merge.
Fix: #1750 
Yes, I will refine documentation in other PR.
unit test, integration test, real job in cluster.
> [#1750] feat(remote merge): Support MapReduce.

- common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
- common/src/main/java/org/apache/uniffle/common/ReconfigurableRegistry.java
- common/src/main/java/org/apache/uniffle/common/config/RssConf.java
- common/src/test/java/org/apache/uniffle/common/ReconfigurableRegistryTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
Introduce the ReconfigRegistry and ReconfigureListener to support update the changed config value dynamically.
Fix: #2158
No.
new UT.
> [#2158] feat(common): Introduce reconfigure listener

- common/src/main/java/org/apache/uniffle/common/executor/MeasurableRejectedExecutionHandler.java
- common/src/main/java/org/apache/uniffle/common/executor/ThreadPoolManager.java
- common/src/main/java/org/apache/uniffle/common/metrics/CommonMetrics.java
- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
- common/src/test/java/org/apache/uniffle/common/executor/ThreadPoolManagerTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorMetrics.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/metric/CoordinatorMetricsTest.java
- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Introduce ThreadPoolManager support metrics
Fix: #2125
Add batch of metrics related to the registered thread pool.
Open the dashboard server metrics page.
> [#2125] feat(common): Introduce ThreadPoolManager support metrics

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerGrpcMetricsTest.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Record more grpc process time and total metrics
Especially, the reportShuffleResult and getShuffleResultForMultiPart would be the most cost time call, this PR could measure  the performance of these methods.
Introduced new metrics.
- grpc_get_shuffle_result_for_multi_part_process_latency
- grpc_report_shuffle_result_process_latency
- grpc_get_shuffle_result_for_multi_part_total
Locally.
> [MINOR] improvement(server): Record more grpc process time and total metrics

- common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
- common/src/main/java/org/apache/uniffle/common/ReconfigurableRegistry.java
- common/src/main/java/org/apache/uniffle/common/web/resource/ConfOpsResource.java
- common/src/main/java/org/apache/uniffle/common/web/resource/ConfVO.java
- common/src/test/java/org/apache/uniffle/common/ReconfigurableRegistryTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
- Refactor `ReconfigurableRegistry#update` to only notify the key of changed properties.
- Support update multiply keys within a single rest request.
- Support notify the listener by  rest api `/confOps/update`.
Fix: #2158
Support rest api trigger update to reconfig listener
- curl command line
```Console
➜  ~ curl -X POST http://localhost:19978/api/shuffleServer/confOps/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.rpc.audit.log.enabled": "true", "rss.server.rpc.audit.log.excludeList": ""}}'
temporarily effective until restart: Update successfully%
```
- server.log
```
[2024-10-12 09:37:59.480] [Jetty-17] [INFO] ConfOpsResource - Dynamic updating ConfVO{update={rss.server.rpc.audit.log.enabled=true, rss.server.rpc.audit.log.excludeList=}, delete=[]}
```
> [#2158][FOLLOWUP] improvement(server/coordinator): Support notify reconfig listeners from rest api

- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
Do not select storage when there is only one storage, this can reduce the memory cost of `LocalStorageManager#sortedPartitionsOfStorageMap`.
Perf for single Local storage
No.
No need.
> [MINOR] improvement(server): Perf for single Local storage

- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Introduce in flush block count metrics in buffer pool
Insight all blocks in server include buffer pool and in flush blocks.
- New metrics named `in_flush_block_count_in_buffer_pool`
Test locally.
> [MINOR] feat(server): Introduce in flush block count metrics in buffer pool

- server/src/main/java/org/apache/uniffle/server/ShuffleDataFlushEvent.java
- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
- server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/api/ShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandler.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandlerTest.java
Avoid copy while toFlushEvent invoked
Avoid copy blocks from a  Collection to another Collection.
No.
Existing UTs
> [MINOR] improvement(server): Avoid copy while toFlushEvent invoked

- common/src/main/java/org/apache/uniffle/common/executor/ThreadPoolManager.java
- common/src/main/java/org/apache/uniffle/common/metrics/CommonMetrics.java
- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
- common/src/test/java/org/apache/uniffle/common/executor/ThreadPoolManagerTest.java
- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
Support dynamic update ThreadPool
Fix: #2169
Change update conf rest api to support update multiply keys one time.
- curl command line
```
➜  ~ curl -X POST http://localhost:19978/api/shuffleServer/confOps/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.flush.localfile.threadPool.size": "122", "rss.server.flush.thread.alive": "112"}}'
temporarily effective until restart: Update successfully%                                                                                                                                                                                          ➜  ~ curl -X POST http://localhost:19978/api/shuffleServer/confOps/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.flush.localfile.threadPool.size": "122", …
```
> [#2169] feat(server)(coordinator): Support dynamic thread number update about ThreadPool

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- internal-client/src/main/java/org/apache/uniffle/client/api/CoordinatorClient.java
- internal-client/src/main/java/org/apache/uniffle/client/factory/CoordinatorClientFactory.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcRetryableClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssAccessClusterRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleAssignmentsRequest.java
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
Modify RssShuffleManagerBase, let getShuffleAssignments and registerShuffleServers in one retry, and fix some code style problem
RssShuffleManagerBase.requestShuffleAssignment 's logic has been changed in #2095 
Fix: #2153
No.
Uts
> [#2153] fix(client): Fix requestShuffleAssignment in RssShuffleManagerBase

- common/src/main/java/org/apache/uniffle/common/PartitionInfo.java
- common/src/main/java/org/apache/uniffle/common/util/ByteUnit.java
- common/src/main/java/org/apache/uniffle/common/util/Constants.java
- common/src/main/java/org/apache/uniffle/common/util/UnitConverter.java
- common/src/test/java/org/apache/uniffle/common/util/UnitConverterTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleDetailInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Output the shuffle data size and block count before purge app
Clearly and easily to view the shuffle blocks info.
No.
Run locally.
```
[2024-10-15 11:25:31.438] [clearResourceThread] [INFO] ShuffleTaskManager - Removing app summary info: appId: app-20241015112429-0069_1728962668484
The app task info: ShuffleTaskInfo{appId='app-20241015112429-0069_1728962668484', totalDataSize=741B, inMemoryDataSize=0B, onLocalFileDataSize=741B, onHadoopDataSize=0B, maxSizePartitionInfo=[id=1, shuffleId=0, size=663B, blockCount=17], shuffleDetailInfo={0=ShuffleDetail [id=0, dataSize=741B, blockCount=19, startTime=2024-10-15 11:24:36]}}
```
> [#2133][FOLLOWUP] improvement(server): Support output the shuffle data size and block count before purge app

- common/src/main/java/org/apache/uniffle/common/ShuffleIndexResult.java
- Pass the flaky test
- Avoid memory leak after double release the `ShuffleIndexResult`
Fix: #1628
No.
Flaky test can be fixed.
> [#1628] test(client): Fix double release ShuffleIndexResult cause exception to pass flaky test 

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java
Support config grpc thread pool waiting queue size
Without this, the server could be rush full of rpc call and cost all memory.
No.
Existing UTs.
> [MINOR] improvement(server,coordinator): Support config grpc queue size

- integration-test/mr/src/test/java/org/apache/uniffle/test/DynamicConfTest.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/HadoopConfTest.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/LargeSorterTest.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/MRIntegrationTestBase.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/RMWordCountTest.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/SecondarySortTest.java
- integration-test/mr/src/test/java/org/apache/uniffle/test/WordCountTest.java
Support Netty for MR integration test.
Fix: #2015
No.
Integration tests themselves.
> [#2015] improvement(netty): Support Netty for MR integration test.

- common/src/main/java/org/apache/uniffle/common/netty/protocol/SendShuffleDataRequest.java
Fix shuffle server memory leaks when reaching memory limit.
When enabling Netty, on the shuffle server side, Netty will allocate memory for SEND_SHUFFLE_DATA_REQUEST request. However, when the memory limit is reached, an `OutOfDirectMemoryError` will be thrown and the decoding process for this message will fail. This will cause the bytebuf allocated successfully in the previous batch in this message to not be released, resulting in memory leaks.
Fix: https://github.com/apache/incubator-uniffle/issues/2060
No.
Existing UTs
> [#2060] fix(server): Fix memory leaks when reaching memory limit

- dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Display version and gitCommitId in one column
Fix: #2205 
Yes.
Locally
> [#2205] feature(dashboard) Display version and gitCommitId in one column

- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java
Add the write information of appinfo in Shuflle Server heartbeat
Fix: #2207 
No.
Locally
> [#2207] feat(dashboard): Add the write information of appinfo in Shuflle Server heartbeat

- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
- client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java
- client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java
- client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java
- client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/test/java/org/apache/uniffle/client/record/reader/MockedShuffleWriteClient.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTestWhenShuffleFlushed.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssRegisterShuffleRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/merge/ShuffleMergeManager.java
- server/src/test/java/org/apache/uniffle/server/merge/ShuffleMergeManagerTest.java
Refactor to use mergeContext collect the arguments related to remote merger
- Make code clean and friendly to other developer who do not attention to `Remote Merger`.
- Without api change while extends the `mergeContext`.
No.
No need, just refactor.
> [MINOR]improvement(client/server): (RemoteMerger) Refactor to use mergeContext collect the arguments related

- common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java
- storage/src/main/java/org/apache/uniffle/storage/common/HadoopStorage.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopFileWriter.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandler.java
Support config buffer size for HadoopShuffleWriteHandler
Fix: #2209 
No.
Locally test.
> [#2209] [FOLLOWUP]feat(server) Support config buffer size for HadoopShuffleWriteHandler

- server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Introduce metrics related bitmaps.
Insight the block bitmap related count.
Fix: # (issue)
- committed_block_count
- reported_block_count
- cached_block_count
Locally.
> [MINOR] feat(server): Introduce metrics related bitmaps(committedBlockIds/cachedBlockIds/partitionToBlockIds)

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
Degrade the log of `Accepted blockIds report for` from `INFO` to `DEBUG` level.
Server log filled full of `Accepted blockId ...`, it is hard to find other useful log.
No.
No need, just log level change.
> [MINOR] improvement(server): Reduce huge amount of server log when `Accepted blockId`

- deploy/kubernetes/operator/api/uniffle/v1alpha1/remoteshuffleservice_types.go
- deploy/kubernetes/operator/config/crd/bases/uniffle.apache.org_remoteshuffleservices.yaml
- deploy/kubernetes/operator/pkg/controller/sync/shuffleserver/shuffleserver.go
- deploy/kubernetes/operator/pkg/controller/sync/shuffleserver/shuffleserver_test.go
Add optional PodManagementPolicy field under shuffleServer
To support cases where users deploy the shuffle service as a short-lived service that is deployed and deleted frequently, allowing users to set PodManagementPolicy to `Parallel` makes deployment time shorter
Introduce 1 new optional field in CRD:
PodManagementPolicy
UT + Manually
> [MINOR] feat(operator): Add support for PodManagementPolicy

- common/src/main/java/org/apache/uniffle/common/netty/protocol/Decoders.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/Message.java
- common/src/main/java/org/apache/uniffle/common/netty/protocol/SendShuffleDataRequestV1.java
- common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTest.java
- common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTestUtils.java
- server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
On the server side of the netty mode, when the server receives the sendShuffleData message, it decodes it into an unnecessary ShuffleBlockInfo and then converts it to ShufflePartitionedBlock in handleSendShuffleDataRequest. 
Fix: #2181 
No.
Locally
> [#2181]improvement(server): Replace ShuffleBlockInfo with ShufflePartitionedBlock in netty

- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/ShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfoTest.java
- client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/impl/FailedBlockSendTracker.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/impl/TrackingPartitionStatus.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReassignOnBlockSendFailureRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/response/RssSendShuffleDataResponse.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/HugePartitionUtils.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
Support sliced store partition to multiply server.
Limitation:
- Only finished tested the netty mode.
Fix: #2086
No.
- Start multiply servers and coordinator on local
- Start a spark standalone env on local
- Start spark-shell and execute `test.scala`
```Console
bin/spark-shell  --master  spark://localhost:7077  --deploy-mode client --conf spark.rss.client.reassign.blockRetryMaxTimes=3 --conf spark.rss.writer.buffer.spill.size=30 --conf spark.rss.client.reassign.enabled=true  --conf spark.shuffle.manager=org.apache.spark.shuffle.RssShuffleManager --conf spark.rss.coordinator.quorum=localhost:19999  --conf spark.rss.storage.type=LOCALFILE --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.rss.test.mode.enable=true --conf spark.rss.client.type=GRPC_NETTY --conf …
```
> [#2086] feat(spark): Support cut partition to slices and served by multiply server

- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
Record the unexpected exception event flushing operation duration
Fix: #2243
No.
Needn't
> [#2243] improvement(server): Record the unexpected exception event flushing operation duration

- .github/PULL_REQUEST_TEMPLATE
add some examples and notice
- To show more use case about how to write PR title
- Notice contributors to remove all the generated comments before review request.
> [MINOR] improvement(ci): add some examples and notice

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
LOG the exception call stack while unregisterShuffle
Easy to find the error call stack.
No.
No need.
> [MINOR] improvement(server): LOG the exception call stack while unregisterShuffle

- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Introduce option to mark server unhealthy once any storage corrupted.
For: #2241
This feature is to reduce the impact while the local directories are corrupted.
Yes. 
`rss.server.health.markUnhealthyOnceStorageCorruption` is introduced, the default value is false that will not activate this feature by default.
Existing unit tests.
> [#2241] feat(server): Introduce option to mark server unhealthy once any storage corrupted

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
- release/publish_maven_artifacts.sh
Fix the issue of license loss
LICENSE file is missing but license directory which is from  grpc-netty-shaded-1.61.1.jar exists.
And when published maven artifacts, I can not close.
No.
test in dev and cluster
> [MINOR] chore: Fix the issue of license loss

- client-spark/spark2-shaded/pom.xml
- client-spark/spark3-shaded/pom.xml
- release/publish_maven_artifacts.sh
Fix the issue of license loss
LICENSE file is missing but license directory which is from  grpc-netty-shaded-1.61.1.jar exists.
And when published maven artifacts, I can not close.
No.
test in dev and cluster
> [MINOR] chore: Fix the issue of license loss.

- common/src/main/java/org/apache/uniffle/common/future/CompletableFutureUtils.java
- common/src/test/java/org/apache/uniffle/common/future/CompletableFutureUtilsTest.java
- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Introduce storage flush operation timeout cancel to avoid disk hang
For #2241 
Yes.
`rss.server.storage.flushOptionTimeoutSec` is introduced, the default value = -1 means this timeout cancel will not be activated by default
unit tests and existing tests.
> [#2241] improvement(server): Introduce storage flush operation timeout cancel to avoid disk hang

- common/src/main/java/org/apache/uniffle/common/storage/StorageInfo.java
- server/src/main/java/org/apache/uniffle/server/Checker.java
- server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java
- server/src/test/java/org/apache/uniffle/server/HealthyMockChecker.java
- server/src/test/java/org/apache/uniffle/server/UnHealthyMockChecker.java
- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
fix wrong disk used space while config multiply dirs in one mount point
Fix: [#2251](https://github.com/apache/incubator-uniffle/issues/2251)
No.
No need.
> [#2251] fix(server): fix wrong disk used space while config multiply dirs in one mount point

- server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java
Mark the underlying thread name for flushing events
The follow up pr for #2241
No.
needn't
> [#2241][FOLLOWUP] improvement(server): Mark the underlying thread name

- common/src/main/java/org/apache/uniffle/common/metrics/MetricsManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
- dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java
- proto/src/main/proto/Rss.proto
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Report configured metrics of server to coordinator and display to dashboard
With this feature, it can be extensible for displaying server state by dashboard.
In the beginning, we only need to display the app number in the dashboard, after a few days, we want to add partition with node in to dashboard, maybe no more days later, we need another value displayed in to dashboard.
So it is not extensible if we add it one by one, this is why I invent this feature, it can be easy to let user config the metrics what they think it is necessary and should be displayed in the dashboard.
- new config: rss.server.displayMetricsList
Test Locally.
> [MINOR] feat(server,dashboard,coordinator): Report configured metrics of server to coordinator and display to dashboard

- cli/pom.xml
- client-mr/core/pom.xml
- client-mr/hadoop2.8/pom.xml
- client-mr/hadoop3.2/pom.xml
- client-spark/common/pom.xml
- client-spark/spark2-shaded/pom.xml
- client-spark/spark2/pom.xml
- client-spark/spark3-shaded/pom.xml
- client-spark/spark3/pom.xml
- client-tez/pom.xml
- client/pom.xml
- common/pom.xml
- coordinator/pom.xml
- dashboard/pom.xml
- deploy/kubernetes/pom.xml
- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/spark2/pom.xml
- integration-test/spark3/pom.xml
- integration-test/tez/pom.xml
- internal-client/pom.xml
- pom.xml
- proto/pom.xml
- server-common/pom.xml
- server/pom.xml
- storage/pom.xml
Bump version to 0.11.0-SNAPSHOT
I run the command in my Mac
```
gsed  -i "s%<version>0.10.0-SNAPSHOT</version>%<version>0.11.0-SNAPSHOT</version>%" $(grep -l "<groupId>org.apache.uniffle</groupId>" $(find . -name pom.xml))
```
Release 0.10.0
No.
No need.
> [MINOR] Bump version to 0.11.0-SNAPSHOT

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcRetryableClient.java
Fix error log for CoordinatorGrpcRetryableClient#accesCluster
The existing log can make user confused.
Correct spark am log
No need.
> [MINOR] fix(client): Fix error log for CoordinatorGrpcRetryableClient#accesCluster

- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java
The private variable dataLength of ShuffleBufferWithLinkedList will be cleared after toFlushEvent.
The private variable dataLength of ShuffleBufferWithLinkedList not be cleared after toFlushEvent.
Fix: #2259 
No.
Tested by UT.
> [#2259] fix(server) dataLength of ShuffleBufferWithLinkedList not be cleared after toFlushEvent

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
put sparkConf as extra properties while client request accessCluster
Coordinator can let the spark application access rss cluster or not by some customized access checker leverage some of the spark configs.
No.
No need
> [MINOR] improvement(spark-client): put sparkConf as extra properties while client request accessCluster

- common/src/test/java/org/apache/uniffle/common/log/TestLoggerExtension.java
Fix ConcurrentModifiedException while use TestAppender
```
[ERROR] testNewAppWhileCheckLeak{ExtensionContext}  Time elapsed: 0.3 s  <<< ERROR!
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
at java.util.ArrayList$Itr.next(ArrayList.java:861)
at org.apache.uniffle.common.log.TestLoggerExtension$TestAppender.wasLogged(TestLoggerExtension.java:106)
at org.apache.uniffle.common.log.TestLoggerExtension.wasLogged(TestLoggerExtension.java:73)
at org.apache.uniffle.server.storage.LocalStorageManagerTest.testNewAppWhileCheckLeak(LocalStorageManagerTest.java:399)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> [MINOR] test: Fix ConcurrentModifiedException while use TestAppender

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
Fix the bug of none object self when invoking the reflection method.
Fix: #2282
No.
Existing tests
> [#2282] improvement(spark3): Invoke with object self in DelegationRssShuffleManager

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandler.java
- storage/src/test/java/org/apache/uniffle/storage/handler/impl/PooledHadoopShuffleWriteHandlerTest.java
Correct the initialization flag to fix potential hang in PooledHadoopShuffleWriteHandler
fix: #2292
No.
Unit tests
> [#2292] fix(server): Potential hang when HadoopShuffleWriteHandler initialization failure in PooledHadoopShuffleWriteHandler

- server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
Correct the metric of grpc_get_local_shuffle_data_process_latency
fix #2298
No.
Needn't
> [#2298] fix(server): Correct the metric of grpc_get_local_shuffle_data_process_latency

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
The `timeoutMs` in ShuffleWriteClientImpl#sendAppHeartbeat method. The timeoutMs for per RPC is similar to the timeoutMs of ThreadUtils#executeTasks` for all servers RPC execute, and the logic here is flawed. 
Resetting the `timeoutMs` for `ThreadUtils.executeTask`.
Fix: #2188 
No.
no need
> [#2188] fix(client): Fixup timeoutMs for executeTasks in ShuffleWriteClientImpl#sendAppHeartbeat

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/RSSStageResubmitTest.java
If the current Reader fails to obtain Shuffle data, it does not trigger the upstream Stage to rewrite the data. If a Shuffle Server fails, it does not trigger Stage retry.
Fix: https://github.com/apache/incubator-uniffle/issues/2279
No.
UT.
> [#2279] improvement(spark): Trigger the upstream rewrite when the read stage fails 

- docs/remote_merge_guide.md
Fix the license format of remote_merge_guide.md
If we open https://github.com/apache/incubator-uniffle/blob/master/docs/remote_merge_guide.md, we can see the following warning.
```
Error in user YAML: (<unknown>): could not find expected ':' while scanning a simple key at line 6 column 1
```
No.
Unnecessary
> [MINOR] docs: Fix the license format of remote_merge_guide.md

- server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java
As title.
Fix: #1782
No.
Existing UTs.
> [#1782] fix: Fix flaky test ShuffleBufferManagerTest

- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Client stop retrying and throw RssException for reportShuffleResult operation while interrupted by caller.
Fix: #2269 
No.
No need
> [#2269] refactor: Fix duplicated blockIds issue caused by duplicated reportShuffleResult

- storage/src/test/java/org/apache/uniffle/storage/HadoopTestBase.java
Disable System exit for HadoopTestBase
Without this, we cannot find the root cause of failure test, we can only find out the test process crashed.
No.
Existing UTs.
> [MINOR] fix(test): Disable System exit for HadoopTestBase

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileBlackHoleWriter.java
Introduce a new implementation of FileWriter, named `LocalFileBlackHoleWriter`.
Drop all the data, specify `LocalFileBlackHoleWriter` for test the ceiling performance of flush event.
No.
Tested on our pressure cluster.
> [MINOR] feat(server): Introduce LocalFileBlackHoleWriter for test flush ceiling performance

- client-spark/common/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManagerUtils.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTestBase.java
- internal-client/src/main/java/org/apache/uniffle/client/api/CoordinatorClient.java
- internal-client/src/main/java/org/apache/uniffle/client/factory/CoordinatorClientFactory.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcRetryableClient.java
Close coordinator client in time.
Grpc retry will throw exception for all the time.
```
[16:44:57:437] [grpc-default-executor-0] WARN  org.apache.uniffle.shaded.io.grpc.internal.ManagedChannelImpl.handleErrorInSyncContext:1866 - [Channel<1>: (a:10000)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host a, cause=java.lang.RuntimeException: java.net.UnknownHostException: a: 未知的名称或服务
    at org.apache.uniffle.shaded.io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
    at org.apache.uniffle.shaded.io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
    at org.apache.uniffle.shaded.io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
    at …
```
> [MINOR] fix(spark-client) Close coordinator client in time

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
Fix fallback to sort fail issue
Support fallback to sort shuffle service.
No.
Existing UTs.
> [MINOR] fix(spark-client): Fix fallback to sort fail issue

- integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcServerTest.java
- internal-client/src/main/java/org/apache/uniffle/client/api/CoordinatorClient.java
Fix flaky test for CoordinatorGrpcServerTest#testGrpcConnectionSize
Do some efforts to make Ci more stable.
NO
Existing UTs.
> [MINOR] fix(test): Fix flaky test for CoordinatorGrpcServerTest#testGrpcConnectionSize

- release/create-package.sh
Update the project directory name
Fix: #1872 
No.
current UT
> [#1872] improvement: Update the project directory name

- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
Fix flaky test CoordinatorServerTest#test
Make CI stable.
No.
Existing UT.
> [MINOR] fix(test): Fix flaky test CoordinatorServerTest#test

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
Refactor and abstract the same code into base class.
Reduce the redundant code and simplify the development in rss spark-client scope.
The Spark version unrelated code should be placed into RssShuffleManagerBase class, for this RssShuffleManager Class, it should only maintains the spark api related codes.
No.
- Existing UTs.
- Our test cluster, tested both spark v2 and v3 version.
> [MINOR] improvement(spark-client): Refactor RssShuffleManager for spark2 and spark3 to reduce redundant code

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileNullDeviceWriter.java
Introduce a new implementation of FileWriter, named LocalFileNullDeviceWriter.
Write all the data into null device, specify LocalFileNullDeviceWriter for test the ceiling performance of flush event but kept the cost for file level api.
No.
Tested on our test cluster.
> [MINOR] feat(server): Introduce LocalFileNullDeviceWriter to flush data into null device for test flush ceiling performance

- integration-test/common/pom.xml
- integration-test/mr/pom.xml
- integration-test/spark-common/pom.xml
- integration-test/tez/pom.xml
- pom.xml
Fix the warning:   Parameter `systemProperties` is deprecated: Use `systemPropertyVariables` instead.
Fix: #2335 
No.
current UT
> [#2335] Improvement: Fix the warning:   Parameter `systemProperties` is deprecated: Use `systemPropertyVariables` instead.

- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
Fix the warning that delete(Path) in FileSystem has been deprecated
Fix: #2346 
No.
current UT
> [#2346] Improvement: Fix the warning that delete(Path) in FileSystem has been deprecated

- coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorMetrics.java
Add metrics of active/lost server number
for #2350 
No.
Needn't
> [#2350] improvement(coordinator): Add metrics of active/lost server number

- client/src/main/java/org/apache/uniffle/client/record/reader/RMRecordsReader.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTestWhenShuffleFlushed.java
Fix the warning: unchecked method invocation: method put in interface Map is applied to given types
Fix: #2349 
No.
current UT
> [#2349] Improvement: Fix the warning: unchecked method invocation: method put in interface Map is applied to given types

- common/src/main/java/org/apache/uniffle/common/netty/buffer/FileSegmentManagedBuffer.java
- common/src/test/java/org/apache/uniffle/common/netty/buffer/FileSegmentManagedBufferTest.java
FileSegmentManagedBuffer#nioByteBuffer add a buffer to hold read file result to avoid multiple read file
Fix: #1658 
No.
existed  UT
> [#1658] fix(server): FileSegmentManagedBuffer#nioByteBuffer read result cacheable

- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/GrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
- internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Introduing the config option to set the grpc netty based network impl event loop threads
Fix: #2354 
Yes.
Tests in the spark jobs
> [#2354] feat(client): Explicitly setting grpc netty based event loop threads to avoid too much threads

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Record the partition choosing sort time for analysis
For better optimize write duration
No.
Needn't
> improvement(spark): Record the partition choosing sort time for analysis

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/PrefetchableClientReadHandler.java
Followup #2365 . Record the background fetch time to compare with the real read time to get the overlapping time to know more about the prefetch performance
To know about the performance for online spark jobs
No.
Needn't
> [#291] feat(client): Record background fetch time for prefetch

- client/src/main/java/org/apache/uniffle/client/record/reader/RMRecordsReader.java
Fix the warning: unchecked call to put(E) as a member of the raw type RMRecordsReader.Queue
Fix: #2356
No.
current UT
> [#2356] Improvement: Fix the warning: unchecked call to put(E) as a member of the raw type `RMRecordsReader.Queue`

- common/src/main/java/org/apache/uniffle/common/ReconfigurableRegistry.java
Fix the warning: [unchecked] unchecked call to add(E) as a member of the raw type List
Fix: #2370
No.
> [#2370] Improvement: Fix the warning: [unchecked] unchecked call to add(E) as a member of the raw type List

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client/src/test/java/org/apache/uniffle/client/ClientUtilsTest.java
- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
- server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
- server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java
- server/src/main/java/org/apache/uniffle/server/storage/SingleStorageManager.java
- server/src/test/java/org/apache/uniffle/server/StorageCheckerTest.java
Simplify return expression
Cleanup redundancy code, make lambda expression more elegant
No.
UT
> [MINOR] improvement: Simplify return expression

- coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
The initial an interval execution time of `SimpleClusterManager.nodesCheck` changed from 100ms to 200ms, this can make condition verify of unit test execute before and after `nodesCheck`
- Pass the flaky test
- set bigger rss.coordinator.server.heartbeat.timeout to avoid `SimpleClusterManager.nodesCheck` happens before the first execution of await condition, since the default poll time of the `org.awaitility.Awaitility.await` is 100ms
Fix: #2376
No.
Flaky test can be fixed
> [#2376] test(coordinator): The interval of `SimpleClusterManager.nodesCheck` should be bigger than that of `org.awaitility.Awaitility.await`

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
1. Fake ports are not duplicate and limit to the valid range 1-65535, which can make the client rpc fast fail if the corresponding shuffleServer do not exist
2. App expire time should be greater enough, so that rpc retry and secondary sending around will not encounter app expire
Fix: #2378
No.
UT
> [#2378] test(client): Fix flaky test QuorumTest#case10

- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithKerberizedHadoopTest.java
Introduce a new way to start servers
1. Store coordinator and shuffleServer conf
2. Initialize coordinator and shuffleServer lazily by using random port in `startServersWithRandomPorts`
3. Pass coordinator quorum to shuffleServer after coordinator started
Avoid port conflicts of unit test
Fix: #2382
No.
UT
> [#2382] improvement(test): Fix ServletTest, ShuffleServerFaultToleranceTest,ShuffleServerWithKerberizedHadoopTest to use random port

- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RMRssShuffle.java
- client/src/main/java/org/apache/uniffle/client/record/reader/KeyValueReader.java
- client/src/main/java/org/apache/uniffle/client/record/reader/RMRecordsReader.java
- client/src/test/java/org/apache/uniffle/client/record/reader/RMRecordsReaderTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTestWhenShuffleFlushed.java
KeyValueReader::next combines the semantics of hasNext and next, which is unreasonable and should be separated.
Fix: #2389 
No.
unit test and integration test
> [#2389] fix:(remote merge): Fixed the issue of losing data when calling hasNext multiple times.

- integration-test/common/src/test/java/org/apache/uniffle/test/IntegrationTestBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
Close shuffle client per test
ShuffleClient never close in all unit test
Below action failed mainly because shuffleclient leak, in a result channel process slow down
https://github.com/apache/uniffle/actions/runs/13764353793/job/38487344830
```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: CallOptions deadline exceeded after 0.199753390s. Name resolution delay 0.000111669 seconds. [closed=[], open=[[buffered_nanos=200741728, waiting_for_connection]]]
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
at  org.apache.uniffle.proto.ShuffleServerGrpc$ShuffleServerBlockingStub.registerShuffle(ShuffleServerGrpc.java:850)
at …
```
> [MINOR] fix(test): Prevent shuffle rpc client leak in test

- common/src/main/java/org/apache/uniffle/common/netty/buffer/FileSegmentManagedBuffer.java
Avoid release cachedBuffer, when FileSegmentManagedBuffer release
There is no need to invoke release, since the reference of cachedBuffer is reset, besides this may cause concurrent issue
Fix #2404 
No.
UT
> [#2385] fix(server): FileSegmentManagedBuffer release concurrently avoid NPE

- common/src/main/java/org/apache/uniffle/common/web/JettyServer.java
- common/src/test/java/org/apache/uniffle/common/web/JettyServerTest.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
- coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorServerTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServer.java
- server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java
Make it possible to get the actual port when config jetty port to zero
Support jetty use random port
Fix: #2401 
No.
UT
> [#2401] Make it possible to get the actual port when config jetty port to zero

- common/src/test/java/org/apache/uniffle/common/KerberizedHadoop.java
- common/src/test/java/org/apache/uniffle/common/util/RetryUtilsTest.java
Fix the warning unchecked generic array creation for varargs parameter of type `Class<? extends Throwable>[]`
Fix: #2398
No.
> [#2398]Improvement: Fix the warning unchecked generic array creation for varargs parameter of type `Class<? extends Throwable>[]`

- storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
- storage/src/test/java/org/apache/uniffle/storage/common/DefaultStorageMediaProviderTest.java
When I run the unit tests on the `/dev/nvme0n1p6` filesystem, Linux incorrectly assumes that this in a HDD. It tries to read info from `/sys/block/nvme0n1p/queue/rotational` but it should read info from `/sys/block/nvme0n1/queue/rotational`.
The method `getDeviceName` correctly removes the numbers at the end from `sda1` to create a device name `sda` but it does not handle nvme devices correctly, mount point  `nvme0n1p6` should return `nvme0n1` as device name, we need to remove the `p6` part. 
```
[INFO] Running org.apache.uniffle.server.storage.LocalStorageManagerTest                                                 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.879 s <<< FAILURE! - in org.apache.uniffle.server.storage.LocalStorageManagerTest
[ERROR] …
```
> [MINOR] fix(test): Fix test for LocalStorageManagerTest

- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/ShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/SimpleShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/StageAttemptShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/split/PartitionSplitInfo.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/TaskAttemptAssignment.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/PartitionSplitMode.java
- common/src/main/java/org/apache/uniffle/common/config/RssClientConf.java
- integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkIntegrationTestBase.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/PartitionSplitOfLoadBalanceModeTest.java
- proto/src/main/proto/Rss.proto
Introduce the load_balance mode for partition split
Firstly, thanks the great work to @maobaolong . This work is based on the #2093, this introduces the load_balance mode for the partition split.
As we know, if the partition is big, the partition split will be activated to reassign to another server. For the default impl, the reassign logic is pipeline. it will reassign for first server -> second -> third until reaching the max reassignment server num limit.
But for the huge partition with huge write throughput at the same time, I hope this can write the multi servers for load balance to speed up writing.
Yes. 
1. `rss.client.reassign.partitionSplitMode`. Default value PIPELINE (that is consistent with previous codebase)
2. `rss.client.reassign.partitionSplitLoadBalanceServerNumber` . …
> feat(client): Introduce `LOAD_BALANCE` mode for partition split

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Improving error message in `ShuffleWriteClientImpl`
`ShuffleWriteClientImpl` prints out this error message, which is not very useful:
```
org.apache.uniffle.common.exception.RssException: getShuffleAssignments or registerShuffle failed!                                                                                            
at org.apache.uniffle.shuffle.manager.RssShuffleManagerBase.requestShuffleAssignment(RssShuffleManagerBase.java:1378)                                                                 
at org.apache.uniffle.shuffle.manager.RssShuffleManagerBase.requestShuffleAssignment(RssShuffleManagerBase.java:1390)                                                                 
at org.apache.spark.shuffle.RssShuffleManager.registerShuffle(RssShuffleManager.java:150) …
```
> [MINOR] improvement(client): Detailed error message in ShuffleWriteClientImpl

- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssMergeManager.java
Fixing logger classname.
Logger classname was MergeManager in RssMergeManager class.
No.
UT
> [MINOR] Fix logger classname in RssMergeManager

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Skip the application which is expired when flushing buffers.
All RPC executors will be blocked when flushBuffer and removeResources are triggered at the same time in the same app.
Fix: #2426
No.
Existing UTs.
> [#2426] improvement: Skip the application which is expired when flushing buffers

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
Remove unnecessary release for ByteBuf
Fix: #2082
No.
CI passed. User verified this fix in the production environment.
> [#2082] fix: spark executor task error when reading shuffle data when  using java open jdk11

- storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
- storage/src/test/java/org/apache/uniffle/storage/common/DefaultStorageMediaProviderTest.java
This part of `testStorageProvider` should test the default storage media for a non-existent directory. But 47cac3918ff6cdd3873754acc4d6524c4326c604 changed the behavior of `getStorageMediaFor`, now it checks the parent directory (recursively)  so for `/path/to/base/dir` it will end up checking `/` which is existent. With this change it will check `path` which is missing, so it will really check the default value.
```
[INFO] Running org.apache.uniffle.storage.common.DefaultStorageMediaProviderTest                                         
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.586 s <<< FAILURE! - in org.apache.uniffle.storage.common.DefaultStorageMediaProviderTest
[ERROR] testStorageProvider  Time elapsed: 0.017 s  <<< FAILURE! …
```
> fix(test): Fix test about default storage type for DefaultStorageMediaProviderTest

- docs/client_guide/mr_client_guide.md
- docs/client_guide/tez_client_guide.md
Fixing storage type in documentation.
The documentation refers to MEMORY_LOCAL_HADOOP mode.
No.
Not tested, this is just a documentation change.
> [MINOR] docs: fix storage type in MR / TEZ documentation.

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleWithRssClientTest.java
Remove shuffleServer from coordinators when it stops.
Fix: #2439
No.
Repeat it for 100 times.
> [#2439] fix(test): remove shuffleServer from coordinators when it stops

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Now the master branch code is not compatible with the gluten latest version, this is caused by the #1838.
And so this PR is to fix this uncompatible problem.
Please see https://github.com/apache/incubator-gluten/blob/main/backends-velox/src-uniffle/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java
Fix compatibility with gluten 
No.
Internal production tests.
> fix(spark3): Reserve previous writer initialization way for gluten + uniffle

- client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java
- coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
- server/src/main/java/org/apache/uniffle/server/merge/Shuffle.java
- server/src/main/java/org/apache/uniffle/server/merge/ShuffleMergeManager.java
- storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
Replace putIfAbsent to avoid performance loss
Fix: #493
No.
CI
> [#493][FOLLOWUP] improvement: replace putIfAbsent to avoid performance loss

- server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Fixes #2428
This PR improves the robustness of the test `LocalStorageManagerTest.testGetLocalStorageInfo`, which previously failed on certain environments due to incorrect disk type detection (SSD vs HDD).
- Improved the logic for detecting disk type via `lsblk` to handle unexpected or missing ROTA values
- Silently skipped media type assertion if detection is not reliable, avoiding false failures
The test is flaky on machines with NVMe SSDs or less common disk setups, where tools like `lsblk` may not return consistent results. This leads to false test failures even when the logic is correct. 
No.
Manually tested the fix on both SSD and HDD environments by running:
```bash
mvn test -Dtest=LocalStorageManagerTest
> [#2428] fix(test): Fix flaky test for LocalStorageManagerTest#testGetLocalStorageInfo

- deploy/kubernetes/docker/build.sh
Setting correct `HADOOP_SHORT_VERSION` if we provide `--hadoop-version`.
Without this, if we specify `--hadoop-version 3.2.1` it installs hadoop 3.2.1 to the image with `rss-0.11.0-SNAPSHOT-hadoop2.8.tgz` instead of the correct `rss-0.11.0-SNAPSHOT-hadoop3.2.tgz`
No.
Running the script locally.
> [MINOR] fix(docker): Fix hadoop version

- client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java
This PR corrects the reflection logic in `RssDAGAppMaster.DagInitialCallback` when setting the `className` for `InputDescriptor`. It now correctly obtains the `Field` object directly from `InputDescriptor`'s class hierarchy, instead of incorrectly reusing the `Field` object derived from `OutputDescriptor`.
The previous code mistakenly used the `Field` for `className` obtained from `OutputDescriptor` to modify the `InputDescriptor`.
This **happened to work** likely because both `InputDescriptor` and `OutputDescriptor` inherit the `className` field from a common superclass. Java's reflection allows applying a `Field` object to any instance that possesses that field (often through inheritance), even if the `Field` was retrieved via a different related class.
This fix ensures the reflection …
> [MINOR] fix(tez): Use correct Field object for InputDescriptor className

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/AddBlockEvent.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleServerPushCost.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleServerPushCostTracker.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
- client/src/main/java/org/apache/uniffle/client/response/SendShuffleDataResult.java
Introducing shuffle-server data push statistics in writer
Sometimes we found some jobs are slow due to the underlying one server slow, but under the current codebase, it's hard to found it. This PR is to track the shuffle-servers speed to output.
BTW, based on this PR, I will introduce the uniffle spark UI for easier and better observability.
No.
> [#2457] feat(spark): Introducing shuffle-server data push statistics

- bin/start-coordinator.sh
- common/src/main/java/org/apache/uniffle/common/web/JettyServer.java
- common/src/main/java/org/apache/uniffle/common/web/resource/MetricResource.java
- dashboard/src/main/java/org/apache/uniffle/dashboard/web/Dashboard.java
When using a high version of JDK9.0 or above, when starting services such as Coordinator and Shuffle Server for the first time and when http services are accessible, some alarm logs will be printed. Although it doesn't affect the service, it's very uncomfortable to print.
`WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/hadoop/share/hadoop/common/lib/jaxb-impl-2.2.3-1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Apr 15, …
> [Improvement] Clear the alarm log when starting the relevant service

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/extension/pom.xml
- client-spark/extension/src/main/resources/META-INF/services/org.apache.spark.status.AppHistoryServerPlugin
- client-spark/extension/src/main/scala/org/apache/spark/UniffleHistoryServerPlugin.scala
- client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala
- client-spark/extension/src/main/scala/org/apache/spark/UnifflePlugin.scala
- client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala
- client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala
- pom.xml
1. Add support of history server plugin
2. Optimize UI performance by more memory cache and less status store access
3. Add more infos and correct partial metric unit show 
4. Enable shuffle manager rpc when UI plugin is enabled
followup for #2459 
No.
> [#2460] feat(spark)(part-2): Add support of history server plugin

- coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java
Ignore appIdToInfos when serialize ServerNode
Fix #2466
No.
Manual Testing
> [#2466] fix(server): Ignore appIdToInfos when serialize ServerNode

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Add an option to disable flush buffer when caching data.
Fix: #2496
set `rss.server.buffer.flush.triggeredWhenCachingData` to false
and make sure `rss.server.shuffleBufferManager.trigger.flush.interval` is bigger than 0
CI
> [#2495] feat(server): Add an option to disable flush buffer when caching data

- client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala
Add client/uniffle different observed shuffle speed
followup #2460 
No.
Neen't
> [#2460] feat(spark3): Add client/uniffle different observed shuffle speed

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java
- client/src/main/java/org/apache/uniffle/client/impl/FailedBlockSendTracker.java
- common/src/main/java/org/apache/uniffle/common/ShuffleBlockInfo.java
- common/src/test/java/org/apache/uniffle/common/ShuffleBlockInfoTest.java
Fast fail for those stale assign blocks for partition reassign
for #2502
No.
Add unit tests
> [#2502] feat(spark3): Fast fail for those stale assign blocks for partition reassign

- client-spark/common/src/main/java/org/apache/spark/shuffle/events/TaskShuffleReadInfoEvent.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/events/TaskShuffleWriteInfoEvent.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleReadMetricRequest.java
- internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleWriteMetricRequest.java
- proto/src/main/proto/Rss.proto
Record failed tasks on any shuffle write/failure into event logs
For #2508. Having this PR, we could retrieve spark jobs failure reason from the whole clusters' event logs.
No.
Neen't
> [#2508] feat(spark3): Record failed tasks on any shuffle write/failure into event logs

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Disable fast fail on any pushing failure if partition reassign is activated
Before this PR, if multi-replica is disabled, the sending logic would fail fast upon any push failure.
However, when partition reassignment is enabled, this behavior could cause some block futures to be canceled, leading to the loss of block sending events.
As a result, the client might fail due to unsent remaining blocks.
for #2518
No.
Needn't. This could be quickly validated by human.
> [#2518] fix(client): Disable fast fail on any pushing failure if partition reassign is activated

- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
Skip reassignment number check on partition split and reuse the assigned server for split partition
fix #2503
No.
Internal job test
> [#2503] fix(spark): Skip reassignment number check on partition split

- client-spark/common/src/main/java/org/apache/spark/shuffle/events/ShuffleWriteTimes.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Shuffle write total duration is incorrectly accumulated in event log
fix #2520
No.
Needn't
> [#2520] fix(spark3): Shuffle write total duration is incorrectly accumulated in event log

- server/src/main/java/org/apache/uniffle/server/buffer/lab/ChunkCreator.java
If the chunId overflow it will reset it to (max chunk id in the chunk pool + 1)
Fix: #2526 Handle the possible overflow of the chunkId
No.
Unit test
> [#2526] improvement: Reset the chunkID if it overflow

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
- common/src/main/java/org/apache/uniffle/common/DeferredCompressedBlock.java
- common/src/main/java/org/apache/uniffle/common/ShuffleBlockInfo.java
- common/src/test/java/org/apache/uniffle/common/DeferredCompressedBlockTest.java
- integration-test/spark3/src/test/java/org/apache/uniffle/test/CompressionOverlappingTest.java
Support overlapping compression to avoid block shuffle writing
for #2494 . 
After applying the proposed improvements, the client observed that shuffle performance doubled in a 100GB Terasort benchmark. Specifically, the overall shuffle speed improved by over 100%, significantly reducing the job’s runtime and demonstrating the effectiveness of the optimizations in large-scale sorting workloads.
Yes.
Will be added later.
> [#2494] feat(spark): Overlapping compression to avoid blocking shuffle writing

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/OverlappingCompressionDataPusher.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/OverlappingCompressionDataPusherTest.java
Introduce extra the option to control the concurrency of overlapping compression.
for #2536 .
Decoupling compression concurrency from the transfer pool is essential for resource isolation and performance stability, especially under multi-tenant or CPU-constrained environments.
Yes.
`rss.client.write.overlappingCompressionThreads=-1`.
About overlapping compression related config options, I will add it into doc in another PR
Unit tests.
> [#2536] feat(spark): Controllable concurrency for overlapping compression

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/OverlappingCompressionDataPusher.java
- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/OverlappingCompressionDataPusherTest.java
Make the overlapping compression threads pool's threads number aligned with the spark executor vcores by the ratio of per vcore.
Compression is a computing sensitive workload, we'd better to obey the rule of vcores allocation.
Yes. 
`rss.client.write.overlappingCompressionThreadsPerVcore = -1`
existing unit tests.
> [#2545] feat: Align with spark executor cores on overlapping compression

- common/src/main/java/org/apache/uniffle/common/compression/StatisticsCodec.java
Converting  `List<codeCost>`   into a synchronize list
this bugs happened in concurrent environment when spark workers with the `RssShuffleManager` and  spark.rss.client.io.compression.statisticsEnabled property enabled, logs its compression statistics when finished, but since the class was not prepared for concurrent enviroment, at the time to call `List<codeCost>` into the `codec.statistics()` methods enters in a race condition.
Fix: # 2544
No.
this issue was diffcult to replicate  into a local enviroment, but instead  when the patch was applied, i make sure the application continue working as usual by: 
1- deploying the application based on  `./deploy/docker/read.me`  
2- when executing the spark-shell make sure to do it by including the …
> [#2544] fix(client): NPE about StatisticsCodec

- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Change the default value of chunkPoolCapacityRatio
The proportion and the frequency of small blocks is not high. If this value is set too high, it may cause off-heap memory overflow.
Fix: #2492
No.
Verify in production environment.
> [#2492][FOLLOWUP] improvement: change the default value of chunkPoolCapacityRatio

- storage/src/main/java/org/apache/uniffle/storage/handler/impl/MultiReplicaClientReadHandler.java
When multi replica or partition split is enabled,  the log with blockId unexception message will always show when reading from one shuffle-server, that will make someone confuse. 
Shorten log for multi replica client reader
No.
Neen't
> [MINOR] improvement(client): Shorten log for multi replica client reader

- client-spark/common/src/test/java/org/apache/spark/shuffle/reader/RssShuffleDataIteratorTest.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java
- storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopClientReadHandler.java
Fast fail on hadoop reader initialization failure
When the hadoop reader initialization failed, this exception will be ignored. When the final unexcepted blockIds throws, it’s hard to find out the root cause.
And so, we should fast fail in this case.
No.
Existing unit tests.
> [#2560] improvement(client): Fast fail on hadoop reader initialization failure

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTest.java
fix invalid remote storage configuration was propagated during application registration
fix #2549
No.
Yes. existing tests and internal cluster tests.
> [#2549] fix: Invalid remote storage configuration was propagated during application registration

- client-spark/common/src/main/java/org/apache/spark/shuffle/writer/TaskAttemptAssignment.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
This PR is to add more logs of shuffle write on reassignment failure for the next inspection when it occurs.
for #2563 .
```
25/07/29 08:13:25 ERROR TaskResources: Task 14257 failed by error: 
org.apache.uniffle.common.exception.RssException: No available replacement server for: 10.xxxxx-23100-23104
at org.apache.spark.shuffle.writer.RssShuffleWriter.reassignAndResendBlocks(RssShuffleWriter.java:832)
at org.apache.spark.shuffle.writer.RssShuffleWriter.collectFailedBlocksToResend(RssShuffleWriter.java:672)
at org.apache.spark.shuffle.writer.RssShuffleWriter.checkDataIfAnyFailure(RssShuffleWriter.java:570)
at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:532)
at org.apache.spark.shuffle.writer.RssShuffleWriter.internalCheckBlockSendResult(RssShuf …
```
> [#2563] improvement(spark): Add more logs of shuffle write on reassignment failure

- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerConcurrentWriteOfHadoopTest.java
- server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java
- server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Limit the max flush event count for a single buffer.
Fix: #2558 
No.
Verify in production environment.
> [#2558] improvement(server): Limit the max flush event count for a single buffer

- client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Using the thread safe way to add shuffle-servers to emlinate race condition
fix #2571
No.
Needn't
> [#2571] fix(client): Race condition when adding shuffle servers

- common/src/main/java/org/apache/uniffle/common/util/JavaUtils.java
Cache the java9+ var to eliminate lock when creating concurrent hashmap
fix #2576 .
`Enums.getIfPresent` will always using the global lock, this is unnecessary and hurt the performance
No.
> [#2576] fix: Warm up java version var to eliminate lock on creating concurrent hashmap

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/RssSparkShuffleUtilsTest.java
- client-spark/spark2/src/test/java/org/apache/spark/shuffle/RssSpark2ShuffleUtilsTest.java
- client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssSpark3ShuffleUtilsTest.java
Use `SparkContext.getActive` instead of `getOrCreate` to better align with the intended semantics for external invocation.
Fix #2581
No.
Added unit test
> [#2581] fix(spark): Use `SparkContext getActive` instead of `getOrCreate` to align with method semantics

- client-spark/common/src/main/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfo.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/handle/MutableShuffleHandleInfoTest.java
- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
- proto/src/main/proto/Rss.proto
This PR uses a space-efficient protobuf data structure to store the partitions-to-servers mapping, thereby reducing the RPC cost.
This is the part of PR for the #2568. 
In large-scale Spark jobs, the number of partitions can reach up to 20K, whereas the number of assigned shuffle servers remains smaller than the total number of nodes in the Uniffle cluster.
Prior to this PR, both the driver and the client (when reassignment was enabled) required substantial memory for RPC transfers, which could significantly increase the frequency of driver garbage collection.
No
Unit tests.
> [#2568] feat(spark): Use space-efficient protobuf for `MutableShuffleHandleInfo` to reduce RPC memory overhead

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
Only enable taskId filter mechanism on AQE skew hit and multi replicas. Previously, when multi shuffle servers are assigned for reader to read, it will enable this mechanism, that will hurt the shuffle-servers performance due to the bitmap check, actually there is no need to do this on partition reassign (partition split) is enabled.
To fix #2583 
No.
Existing tests
> [#2583] fix(spark): Enable taskId filter only on AQE and multi replicas for reader

- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java
- docs/client_guide/spark_client_guide.md
1. Enable overlapping compression by default
2. Add doc for this feature
for #2494 
Yes.
Needn't
> [#2494] feat(spark): Enable overlapping compression by default

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
Ignore failure when reporting shuffle read metrics to driver
fix #2592 
No.
Needn't
> [#2592] fix(spark): Ignore failure when reporting shuffle read metrics to driver

- client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java
- client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java
- client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcher.java
- client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssTezShuffleDataFetcher.java
- client/src/main/java/org/apache/uniffle/client/api/ShuffleReadClient.java
- client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java
- client/src/main/java/org/apache/uniffle/client/impl/DecompressionWorker.java
- client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java
- client/src/main/java/org/apache/uniffle/client/response/DecompressedShuffleBlock.java
- client/src/main/java/org/apache/uniffle/client/response/ShuffleBlock.java
- client/src/test/java/org/apache/uniffle/client/TestUtils.java
- client/src/test/java/org/apache/uniffle/client/impl/DecompressionWorkerTest.java
- client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/HybridStorageFaultToleranceBase.java
- integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithHadoopTest.java
- integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithKerberizedHadoopTest.java
This PR is to introduce the overlapping decompression for the shuffle reading for the better shuffle speed.
for #2601
When applying the https://github.com/apache/uniffle/pull/2598 into the benchmark of terasort 100g, I found some bottleneck for the decompression time in the read phase. 
Based on a 100 GB Terasort benchmark, the results are impressive, reducing shuffle read time by 50% after applying this PR.
Yes
1. Unit tests.
> [#2601] feat(spark): Overlapping decompression for shuffle read

- release/publish_to_svn.sh
Remove incubator to correct uniffle svn url
fix invalid url
No.
Neen't
> fix: Remove incubator to correct uniffle svn url

- client-spark/common/src/test/java/org/apache/spark/shuffle/writer/TaskAttemptAssignmentTest.java
- common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java
- common/src/test/java/org/apache/uniffle/common/ShuffleServerInfoTest.java
Make shuffleServerInfo comparable for `updatePartitionSplitAssignment`
fix 2622
No.
Unit tests
> [#2622] fix(spark): Make shuffleServerInfo comparable for `updatePartitionSplitAssignment`

- client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java
- client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala
Fix the invalid reassign status show in spark UI tab
In the original design, the reassign info event is sent in the final stop method. However, because the post operation runs asynchronously, the listener may not receive the event before the JVM shuts down, so the event is effectively dropped.
No.
Internal spark job test
> [#2618] fix(spark): Invalid reassign status show in spark UI tab

- client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Skip failure when reporting shuffle write metrics to driver
followup the PR for the #2592 
No.
Needn't
> [#2592] fix(spark): Skip failure when reporting shuffle write metrics to driver

- server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
- server/src/main/java/org/apache/uniffle/server/block/DefaultShuffleBlockIdManager.java
- server/src/main/java/org/apache/uniffle/server/block/PartitionedShuffleBlockIdManager.java
- server/src/main/java/org/apache/uniffle/server/block/ShuffleBlockIdManager.java
Solve the problem of data loss caused by Spark task retries and Block metadata Report retries.
Fix: #2631 
No.
Exist UT.
> [#2631] fix(server): Potential data loss due to the shuffle result report retry
