coordinator/src/main/java/com/tencent/rss/coordinator/PartitionBalanceAssignmentStrategy.java, server/src/main/java/com/tencent/rss/server/storage/LocalStorageManager.java, server/src/main/java/com/tencent/rss/server/storage/SingleStorageManager.java
Trivial code improvements
code improvements
No
No
=> Trivial code improvements

coordinator/src/main/java/org/apache/uniffle/coordinator/PartitionBalanceAssignmentStrategy.java
Covert PartitionAssignmentInfo to static inner class.
To avoid creating unnecessary outer class
No.
Existing UT.
=> Covert PartitionAssignmentInfo to static inner class

server/src/main/java/com/tencent/rss/server/ShuffleFlushManager.java, server/src/main/java/com/tencent/rss/server/storage/HdfsStorageManager.java, server/src/main/java/com/tencent/rss/server/storage/SingleStorageManager.java, server/src/test/java/com/tencent/rss/server/ShuffleFlushManagerTest.java
There will be NPE problem when process the event if application was cleared already
Fix a critical bug which cause resource leak. 
No
UT is added
=> [Bug] Fix NPE problem when process the event if application was cleared already

integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManager.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManagerFallback.java
Remove redundant package.
Introduced in #18.
No
No
=> Remove redundant package

.asf.yaml
Fix the issues introduced in #25 to correct the notifications.
Reduce the PR comment noise in dev@.
No.
N/A
=> [INFRA] Improve asf.yaml to reduce the notifications (another-try)

pom.xml
Bump commons-lang3 from 3.5 to 3.10
execute test case error in jdk 11.
```
2022-07-05 16:32:54,311 INFO  [main] storage.BlockManagerMasterEndpoint (Logging.scala:logInfo(57)) - BlockManagerMasterEndpoint up
java.lang.ExceptionInInitializerError
at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:109)
at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:371)
at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:311)
at org.apache.spark.SparkEnv$.create(SparkEnv.scala:359)
at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:189)
at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
at …
```
=> Bump commons-lang3 from 3.5 to 3.10

README.md
Fix some hyperlink error in README.md 
Fix some hyperlink error
No
Manual
=> Fix some hyperlink in README.md

coordinator/src/main/java/org/apache/uniffle/coordinator/AbstractAccessChecker.java, coordinator/src/main/java/org/apache/uniffle/coordinator/AccessCandidatesChecker.java, coordinator/src/main/java/org/apache/uniffle/coordinator/AccessChecker.java, coordinator/src/main/java/org/apache/uniffle/coordinator/AccessClusterLoadChecker.java, coordinator/src/test/java/org/apache/uniffle/coordinator/AccessManagerTest.java
Explicitly set the constructor with AccessManager when extending AccessChecker
In current codebase, when i extends the AccessChecker, i dont know to set the constructor with the AccessManager. So i think make the AccessChecker abstract is necessary.
No.
no need.
=> Explicitly set the constructor with AccessManager when extending AccessChecker

client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Log enhancement: Merge multiple logs into oneline and add more description 
Adding more description to analyze the request time cost.
No 
No need
=> Log enhancement: Merge multiple logs into oneline and add more description 

coordinator/src/main/java/org/apache/uniffle/coordinator/PartitionBalanceAssignmentStrategy.java
Fixed the comment.
Missing byte units.
No.
Without any test.
=> [MINOR] Comments of PartitionBalanceAssignmentStrategy miss byte units

client/src/main/java/org/apache/uniffle/client/util/RssClientConfig.java
Make config keys and default values in `RssClientConfig` final.
No.
CI.
=> [Minor] Make config keys and default values finalized

storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriter.java
[Performance Optimization] Improve the speed of writing index file in shuffle server
When I test uniffle performance, i found a huge performance drop due to the low speed of writing index file. 
After using "dataOutputStream = new DataOutputStream(new BufferedOutputStream(fileOutputStream))" in LocalFileWriter, the performance has great imrpovement.
No
No need.
=> [Performance Optimization] Improve the speed of writing index file in shuffle server

coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
Useless multiple build Configuration 
Reduce consumption
No
Unit test
=> [MINOR][IMPROVEMENT] Avoid CoordinatorServer#initialization multiple `new Configuration()`

common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java, integration-test/common/src/test/java/org/apache/uniffle/test/AssignmentServerNodesNumberTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/DiskErrorToleranceTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/HealthCheckCoordinatorGrpcTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/MultiStorageFaultToleranceTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHdfsTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemoryTest.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/RepartitionWithHdfsMultiStorageRssTest.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/RepartitionWithMemoryMultiStorageRssTest.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/RepartitionWithMemoryRssTest.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManager.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/SparkSQLWithDelegationShuffleManagerFallback.java, server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java, server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java, server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java, server/src/test/java/org/apache/uniffle/server/HealthCheckTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerConfTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java, server/src/test/java/org/apache/uniffle/server/StorageCheckerTest.java, server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java, server/src/test/java/org/apache/uniffle/server/storage/HdfsStorageManagerTest.java, server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java, server/src/test/java/org/apache/uniffle/server/storage/MultiStorageManagerTest.java
Make the conf of rss.storage.basePath as list
Follow up the PR #9 
No
No need
=> Make the conf of rss.storage.basePath as list

README.md, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java, docs/coordinator_guide.md
[DOC] Migrate the coordinator doc from README to docs page
The dedicated doc page will benefit users to find configs
No
No need
=> [DOC] Migrate the coordinator doc from README to docs page

common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java, common/src/main/java/org/apache/uniffle/common/rpc/GrpcServer.java, common/src/main/java/org/apache/uniffle/common/rpc/MonitoringServerTransportFilter.java, common/src/test/java/org/apache/uniffle/common/GrpcServerTest.java, coordinator/src/test/java/org/apache/uniffle/coordinator/CoordinatorMetricsTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcServerTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
Introduce more grpc server metrics
1. grpc_server_executor_active_threads
2. grpc_server_executor_blocking_queue_size
3. grpc_server_connection_size
Now if the executors size is not enough for handling requests, there is no way to find this problem. And the connection number is need to use the linux command of `nestat` to find. 
So this PR is to introduce these metrics.
No
Unit Tests
=> Introduce more grpc server metrics

integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfos.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java, server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java
There is no need to cache four Map. Introduce a new object, `ShuffleTaskInfo`, to replace `currentTimes`, `commitCounts`, `commitLocks` and `cachedBlockIds`. 
This will be clear and save space.
No.
Passed the ut.
=> [Improvement] Introduce a new class ShuffleTaskInfo

bin/start-coordinator.sh, bin/start-shuffle-server.sh, bin/utils.sh
PID file name with coordinator/shuffle-server tag. 
Once coordinator/shuffle-server process started, the pid file will be generated as 
1. coordinator.pid
2. shuffle-server.pid
Original PID file name is `currentpid`, from which, we can't distinguish between coordiantor and server processes 
And when I writing the service script to control the coordinator/shuffle-server process, I need the pid name which could be bound to its role. 
No
Manual test.
=> PID file name should contains program name

common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java, common/src/test/java/org/apache/uniffle/common/KerberizedHdfs.java
Introduce the retry mechanism when minidfs cluster startup encounter BindException.
To fix the flaky test about kerberos test
No
Not necessary
=> Fix flaky test about kerberos

client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java
[Log-Improvement] Log the newly registered app id
I hope from the coordinator log, I could directly find the newly registered app and manually monitor its state. 
Besides, the appId in uniffle is different from the Yarn appId, it's with the timestamp. So it's better to add the spilt KEY for debugging.
No
Not necessary.
=> [Log-Improvement] Log the newly registered app id

coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
This flaky test of heartbeatTimeoutTest
This flaky test is found on https://github.com/apache/incubator-uniffle/runs/8244850538?check_suite_focus=true. 
No
No
=> Fix flaky test of heartbeatTimeoutTest

DISCLAIMER, pom.xml
Add DISCLAIMER
ASF podding
No
No need.
=> Add DISCLAIMER

DISCLAIMER
Fix incubating issues and modify the format of DISCLAIMER
consistent with other ASF incubating projects
No
No need.
=> [Minor] Modify the format of DISCLAIMER

README.md
Add "total lines", "code quality" and "license" badges in README.
To show more insight of the project.
No.
See https://github.com/kaijchen/incubator-uniffle/tree/badges#apache-uniffle-incubating
=> Add more badges in README

internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, storage/src/main/java/org/apache/uniffle/storage/util/ShuffleStorageUtils.java
Fix warnings reported by lgtm.
https://lgtm.com/projects/g/apache/incubator-uniffle/?mode=list
No.
By CI.
=> [MINOR] Fix warnings reported by lgtm

bin/start-coordinator.sh, bin/start-shuffle-server.sh
Output the stderr and stdout to output file in startup script
I found it cause some netty exception logs output to the console due to lacking this PR. It's better to collect these uncaught logs into file and will be helpful to diagnose.
No
No need.
=> Output the stderr and stdout to output file in startup script

bin/start-shuffle-server.sh
Modify environment variable
throw unbound variable error
No
Manual test
=> Fix startup shell problem

.github/PULL_REQUEST_TEMPLATE
Correct the contributing guide link in pull-request template
Correct the contributing guide link in pull-request template
No
Dont need
=> Correct the contributing guide link in pull-request template

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, integration-test/spark-common/src/test/java/org/apache/uniffle/test/TestUtils.java, integration-test/spark2/src/test/java/org/apache/uniffle/test/GetReaderTest.java, integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java
Follow issue#154, When the RDD is Empty, partitionNum is 0, return the empty RssShuffleHandle directly
If the requested shuffle Server is 0, there is no need to request a coodinator.
No.
UT
=> [ISSUE-154][Improvement] Support Empty assignment to Shuffle Server

coordinator/src/main/java/org/apache/uniffle/coordinator/AbstractAssignmentStrategy.java, coordinator/src/main/java/org/apache/uniffle/coordinator/PreferDiffHostAssignmentStrategy.java
Fix typo of PreferDiffHostAssignmentStrategy
=> Fix typo of PreferDiffHostAssignmentStrategy

client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java, client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriterBuffer.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java, common/src/main/java/org/apache/uniffle/common/filesystem/HadoopFilesystemProvider.java, common/src/main/java/org/apache/uniffle/common/metrics/GRPCMetrics.java, common/src/main/java/org/apache/uniffle/common/rpc/MonitoringServerTransportFilter.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorConf.java, integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcServerTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java, internal-client/src/main/java/org/apache/uniffle/client/factory/CoordinatorClientFactory.java, server/src/main/java/org/apache/uniffle/server/HealthCheck.java, server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, server/src/main/java/org/apache/uniffle/server/storage/HdfsStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/MultiStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/StorageManager.java, server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java, server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java, storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java, storage/src/main/java/org/apache/uniffle/storage/util/ShuffleStorageUtils.java
tweaks some wording, fixes some typos and removes some dead code
Better code quality
No
Existing UTs.
=> [Improvement] Small refactor for code quality

storage/src/main/java/org/apache/uniffle/storage/handler/impl/MultiReplicaClientReadHandler.java
Fix incorrect block info statistics after read finished
It is bug introduce by #395 
No
No need
=> [BUG] Fix incorrect block info statistics after read finished

storage/src/main/java/org/apache/uniffle/storage/api/FileWriter.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsFileWriter.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriter.java
[Minor][Improvement] Introduce FileWriter interface for Localfile/HDFS file writer
1. To keep consistent with the interface of `FileReader` for Localfile/HDFS file reader.
No
Don't need
=> [Minor][Improvement] Introduce FileWriter interface for Localfile/HDFS file writer

.github/workflows/parallel.yml, README.md, integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java, pom.xml
1. Add maven profile `spark3.3`
2. Enable tests for Spark 3.3 in CI
3. Fix broken tests
#461 
No.
https://github.com/kaijchen/incubator-uniffle/actions/runs/3879507232
=> [ISSUE-461] Support Spark 3.3

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java, common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java, storage/src/main/java/org/apache/uniffle/storage/common/LocalStorageMeta.java
Improve readability by replacing lambda with method reference.
Fixes #487
No.
Existing CI.
=> [Minor] Improve readability by replacing lambda with method reference

docs/server_guide.md
Add doc about huge partitions
Guide for users
No
Don't need
=> [ISSUE-378][HugePartition][Part-4] Supplement doc about huge partitions

coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/AppBalanceSelectStorageStrategyTest.java, coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java
1. The way to write mini hdfs has been removed, which is consistent with `AppBalanceSelectStorageStrategyTest`. 
2. Closing the scheduling thread for writing the hdfs file.
3.  Using `CountDownLatch` instead of `thread.join()`.
To resolve #526 
No.
Fix ut.
=> Flaky Test: LowestIOSampleCostSelectStorageStrategyTest#selectStorageTest

.asf.yaml
Remove commiters from collaborators
Xianjing Feng became our commiter, let us remove him from collaborators.
No
No need
=> [MINOR] Remove commiters from collaborators

client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/EventFetcherTest.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
Fix misuse of `assert` in tests.
Fix typo in test name of `EventFetcherTest`.
Improve code quality.
No.
CI.
=> [MINOR] test: fix assertion in tests

client-mr/pom.xml, client-spark/common/pom.xml, client-spark/spark2/pom.xml, client-spark/spark3/pom.xml, client/pom.xml, common/pom.xml, coordinator/pom.xml, deploy/kubernetes/pom.xml, integration-test/common/pom.xml, integration-test/mr/pom.xml, integration-test/spark-common/pom.xml, integration-test/spark2/pom.xml, integration-test/spark3/pom.xml, internal-client/pom.xml, pom.xml, proto/pom.xml, server/pom.xml, storage/pom.xml
Update version to 0.8.0-SNAPSHOT
For next release
No
Don't need
=> [#611] chore: update project version to 0.8.0-SNAPSHOT

.github/workflows/build.yml
Fix a typo in build.yml
Follow up of #631
No.
Verified by another github action.
=> [#626][FOLLOWUP] chore(ci): fix typo in build.yml

README.md
Update the project introduction in README.
It is derived from the [Uniffle Proposal][1], hope it introduces the project better.
[1]: https://cwiki.apache.org/confluence/display/INCUBATOR/UniffleProposal
No.
No need.
=> [MINOR] docs: update the project introduction in README

.github/ISSUE_TEMPLATE/flaky-test-report.yml
Remove field Parent issue.
We can't use this template now for the value of this field is empty.
No.
No need.
=> [MINOR] docs: fix flaky-test-report.yml

common/src/main/java/org/apache/uniffle/common/util/Constants.java, server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java, server/src/test/java/org/apache/uniffle/server/StorageCheckerTest.java
Filter no space exception in checkStorageReadAndWrite
Fix: #675 
No.
UT
=> [#675] fix: filter no space exception in checkStorageReadAndWrite

common/src/main/java/org/apache/uniffle/common/security/HadoopSecurityContext.java, coordinator/pom.xml, coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/metric/CoordinatorMetrics.java, coordinator/src/test/java/org/apache/uniffle/coordinator/ClientConfManagerTest.java, coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java
Add metrics for `QuotaManager` to record the number of apps run by each user.
Fix: #671
No.
New uts.
=> [#671] feat(coordinator): Metrics of the number of apps submitted by users

storage/src/main/java/org/apache/uniffle/storage/common/DefaultStorageMediaProvider.java
use the naive equals method to avoid introducing additional dependencies
Fix: #697 
No.
Don't need
=> [#697] fix: use the naive equals method to avoid introducing additional dependencies

coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorServer.java
Add  method `close` for ApplicationManager
Clean resources while testing. It will improve the stability of our test.
No.
GA passed
=> [MINOR] fix: Add  method `close` for ApplicationManager

client-mr/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, common/src/main/java/org/apache/uniffle/common/ClientType.java, common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java, common/src/test/java/org/apache/uniffle/common/ShuffleServerInfoTest.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/test/java/org/apache/uniffle/coordinator/ServerNodeTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/AssignmentWithTagsTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/PartitionBalanceCoordinatorGrpcTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ServletTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java, internal-client/src/main/java/org/apache/uniffle/client/factory/ShuffleServerClientFactory.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssSendHeartBeatRequest.java, proto/src/main/proto/Rss.proto, server/src/main/java/org/apache/uniffle/server/RegisterHeartBeat.java, server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java
Add Netty port information for Shuffle Server
Let us can use old servers with Grpc and new servers with Netty at the same time.
No.
Add new ut
=> [#711] feat(netty): Add Netty port information for Shuffle Server

client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
update log level from INFO to DEBUG to avoid noisy
To avoid too much log in spark executor's log file.
No.
Don't need
=> [MINOR] improvement(client): update log level from INFO to DEBUG to avoid noisy

common/src/test/java/org/apache/uniffle/common/KerberizedHdfs.java, common/src/test/java/org/apache/uniffle/common/KerberizedHdfsBase.java
Reverts apache/incubator-uniffle#721
=> Revert "[MINOR] test: fix tempdir leak in KerberizedHdfs tests"

client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, common/src/main/java/org/apache/uniffle/common/exception/RssException.java, common/src/main/java/org/apache/uniffle/common/exception/RssFetchFailedException.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/ComposedClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryClientReadHandler.java
1. add a new exception called RssFetchFailedException
2. it's used in various instance creation
Fix: #750
No.
Existing UTs.
=> [#750] feat: add RssFetchFailedException

.asf.yaml
Remove committers from collaborators.
Jingxiong Zhong become our committer, we remove him form collaborators.
No.
No need
=> [MINOR] chore: Remove committers from collaborators

client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java, common/src/main/java/org/apache/uniffle/common/ShuffleBlockInfo.java, common/src/main/java/org/apache/uniffle/common/netty/FrameDecoder.java, common/src/main/java/org/apache/uniffle/common/netty/MessageEncoder.java, common/src/main/java/org/apache/uniffle/common/netty/TransportFrameDecoder.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/Decoders.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/Encoders.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/Message.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/RpcResponse.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/SendShuffleDataRequest.java, common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java, common/src/test/java/org/apache/uniffle/common/netty/EncoderAndDecoderTest.java, common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTest.java, common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTestUtils.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHdfsTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemoryTest.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Add Netty Encoder and Decoder. Add `SendShuffleDataRequest` protocol for tests. Other protocols will be added by following prs.
For #133 
No.
UTs.
=> [#133] feat(netty): Add Encoder and Decoder.

README.md
We modify the structure of directory and we should modify the descrition
Modify the description of directory
No.
No
=> [MINOR] fix: the description of Spark patches in the README.md

docs/client_guide.md
Remove unnecessary symbols.
fix:
No.
No need.
=> [MINOR] Modify MD format

common/src/main/java/org/apache/uniffle/common/ShuffleDataDistributionType.java, common/src/main/java/org/apache/uniffle/common/netty/DecodeException.java, common/src/main/java/org/apache/uniffle/common/netty/EncodeException.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/Decoders.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/Encoders.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetLocalShuffleDataRequest.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetLocalShuffleDataResponse.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetLocalShuffleIndexRequest.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetLocalShuffleIndexResponse.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetMemoryShuffleDataRequest.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/GetMemoryShuffleDataResponse.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/RequestMessage.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/RpcResponse.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/SendShuffleDataRequest.java, common/src/main/java/org/apache/uniffle/common/util/ByteBufUtils.java, common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTest.java, common/src/test/java/org/apache/uniffle/common/netty/protocol/NettyProtocolTestUtils.java
Rewrite protocol.
For netty replace grpc.
No.
UTs.
=> [#133] feat(netty): Rewrite protocol.

storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandler.java
We support to read off heap data in the #806, we support to read index in this pr.
#596 follow up pr
No.
GA passed.
=> [#596][FOLLOWUP] Index data support offheap read

.github/workflows/parallel.yml, .github/workflows/sequential.yml
Add the pipeline of Tez
We should verify the code of Tez
No.
No need.
=> [MINOR] chore(ci): Add Tez pipeline

storage/src/main/java/org/apache/uniffle/storage/handler/impl/DataSkippableReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/HdfsShuffleReadHandler.java
just add overwrite key word
Better code.
No.
compile ok
=> [MINOR] refactor: Add overwrite annotation

README.md, build_distribution.sh
- Update document, including the supported mapReduce version and build command.
- Update build_distribution.sh. We can't recognize the hadoop version from final package name for now. We should update the final package name.
=> [MINOR] docs: update document and build script for Hadoop-3.2

client-tez/src/main/java/org/apache/tez/common/InputContextUtils.java, client-tez/src/test/java/org/apache/tez/common/InputContextUtilsTest.java
Get parameter from Inputcontext and then provide util function
Fix: https://github.com/apache/incubator-uniffle/issues/872
No.
unit test
=> [#872] feat(tez): Get parameter from Inputcontext then provide util function

client-tez/src/main/java/org/apache/tez/common/IdUtils.java, client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java, client-tez/src/main/java/org/apache/tez/common/TezRemoteShuffleUmbilicalProtocol.java, client-tez/src/test/java/org/apache/tez/common/IdUtilsTest.java, client-tez/src/test/java/org/apache/tez/common/RssTezUtilsTest.java
modify utils and add test case
Fix: #872 
No.
unit test
=> [#872][FOLLOWUP] feat(tez): Modify utils and add test case

client-tez/src/main/java/org/apache/tez/common/UmbilicalUtils.java
Add UmbilicalUtils to get Worker info from AM
Fix: https://github.com/apache/incubator-uniffle/issues/872
No.
unit test
=> [#872][FOLLOWUP] feat(tez): Add UmbilicalUtils to get Worker info from AM

client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBuffer.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssTezPerPartitionRecord.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssTezSpillRecord.java, client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/impl/RssSorterTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/impl/RssTezPerPartitionRecordTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/output/OutputTestHelpers.java, client-tez/src/test/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutputTest.java
support tez write OrderedPartitionedKVOutput
Fix:#855
No.
UT
=> [#855] feat(tez): Support Tez Output OrderedPartitionedKVOutput

client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffle.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleTest.java
add RssShuffle to handle event and generate fetch task
Fix:  https://github.com/apache/incubator-uniffle/issues/854
No.
unit test, we will push test case in this PR
=> [#854][FOLLOWUP] feat(tez): Add RssShuffle to handle event and generate fetch task

client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssTezFetcherTask.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManagerTest.java
Add RssShuffleManager to run and manager shuffle work
Fix: https://github.com/apache/incubator-uniffle/issues/854
No.
unit test
=> [#854][FOLLOWUP] feat(tez): Add RssShuffleManager to run and manager shuffle work

coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ClientConfManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java, coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/access/checker/AccessClusterLoadChecker.java, coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/BasicAssignmentStrategy.java, coordinator/src/main/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategy.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/servlet/DecommissionServlet.java, coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java
While reading the code and completing the PR, I came across some log messages in the coordinator module that use string concatenation. We are already using slf4j, and it would be better to use placeholder syntax.
log format.
No.
=> [#961] refactor(coordinator):  Improve Coordinator Log Format.

client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java, client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java, client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java, client-tez/src/test/resources/log4j.properties
A method to support remote shuffle for tez framework.
test in real cluster and integration test.
=> [#965] feat(tez): support remote shuffle for tez framework

README.md, docs/client_guide.md
update document for tez client plugin.
=> [MINOR] docs: update document for tez client plugin.

.asf.yaml
Add new collaborators:
@summaryzb
@cchung100m
@slfan1989
@yl09099
Collaborators can run the workflow without committer's approval and manage issues.
They have contributed some features and improvements.  It will be more convenient for them to become collaborators.
No.
No need.
=> [MINOR] Add new collaborators

README.md, build_distribution.sh
update the document and scripts of build tez.
=> [MINOR] docs: update the document and scripts of build tez.

.asf.yaml
Add new collaborator:
@bin41215 
Collaborators can run the workflow without committer's approval and manage issues.
They have contributed some features and improvements.  It will be more convenient for them to become collaborators.
No.
No need.
=> [MINOR] Add new collabrator

NOTICE-binary
I unzip the all the jars of release binary. I append all the `NOTICE` files in the `META-INF`.
Fix: #1043 
No.
No need.
=> [#1043] chore: Add NOTICE-binary

.github/workflows/parallel.yml, README.md, integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java, pom.xml
1. Add maven profile `spark3.4`
2. Enable tests for Spark 3.4 in CI 
3. Fix broken tests
https://github.com/apache/incubator-uniffle/issues/1006
No.
Pass Test
=> [#1006] feat(spark): Support Spark 3.4

docs/client_guide.md
Add the document for tez-client.
Fix: #1124 
No.
=> [#1124] docs: Add the document for tez-client

docs/client_guide.md
Add the document of config option `tez.rss.client.send.thread.num `
Fix: #1124 
No.
=> [#1124] docs(tez): Add the document of config option `tez.rss.client.send.thread.num `

client-mr/core/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, client-mr/core/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java, integration-test/mr/src/test/java/org/apache/uniffle/test/DynamicConfTest.java, integration-test/mr/src/test/java/org/apache/uniffle/test/HadoopConfTest.java, integration-test/mr/src/test/java/org/apache/uniffle/test/MRIntegrationTestBase.java, integration-test/mr/src/test/java/org/apache/uniffle/test/SecondarySortTest.java, integration-test/mr/src/test/java/org/apache/uniffle/test/WordCountTest.java
Ensure configurations in both mapred-site.xml and dynamic_client.conf take effect.
Fix: #1051
No.
tested in our cluster
=> [#1051] fix(mr): Ensure configurations in both mapred-site.xml and dynamic_client.conf take effect.

common/src/main/java/org/apache/uniffle/common/ShuffleDataResult.java, common/src/main/java/org/apache/uniffle/common/ShuffleIndexResult.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
Release buffer when since the buffer have copied to data of reply.
Fix: #1152
No.
Test in cluster manually.
=> [#1152] fix: Direct memory may leak in shuffle server.

client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java
Fix some spelling mistakes.
Fix some spelling mistakes.
No.
No need.
=> [#1165][FOLLOWUP] Fix some spelling mistakes.

cli/pom.xml, client-mr/core/pom.xml, client-mr/hadoop2.8/pom.xml, client-mr/hadoop3.2/pom.xml, client-spark/common/pom.xml, client-spark/spark2/pom.xml, client-spark/spark3/pom.xml, client-tez/pom.xml, client/pom.xml, common/pom.xml, coordinator/pom.xml, deploy/kubernetes/pom.xml, integration-test/common/pom.xml, integration-test/mr/pom.xml, integration-test/spark-common/pom.xml, integration-test/spark2/pom.xml, integration-test/spark3/pom.xml, integration-test/tez/pom.xml, internal-client/pom.xml, pom.xml, proto/pom.xml, server/pom.xml, storage/pom.xml
upgrade to 0.9.0-snapshot
Release 0.8.0
No.
No need.
=> upgrade to 0.9.0-snapshot

.github/workflows/build.yml, .github/workflows/rust.yml, .gitignore, rust/experimental/server/Cargo.toml, rust/experimental/server/src/main.rs
create basic folder for rust-based shuffle server for uniffle
For #1206 
No.
Needn't
=> [#1206][part-1] feat(rust): create basic folder for rust-based shuffle server

.github/workflows/parallel.yml, README.md, pom.xml
1. Add maven profile `spark3.5`
2. Enable tests for Spark 3.5 in CI
https://github.com/apache/incubator-uniffle/issues/1083
No.
Pass Test
=> feat(spark): Support Spark 3.5

README.md, patch/spark/spark-3.3.1_dynamic_allocation_support.patch
Add the dynamic allocation patch for Spark 3.3
https://github.com/apache/incubator-uniffle/issues/1084
No.
Manual test
=> [Improvement] Add dynamic allocation patch for Spark 3.3

README.md, patch/spark/spark-3.4.1_dynamic_allocation_support.patch
Add the dynamic allocation patch for Spark 3.4
https://github.com/apache/incubator-uniffle/issues/1085
No.
Manual test
=> feat: Add dynamic allocation patch for Spark 3.4

deploy/kubernetes/operator/Makefile
Use a fixed version instead of latest version.
Fix the ci error of master branch
No.
CI passed.
=> [MINOR] chore(ci): Fix K8S CI pipeline

patch/spark/spark-3.0.1_dynamic_allocation_support.patch
Add the dynamic allocation patch for Spark 3.0
https://github.com/apache/incubator-uniffle/issues/1088
No.
Manual test spark
=> [#1088] feat(spark): Add dynamic allocation patch for Spark 3.0

README.md, patch/spark/spark-2.3.4_dynamic_allocation_support.patch
Add the dynamic allocation patch for Spark 2.3
https://github.com/apache/incubator-uniffle/issues/1089
No.
Manual local test
=> [#1089] feat(spark): Add dynamic allocation patch for Spark 2.3

integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
Fix test
Fix: #244 
No.
unit test
=> [#244][FOLLOWUP] test: CoordinatorGrpcTest.rpcMetricsTest.

server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
As title
Fix: https://github.com/apache/incubator-uniffle/issues/1252
No.
unit test
=> [#1252] fix(server): Incorrect storage write fail metric

server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Add RemoveResourceTime Metric
For monitor time used by RemoveResourceTime method
Fix: https://github.com/apache/incubator-uniffle/issues/1286
No.
=> [#1286] improvement(server): Add RemoveResourceTime Metric

README.md, docs/client_guide.md
Update jar name for spark client
The jar name of spark client had changed
No.
No need.
=> [MINOR] docs: update jar name for spark client

common/src/main/java/org/apache/uniffle/common/util/RssUtils.java
The tips for checking replica settings is a bit unclear.
This tip may be misleading
No
No need
=> [#1330] improvement: optimize tips for checking replica settings

bin/start-dashboard.sh, bin/stop-dashboard.sh, bin/utils.sh
Fix get_pid_file_name function for the dashboard.
This is the follow up pr of  [#1056](https://github.com/apache/incubator-uniffle/pull/1056)
No.
By running the script: start-dashboard.sh and stop-dashboard.sh.
=> [#960][FOLLOWUP] fix(dashboard): Fix get_pid_file_name function for the dashboard.

common/src/main/java/org/apache/uniffle/common/exception/NotRetryException.java, common/src/main/java/org/apache/uniffle/common/util/RetryUtils.java, common/src/test/java/org/apache/uniffle/common/util/RetryUtilsTest.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
fast fail without retry when oom occurs
Fix: #1267 
No.
Existing UTs
=> [#1267] fix(client): fast fail without retry when oom occurs

common/src/main/java/org/apache/uniffle/common/ServerStatus.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java, dashboard/src/main/webapp/src/components/ApplicationPage.vue, dashboard/src/main/webapp/src/components/ShuffleServerPage.vue, dashboard/src/main/webapp/src/components/shufflecomponent/ActiveNodeListPage.vue, dashboard/src/main/webapp/src/components/shufflecomponent/DecommissionednodeListPage.vue, dashboard/src/main/webapp/src/components/shufflecomponent/DecommissioningNodeListPage.vue, dashboard/src/main/webapp/src/components/shufflecomponent/ExcludeNodeList.vue, dashboard/src/main/webapp/src/components/shufflecomponent/LostNodeList.vue, dashboard/src/main/webapp/src/components/shufflecomponent/UnhealthyNodeListPage.vue, dashboard/src/main/webapp/src/utils/common.js, proto/src/main/proto/Rss.proto
1.Fixed a bug that returned data from some interface calls.
2.Modify some memory to be represented in tape units.
The dashboard page cannot display some indicators.
Fix: #960 
No.
Existing UT.
=> [#960][part-4] feat(dashboard): Fix some display bugs and optimize the display format.

cli/pom.xml, client-mr/core/pom.xml, client-mr/hadoop2.8/pom.xml, client-mr/hadoop3.2/pom.xml, client-spark/common/pom.xml, client-spark/spark2-shaded/pom.xml, client-spark/spark2/pom.xml, client-spark/spark3-shaded/pom.xml, client-spark/spark3/pom.xml, client-tez/pom.xml, client/pom.xml, common/pom.xml, coordinator/pom.xml, deploy/kubernetes/pom.xml, integration-test/common/pom.xml, integration-test/mr/pom.xml, integration-test/spark-common/pom.xml, integration-test/spark2/pom.xml, integration-test/spark3/pom.xml, integration-test/tez/pom.xml, internal-client/pom.xml, pom.xml, proto/pom.xml, server/pom.xml, storage/pom.xml
bump project version to 0.8.1-SNAPSHOT
Prepare for 0.8.1
No.
No need
=> [MIMOR][0.8] chore: bump project version to 0.8.1-SNAPSHOT

client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
fix the incorrect partitionId
Fix: # (issue)
No.
Neen't
=> [MINOR] chore(client): fix the incorrect partitionId

client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java, client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcServiceTest.java
To fix IndexOutOfBoundsException.
For [#1420](https://github.com/apache/incubator-uniffle/issues/1420)
No.
Rerun successfully.
=> [#1420] fix(client): reportShuffleWriteFailure failed because of IndexOutOfBoundsException

.gitignore, rust/experimental/server/Cargo.lock, rust/experimental/server/Cargo.toml, rust/experimental/server/README.md, rust/experimental/server/src/store/hybrid.rs, rust/experimental/server/src/store/local/disk.rs, rust/experimental/server/src/store/local/mod.rs, rust/experimental/server/src/store/localfile.rs, rust/experimental/server/src/store/mod.rs
1. using `opendal` crate to simplify read/write
2. avoid using dashmap.get to fix potential deadlock
For: #1407
No.
Unit tests
=> [#1407] feat(rust): refactor localfile store to speed up writing

server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Fix SC_START_IN_CTOR from SpotBugs suggestion.
Fix SC_START_IN_CTOR from SpotBugs suggestion.
Fix: #532
No.
unit test
=> [#532] SpotBugs: Fix SC_START_IN_CTOR

internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
1、Refactor the method `ShuffleServerGrpcClient.requirePreAllocation`, calling `getBlockingStub().requireBuffer` only once.
2、Try-catch `getBlockingStub().requireBuffer`'s exception, log the error, and return `FAILED_REQUIRE_ID`.
3、Refactor the log to make it more appropriate.
For [#1456](https://github.com/apache/incubator-uniffle/issues/1456)
No.
Existing UTs.
=> [#1456] improvement(client): Better exception handling when calling requireBuffer using GRPC

server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java, server/src/main/java/org/apache/uniffle/server/buffer/PreAllocatedBufferInfo.java
improve expired buffers metric and log
Once the expired buffer happened, it means the server or client may have problems, 
we should find out the related apps by the log shown in the server
For #1356 
No.
Existing tests
=> [#1356] feat(server): improve expired buffers metric and log

rust/experimental/server/src/app.rs, rust/experimental/server/src/grpc.rs, rust/experimental/server/src/metric.rs, rust/experimental/server/src/store/hdfs.rs, rust/experimental/server/src/store/hybrid.rs, rust/experimental/server/src/store/local/disk.rs, rust/experimental/server/src/store/localfile.rs, rust/experimental/server/src/store/memory.rs, rust/experimental/server/src/store/mod.rs
1. feat(rust): add more metrics about local disk and reading
2. feat(rust): support topN app data size
Fix: #1407
No.
Unit tests
=> [#1407] feat(rust): support metrics about disk and topN data size

client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java
Improves the wording on blockId structure.
I found the existing comment ambiguous and had to carefully look into the code.
No.
Only changes in comments.
=> [MINOR] docs: Improve comment on blockId structure

client-mr/core/pom.xml, client-spark/spark2-shaded/pom.xml, client-spark/spark3-shaded/pom.xml, client-tez/pom.xml, pom.xml
Upgrade Netty and GRPC
A sub PR for: https://github.com/apache/incubator-uniffle/pull/1519
No.
Existing UTs.
=> [#1472][part-1] fix(server): Upgrade Netty and GRPC

.github/workflows/parallel.yml, .github/workflows/sequential.yml, .github/workflows/single.yml
Improves how dashboard is build and tested in the Github CI.
Changes in #1498 were not considering the actual state of dashboard within the Maven project.
No.
CI.
=> [MINOR] fix(CI): Improve dashboard across the CI

rust/experimental/server/README.md
add cpu profile doc
Subtask for  #1407
No.
Needn't
=> [#1407] chore(rust): add cpu profile doc

rust/experimental/server/src/grpc.rs, rust/experimental/server/src/metric.rs
1. fix grpc queue size metric 
2. add total grpc request metrics
For #1407
No.
Needn't
=> [#1407] feat(rust): fix + add total grpc request metrics

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
fix partition id type is incorrect
Fix: (#1373)
No.
Not necessary.
=> [#1373][followup] fix(client):Fix partition id type is incorrect

server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
1. Send failed responses only when the channel is writable.
2. Print debug logs when the data is successfully sent, reducing log output.
3. Reduce the duplicated error log.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1605.
No.
Existing UTs.
=> [#1596][FOLLOWUP] fix(netty): Send failed responses only when the channel is writable

client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssBypassWriter.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssInMemoryRemoteMerger.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssRemoteMergeManagerImpl.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java, client-mr/core/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, client-mr/hadoop2.8/src/main/java/org/apache/uniffle/hadoop/shim/HadoopShimImpl.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssShuffleManager.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/RssSimpleFetchedInputAllocator.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffle.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssShuffleScheduler.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RssTezShuffleDataFetcher.java, client-tez/src/main/java/org/apache/tez/runtime/library/input/RssConcatenatedMergedKeyValueInput.java, client-tez/src/main/java/org/apache/tez/runtime/library/input/RssConcatenatedMergedKeyValuesInput.java, common/src/main/java/org/apache/uniffle/common/ShuffleServerInfo.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/request/ApplicationRequest.java, coordinator/src/test/java/org/apache/uniffle/coordinator/conf/YamlClientConfParserTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHadoopTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezSimpleSessionExampleTest.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerConf.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
1. Remove meaningless string concatenation.
2. Use slf4j instead of apache commons logging.
Better readablity and performance, and reduce maintenance complexity.
No.
Existing UTs.
=> [MINOR] Remove meaningless string concatenation

README.md
Update `README.md`.
A follow-up PR for: https://github.com/apache/incubator-uniffle/pull/1650.
Easier for users to find out the performance report.
No.
Unnecessary.
=> [#1607][FOLLOWUP] docs(benchmark): Performance report with partial TPC-DS(SF=40000) queries

server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java
Fix the issue of log variable printing.
Cherry pick commits https://github.com/apache/incubator-uniffle/pull/1643 and https://github.com/apache/incubator-uniffle/pull/1648 from master to branch-0.9.
No.
Unnecessary.
=> [#1459][0.9][FOLLOWUP] fix(server): Fix the issue of log variable printing

server/src/test/java/org/apache/uniffle/server/storage/LocalStorageManagerTest.java
Fix tests which may be flaky on different machines.
Fix: https://github.com/apache/incubator-uniffle/issues/1675.
No.
Unnecessary.
=> [#1675] fix(test): Fix tests which may be flaky on different machines

server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Introduce localfile isWritable metric
For #1682
No.
=> [#1682] feat(server): Introduce localfile isWritable metric

pom.xml
Bump gRPC from 1.61.1 to v1.63.0.
Fix: https://github.com/apache/incubator-uniffle/issues/1703.
No.
Existing UTs.
=> [#1703] improvement(server): Bump gRPC from 1.61.1 to 1.63.0

integration-test/common/pom.xml, integration-test/mr/pom.xml, integration-test/spark-common/pom.xml, integration-test/tez/pom.xml
Increase tests running memory for better stability.
Fix: https://github.com/apache/incubator-uniffle/issues/1698.
No.
Unnecessary.
=> [#1698] fix(test): Increase tests running memory for better stability

pom.xml
Bump gRPC from 1.63.0 to 1.64.0.
Fix: https://github.com/apache/incubator-uniffle/issues/1731.
No.
Existing UTs.
=> [#1731] improvement(server): Bump gRPC from 1.63.0 to 1.64.0

common/src/main/java/org/apache/uniffle/common/ReconfigurableConfManager.java
Avoid outputing too much incorrect non-update logs
follow up #1711
No.
Yes
=> [#1711][FOLLOWUP] fix(server): Avoid outputing too much incorrect non-update logs

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, server/src/main/java/org/apache/uniffle/server/LocalStorageChecker.java
Add exception handling for thread pools.
Fix: https://github.com/apache/incubator-uniffle/issues/1743.
No.
Existing UTs.
=> [#1743] fix: Add exception handling for thread pools

server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
Fix incorrect request to make output too much logs
Followup for #1755 
No.
Needn't
=> [#1755][FOLLOWUP] fix(server): Incorrect request info to output too much logs

docs/coordinator_guide.md
Correct the example of decommission interface
The document content is incorrect.
No.
No need.
=> [MINOR] fix(docs): Correct the example of decommission interface

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/BufferManagerOptions.java
Address https://github.com/apache/incubator-uniffle/pull/1789#discussion_r1639312935
No.
minor fix
=> [MINOR] refactor: Check debug enabled

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
support gluten
Currently, gluten will fail to compile using client from the master branch of uniffle.
Fix: #1751 
No.
Existing UTs and manual testing
=> [#1751][0.9] improvement: support gluten

client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java, client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerInterface.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java, client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/DummyRssShuffleManager.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java, client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssGetShuffleAssignmentsRequest.java, proto/src/main/proto/Rss.proto
Take more infos on get assignment to track app reassign/stageRetry
For #1791 
No.
Existing tests
=> [#1791] feat(spark)(coordinator): Take more infos on get assignment to track app reassign/stageRetry

internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java
Print received Netty ByteBuf's readable bytes in clients.
For: https://github.com/apache/incubator-uniffle/issues/1811.
No.
Existing UTs.
=> [#1811] improvement(netty): Print received Netty ByteBuf readable bytes in clients

.github/workflows/build.yml, .github/workflows/parallel.yml, integration-test/common/src/test/resources/log4j2.xml, integration-test/mr/src/test/resources/log4j2.xml, integration-test/spark-common/src/test/resources/log4j2.xml, integration-test/spark2/src/test/resources/log4j2.xml, integration-test/spark3/src/test/resources/log4j2.xml, integration-test/tez/src/test/resources/log4j2.xml
Upload failed integration test logs of GA.
Convenient troubleshooting of flaky tests.
Fix: #1834.
No.
Existing UTs.
=> [#1834] improvement(test): Upload failed integration test logs of GA

server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Add block counter for SKIP_LIST buffer.
The performance of getting the size of skip-list is not good.
Fix: #1809
No.
Existing UT.
=> [#1809] fix(server): add block counter for SKIP_LIST buffer

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
support gluten
Currently, gluten will fail to compile using client from the master branch of uniffle.
Fix: https://github.com/apache/incubator-uniffle/issues/1751
No.
Existing UTs and manual testing
=> [#1751] improvement: support gluten again

bin/start-dashboard.sh
The script startup parameters are outdated when the dashboard is booted with an advanced JDK version.
The issues are as follows：
[0.001s][warning][gc] -XX:+PrintGC is deprecated. Will use -Xlog:gc instead.
[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
-XX:ConcGCThreads=5 -XX:G1ConcRefinementThreads=20 -XX:GCDrainStackTargetSize=64 -XX:+IgnoreUnrecognizedVMOptions -XX:InitialHeapSize=42949672960 -XX:InitiatingHeapOccupancyPercent=45 -XX:MaxGCPauseMillis=200 -XX:MaxHeapSize=42949672960 -XX:ParallelGCThreads=20 -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCDetails -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseG1GC
Fix: #1401 
No.
Existing UT.
=> [#1401] improvement(dashboard): Make startup scripts support JDK9 or later.

dashboard/src/main/java/org/apache/uniffle/dashboard/web/proxy/WebProxyServlet.java
Fix the bug causing the dashboard to fail to launch.
Fix: #1895
No.
Manually.
=> [#1895] fix(dashboard): Correct dashboard start failed issue

cli/pom.xml, client-mr/core/pom.xml, client-mr/hadoop2.8/pom.xml, client-mr/hadoop3.2/pom.xml, client-spark/common/pom.xml, client-spark/spark2-shaded/pom.xml, client-spark/spark2/pom.xml, client-spark/spark3-shaded/pom.xml, client-spark/spark3/pom.xml, client-tez/pom.xml, client/pom.xml, common/pom.xml, coordinator/pom.xml, dashboard/pom.xml, deploy/kubernetes/pom.xml, integration-test/common/pom.xml, integration-test/mr/pom.xml, integration-test/spark-common/pom.xml, integration-test/spark2/pom.xml, integration-test/spark3/pom.xml, integration-test/tez/pom.xml, internal-client/pom.xml, pom.xml, proto/pom.xml, server/pom.xml, storage/pom.xml
Update version to 0.9.1-SNAPSHOT
Post-release version bump.
No.
Not needed.
=> [#1654] chore: update project version to 0.9.1-SNAPSHOT

common/src/main/java/org/apache/uniffle/common/rpc/StatusCode.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java, proto/src/main/proto/Rss.proto, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java, server/src/main/java/org/apache/uniffle/server/netty/ShuffleServerNettyHandler.java
Fix the npe issue within shuffle server
Fix: #1894
No.
Tested on our test cluster
=> [#1894] fix(server): Fix NPE caused by app not found issue

common/src/main/java/org/apache/uniffle/common/storage/ApplicationStorageInfo.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java, server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/SingleStorageManager.java, storage/src/main/java/org/apache/uniffle/storage/common/AbstractStorage.java, storage/src/main/java/org/apache/uniffle/storage/common/Storage.java
Add some metrics for the shuffle server.
This would be more helpful for us to understand the status of the shuffle server.
Fix: #1903
No.
=> [#1903] improvement(server): Add some metrics for shuffle server

client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
Support reporting more error messages rather than only `Fail to send the block`.
Let users know the error code so users can solve issues by themselves.
No, just output more error messages.
In our env.
=> [MINOR] feat(spark): Support reporting error messages from client

common/src/main/java/org/apache/uniffle/common/records/RecordsReader.java, common/src/main/java/org/apache/uniffle/common/records/RecordsWriter.java, common/src/test/java/org/apache/uniffle/common/records/RecordsReaderWriterTest.java
Provides abstract methods for processing Records.
Fix: #1746
No.
unit test and test in real cluster
=> [#1746] feat(remote merge): Introduce the reader and writer for record.

.github/workflows/build.yml, docs/coordinator_guide.md, docs/dashboard_guide.md, docs/server_guide.md
Add some necessary docs.
Fix: #1905
Yeah, docs page.
No need
=> [#1905][FOLLOWUP] docs: Add documents after introducing XXX_JAVA_OPTS env var

docs/dashboard_guide.md
Fix docs yaml parse error about dashboard_guide.md
Just correct it.
Generate and view docs correctly.
No need.
=> [MINOR] docs: Fix docs yaml parse error about dashboard_guide.md

conf/local_dev/dashboard.conf, dashboard/src/main/java/org/apache/uniffle/dashboard/web/proxy/WebProxyServlet.java, dashboard/src/main/java/org/apache/uniffle/dashboard/web/utils/DashboardUtils.java, dashboard/src/main/webapp/src/api/api.js, dashboard/src/main/webapp/src/pages/CoordinatorServerPage.vue, dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue, dashboard/src/main/webapp/src/utils/http.js
1. Modify NPE bugs;
2. Modify the Vue3's CompositionAPI.
3. Handling the request failed.
4. Optimize page display.
Fix: #1954 
Yes.
UT.
=> [#1927] fix(dashboard): Fix NPE issues in dashboard

coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java, coordinator/src/test/java/org/apache/uniffle/coordinator/SimpleClusterManagerTest.java, dashboard/src/main/webapp/src/api/api.js, dashboard/src/main/webapp/src/pages/serverstatus/ExcludeNodeList.vue, dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
Add the blacklist function from the page.
Fix: #1401 
Yes.
Page click test.
=> [#1401] feat(dashboard): Support adding shuffle servers to the blacklist on the page

common/pom.xml, common/src/main/java-templates/org/apache/uniffle/common/ProjectConstants.java, coordinator/src/main/java/org/apache/uniffle/coordinator/AppInfo.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ApplicationManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/CoordinatorGrpcService.java, coordinator/src/main/java/org/apache/uniffle/coordinator/QuotaManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/AppInfoVO.java, coordinator/src/test/java/org/apache/uniffle/coordinator/QuotaManagerTest.java, dashboard/src/main/webapp/src/pages/ApplicationPage.vue, dashboard/src/main/webapp/src/pages/CoordinatorServerPage.vue, dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue, pom.xml, proto/src/main/proto/Rss.proto
Display version and git commit id in dashboard
The version and git commit id can be used to easily locate whether the component has been upgraded and troubleshoot problems.
User can view version and git commit id from dashboard
Use the latest version, open the dashboard ui, and you can see the version and git commit id on the Coordinator and Shuffle server pages.
Submit a task, and you can see the version and git commit id of each application task in the Apps module on the Application page.
=> [#1977] improvment(dashboard): Add version and git commit id in dashboard

common/pom.xml, coordinator/pom.xml, coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/AppInfoVO.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/CoordinatorConfVO.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/UserAppNumVO.java, pom.xml, server/pom.xml, server/src/main/java/org/apache/uniffle/server/web/vo/ServerConfVO.java
Introduce Lombok
Fix: #1990
No.
CI
=> [#1990] improvement(infra): introduce Lombok

dashboard/src/main/webapp/src/pages/serverstatus/NodeListPage.vue
Combine server table columns in dashboard.
The server table have many columns, it looks to ugly.
Yeah
=> [MINOR] improvement(dashboard): Combine server table columns

coordinator/src/main/java/org/apache/uniffle/coordinator/ClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/SimpleClusterManager.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ServerResource.java, dashboard/src/main/webapp/src/api/api.js, dashboard/src/main/webapp/src/main.js, dashboard/src/main/webapp/src/pages/serverstatus/ExcludeNodeList.vue
1. Provide the page deletion function for blacklist pages.
2. Provide search function for blacklist page.
Fix: #1401 
Yes.
UT.
=> [#1401] feat(dashboard): Support removing excluded servers

client-tez/src/main/java/org/apache/tez/common/ShuffleAssignmentsInfoWritable.java, client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java, client-tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezHashJoinTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezIntegrationTestBase.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezJoinIntegrationTestBase.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezSimpleSessionExampleTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezSortMergeJoinTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountWithFailuresTest.java
Add Netty support for TEZ tasks in Uniffle.
Fix: #1994
Running TEZ tasks with Netty mode is now supported.
Testing has been conducted using the modified integration tests that now support Netty.
=> [#1994] improvement(netty): Add Netty support for TEZ tasks in Uniffle.

dashboard/src/main/webapp/src/components/ApplicationPage.vue
…
Display the human-readable time format in application page.
A long type timestamp really hard to get information from it.
Format the update time to human-readable.
Manual testing
Fix: # (issue)
No.
=> [MINOR] Improvement(dashboard): Support display human-readable time format for app page (#1851)

client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java, client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java, client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java, client/src/main/java/org/apache/uniffle/client/util/RssClientConfig.java, common/src/main/java/org/apache/uniffle/common/config/ConfigOption.java, common/src/main/java/org/apache/uniffle/common/config/ConfigOptions.java, common/src/main/java/org/apache/uniffle/common/config/RssConf.java, common/src/main/java/org/apache/uniffle/common/netty/client/TransportClientFactory.java, common/src/main/java/org/apache/uniffle/common/netty/handle/TransportChannelHandler.java, common/src/main/java/org/apache/uniffle/common/netty/protocol/MessageWithHeader.java, common/src/main/java/org/apache/uniffle/common/web/JettyServer.java, docs/client_guide/mr_client_guide.md, docs/client_guide/tez_client_guide.md, docs/coordinator_guide.md, integration-test/tez/src/test/java/org/apache/tez/dag/app/RssDAGAppMasterForWordCountWithFailures.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountWithFailuresTest.java, server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, storage/src/main/java/org/apache/uniffle/storage/common/FileBasedShuffleSegment.java
There are typo issues within uniffle, it is normal, but we should fix them.
Fix: # (2025)
No.
No need
=> [#2025] fix(all): Fix a batch of typo issue

coordinator/pom.xml, dashboard/pom.xml, pom.xml, server-common/pom.xml, server/pom.xml
Create a  server-common module.
Reduce client-side denpendencies.
No.
No need
=> [MINOR] improvement(all): Create a server-common module to reduce client-side dependencies

docs/index.md, docs/troubleshooting.md
Introduce a document of troubleshooting.
Fix: #2018 
Yes, it introduce a new document.
No
=> [#2018] docs: Add Troubleshooting document

coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java
Correcting Assignment of appCurrent and appTotality
The `appCurrent` stand for the running app count.
The `appTotality` stand for the total app count include running and finished.
`APPS TOTAL` and `APPS CURRENT` swapped.
No need
=> [MINOR] fix(coordinator): Correcting Assignment of appCurrent and appTotality

conf/log4j2.xml, deploy/kubernetes/operator/examples/configuration.yaml, dev/local_dev_template/log4j2.xml
remove console from log4j2.xml
Fix: #2044
No.
test in physical machine
=> [#2044] improvement: Remove console from log4j2.xml.

release/publish_maven_artifacts.sh
Replace mvn with mvnw in publish_maven_artifacts.sh
For consistency.
No.
CI
=> [MINOR] chore: replace mvn with mvnw in publish_maven_artifacts.sh

dashboard/pom.xml, dashboard/src/main/java/org/apache/uniffle/dashboard/web/Dashboard.java, dashboard/src/main/java/org/apache/uniffle/dashboard/web/lombok.config, dashboard/src/main/java/org/apache/uniffle/dashboard/web/resource/DashboardResource.java, dashboard/src/main/java/org/apache/uniffle/dashboard/web/vo/DashboardConfVO.java, dashboard/src/main/webapp/src/api/api.js, dashboard/src/main/webapp/src/components/LayoutPage.vue, dashboard/src/main/webapp/src/pages/DashboardPage.vue, dashboard/src/main/webapp/src/router/index.js
Introduce dashboard page in dashboard web ui to show the version, start time and other information about dashboard.
Fix: #2048
Dashboard UI
=> [#2048] feat(coordinator): Introduce dashboard page in dashboard web ui

server/src/main/java/org/apache/uniffle/server/buffer/AbstractShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
Fix double release issue about clearResource thread
Fix: #1930
No.
No.
=> [#1930] fix(server): Fix a double release issue about clearResource thread

server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java, server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java, server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java
Throws EventRetryException If Exception is encountered during create write handler.
Fix: #2073
No.
CI
=> [#2073] fix(server): throws EventRetryException If Exception is encountered during create write handler

storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileClientReadHandler.java
=> [MINOR] fix(client): Fix the error message for LocalFileClientReadHandler.

client-mr/core/src/test/java/org/apache/hadoop/mapred/SortWriteBufferManagerTest.java, client-mr/core/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java, client-spark/common/src/test/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBaseTest.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/test/java/org/apache/spark/shuffle/RssShuffleManagerTestBase.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java, client/src/main/java/org/apache/uniffle/client/api/ShuffleWriteClient.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, internal-client/src/main/java/org/apache/uniffle/client/factory/CoordinatorClientFactory.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcRetryClient.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/CoordinatorGrpcRetryableClient.java
=> [#2094] feat(client): Introduce retry mechanism for coordinator client

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Fix duplicated blockId cause shuffle server memory leak in netty mode.
Fix: #2105 
No.
=> fix[server] Fix duplicate blockId cause netty memory leak

common/src/main/java/org/apache/uniffle/common/metrics/MetricsManager.java, common/src/main/java/org/apache/uniffle/common/metrics/SupplierGauge.java, server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Refactor SupplierGauge to support generic type and add requireBufferCount metrics
Fix: #1991
Add new metrics named `require_buffer_count`
Tested through dashboard server metrics popup page.
=> [#1991][FOLLOWUP] Refactor SupplierGauge to support generic type and add requireBufferCount metrics

common/src/main/java/org/apache/uniffle/common/web/JettyServer.java, common/src/main/java/org/apache/uniffle/common/web/resource/ConfOpsResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java, dashboard/src/main/java/org/apache/uniffle/dashboard/web/resource/DashboardResource.java, server/src/main/java/org/apache/uniffle/server/web/resource/ServerResource.java
Support a way to updateConf from rest api
To support dynamic update conf.
Yes, supply a rest api.
Tested Locally.
```Console
curl -X POST http://localhost:19978/api/shuffleServer/confOps/update -d "key=rss.server.log.app.detail.while.remove.enabled" -d "value=true"
Set key: rss.server.log.app.detail.while.remove.enabled from 'null' to 'true'%
```
```
[2024-09-23 23:00:13.715] [Jetty-5] [INFO] ConfOpsResource - Dynamic updating rss.server.log.app.detail.while.remove.enabled to true, delete=false
```
=> [#2136] feat:(Server/Coordinator) Support a way to updateConf from rest api

client-tez/pom.xml, client-tez/src/main/java/org/apache/tez/common/GetShuffleServerRequest.java, client-tez/src/main/java/org/apache/tez/common/RssTezConfig.java, client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java, client-tez/src/main/java/org/apache/tez/dag/app/RssDAGAppMaster.java, client-tez/src/main/java/org/apache/tez/dag/app/TezRemoteShuffleManager.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RMRssShuffle.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RMRssShuffleScheduler.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBuffer.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManager.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssSorter.java, client-tez/src/main/java/org/apache/tez/runtime/library/common/sort/impl/RssUnSorter.java, client-tez/src/main/java/org/apache/tez/runtime/library/input/RMRssOrderedGroupedKVInput.java, client-tez/src/main/java/org/apache/tez/runtime/library/output/RssOrderedPartitionedKVOutput.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/RMRssShuffleTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferManagerTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/common/sort/buffer/WriteBufferTest.java, client-tez/src/test/java/org/apache/tez/runtime/library/input/RMRssOrderedGroupedKVInputTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/RMTezOrderedWordCountTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezCartesianProductTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezIntegrationTestBase.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezJoinIntegrationTestBase.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezOrderedWordCountTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/TezWordCountTest.java
Tez support remote merge.
Fix: #1750 
Yes, I will refine documentation in other PR.
unit test, integration test, real job in cluster.
=> [#1750] feat(remote merge): Support Tez.

client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java
Do not unregister repeatedly.
Fix: #2165 
No.
integration test
=> [#2165] fix(client): Fix the exception caused by repeated unregister shuffle in tez tasks.

server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java
=> [#2059][FLOLLOWUP]fix[server] fix spotless error

server/src/main/java/org/apache/uniffle/server/ShuffleServerMetrics.java
Fix spotless issue error
Fix: #2183
No.
CI
=> [#2183] [FOLLOWUP] Fix spotless issue error

client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
set rss.enabled to true in RssShuffleManager
Fix: #2192
No.
=> [#2192] improvement(spark): set rss.enabled to true in RssShuffleManager

server/src/main/java/org/apache/uniffle/server/DefaultFlushEventHandler.java, server/src/main/java/org/apache/uniffle/server/HugePartitionUtils.java, server/src/main/java/org/apache/uniffle/server/ShuffleDataFlushEvent.java, server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java, server/src/main/java/org/apache/uniffle/server/buffer/AbstractShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedList.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java, server/src/main/java/org/apache/uniffle/server/storage/HadoopStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/LocalStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/SingleStorageManager.java, server/src/main/java/org/apache/uniffle/server/storage/hybrid/DefaultStorageManagerSelector.java, server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java, server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java, server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithLinkedListTest.java, server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipListTest.java
Correct the data length and buffer size metrics and logs
Fix: #2154
No
UTs.
=> [#2154] fix: Correct the data length and buffer size metrics and logs

common/src/main/java/org/apache/uniffle/common/merger/StreamedSegment.java, integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTestWhenShuffleFlushed.java, integration-test/mr/src/test/java/org/apache/uniffle/test/RMWordCountTest.java, integration-test/tez/src/test/java/org/apache/uniffle/test/RMTezOrderedWordCountTest.java, server/src/main/java/org/apache/uniffle/server/ShuffleServer.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java, server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferWithSkipList.java, server/src/main/java/org/apache/uniffle/server/merge/Partition.java, server/src/main/java/org/apache/uniffle/server/merge/Shuffle.java, server/src/main/java/org/apache/uniffle/server/merge/ShuffleMergeManager.java, server/src/test/java/org/apache/uniffle/server/merge/ShuffleMergeManagerTest.java
remove cached block for partition.
Fix: #2171 
No.
unit test, integration test.
=> [2171] improvement(remote merge): remove cached block for partition.

common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java, server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java, storage/src/main/java/org/apache/uniffle/storage/common/LocalStorage.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriteHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileWriter.java, storage/src/main/java/org/apache/uniffle/storage/request/CreateShuffleWriteHandlerRequest.java
Support config buffer size for LocalFileWriter
Fix: #2209 
No.
Locally test.
=> [#2209] feat(server): Support config buffer size for LocalFileWriter

server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskInfo.java, storage/src/main/java/org/apache/uniffle/storage/common/AbstractStorage.java, storage/src/main/java/org/apache/uniffle/storage/common/Storage.java, storage/src/main/java/org/apache/uniffle/storage/handler/api/ShuffleWriteHandlerWrapper.java
Add write file quantity info for application. 
Fix: #2203 
No.
Locally
=> [#2203] feat(server) Add write file quantity info for application. 

coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/ApplicationResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/vo/AppInfoVO.java, dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Display the write information of application in dashboard
Fix: #2211 
Yes.
Tested locally.
Related PR: #2208
=> [#2211] feat(dashboard) Display the write information of application in dashboard

server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcMetrics.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerNettyMetrics.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerGrpcMetricsTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleServerMetricsTest.java
add metric for sorted api
Fix: #2174
No.
test in cluster
=> [#2174] feat(remote merge): Add metric for sorted api.

dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Support sortable for totalSize column of applicationPage within dashboard webui
- Easy to find out the biggest application.
No.
Tested Localy
=> [MINOR] improvement(dashboard): Support sortable for totalSize column of applicationPage within dashboard webui

LICENSE
Add the license of tikv/raft-engine
Fix: #2161
No.
No need.
=> [#2161] improvement(core): Add the license of tikv/raft-engine

.github/workflows/rust.yml
Make the test with 1 thread to eliminate flaky test
Currently the rust test cases are not stable
No.
Needn't
=> fix(rust): Make the test with 1 thread to eliminate flaky test

server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java
Support dynamic update the conf of high/low water mark.
It can be easy to tune the server online without restart leverage this.
No.
Tested Locally.
```Console
➜  ~ curl -X POST http://localhost:19948/api/shuffleServer/confOps/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.memory.shuffle.highWaterMark.percentage": "0.5", "rss.server.memory.shuffle.lowWaterMark.percentage": "0.1"}}'
temporarily effective until restart: Update successfully
```
server.log
```
[2024-11-03 21:29:20.660] [Jetty-5] [INFO] ConfOpsResource - Dynamic updating ConfVO{update={rss.server.memory.shuffle.highWaterMark.percentage=0.5, rss.server.memory.shuffle.lowWaterMark.percentage=0.1}, delete=[]}
```
=> [MINOR] improvement(server): Dynamic conf support of server memory watermark

common/src/main/java/org/apache/uniffle/common/web/resource/ConfOpsResource.java, coordinator/src/main/java/org/apache/uniffle/coordinator/web/resource/CoordinatorServerResource.java, server/src/main/java/org/apache/uniffle/server/web/resource/ServerResource.java
Modify the path of update conf rest api
To make it clear to show this is a temp update, do not update the config file.
Path modified to
`http://localhost:19948/api/shuffleServer/confOps/update` ->
`http://localhost:19948/api/shuffleserver/conf/ops/temp/update`
Tested Locally.
```
➜  ~ curl -X POST http://localhost:19948/api/shuffleServer/conf/ops/temp/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.flush.localfile.threadPool.size": "122", "rss.server.flush.thread.alive": "112", "rss.rpc.executor.size": "123"}}'
temporarily effective until restart: Update successfully%
```
=> [#2136][FOLLOWUP] improvement(server,coordinator): Modify the path of update conf rest api

client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
Fix NPE while using DelegationRssShuffleManager in executor
It can encounter NPE if using DelegationRssShuffleManager in executor without this PR.
No.
Tested Locally
=> [MINOR] fix(spark-client): Fix NPE while using DelegationRssShuffleManager in executor

common/src/main/java/org/apache/uniffle/common/metrics/prometheus/PrometheusPushGatewayMetricReporter.java
support dynamic conf the report interval of PrometheusPushGatewayMetricReporter
Adjust the report interval of PrometheusPushGatewayMetricReporter dynamically.
No.
Locally
```
curl  -X POST http://localhost:19948/api/shuffleServer/confOps/update -H "Content-Type: application/json" \
-d '{"update":{"rss.metrics.prometheus.pushgateway.report.interval.seconds": "30"}}'
temporarily effective until restart: Update successfully%
```
server.log
```
[2024-11-04 10:55:24.139] [PrometheusPushGatewayMetricReporter-0] [INFO] PrometheusPushGatewayMetricReporter - Pushed metrics to push gateway
[2024-11-04 10:55:54.460] [PrometheusPushGatewayMetricReporter-0] [ERROR] PrometheusPushGatewayMetricReporter - Failed to send metrics to push gateway.
```
=> [MINOR] improvement(server,coordinator): Dynamic conf support report interval of PrometheusPushGatewayMetricReporter

common/src/main/java/org/apache/uniffle/common/util/OutputUtils.java, common/src/test/java/org/apache/uniffle/common/util/OutputUtilsTest.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java, server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
Introduce OutputUtils class to reduce log size
Fix: #2229
Log become useful but tiny enough.
new UT
=> [#2229] feat(server,client): Introduce `OutputUtils` class to reduce log size

dashboard/src/main/webapp/src/pages/ApplicationPage.vue
Help to find out the most partition num from application page.
No.
Locally
=> [MINOR] improvement(dashboard): Support sort application info by partition num

security.md
Add security.md
Graduation mature assessment
No.
No need.
=> [MINOR] improvement(community): Add security.md

LICENSE-binary, NOTICE
Correct the NOTICE and LICENSE
Follow Justin's suggestion in the mail list of incubator.
No.
No need.
=> [MINOR] Correct the NOTICE and LICENSE

licenses-binary/LICENSE-axios.txt, licenses-binary/LICENSE-core-js.txt, licenses-binary/LICENSE-element-plus.txt, licenses-binary/LICENSE-moment.txt, licenses-binary/LICENSE-vue-resource.txt, licenses-binary/LICENSE-vue-router.txt, licenses-binary/LICENSE-vue.txt
Add left licenses
Follow the Justin's suggestion
No.
No need.
=> [MINOR] build: Add left licenses

deploy/kubernetes/docker/base/centos/Dockerfile
Fix the build of Centos image
Fix #2290
No.
Tested locally.
=> [#2290] docker: Fix the build of Centos image

server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java
followup to correct the metric of grpc_get_local_shuffle_index
Fix: #2298 
No.
=> [#2298] fix(server): followup to correct the metric of grpc_get_local_shuffle_index

NOTICE
Update the year of NOTICE
Fix: #2304
No.
No need.
=> [#2304] improvement: Update the year of NOTICE

LICENSE
Add copyright for PingCAP
Fix: #2305 
No.
No need.
=> [#2305] improvement: Add copyright for PingCAP

NOTICE-binary
Remove repeated notice information
Fix: #2306
No.
No need.
=> [#2306] improvement: Remove repeated notice information

coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/assignment/BasicAssignmentStrategyTest.java, coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/assignment/PartitionBalanceAssignmentStrategyTest.java
Fix NPE for test PartitionBalanceAssignmentStrategyTest 
It will NPE if The metrics have not register to MetricsSystem yet for UTs.
No.
Existing UT.
=> [MINOR] test: fix NPE for test PartitionBalanceAssignmentStrategyTest

integration-test/common/src/test/java/org/apache/uniffle/test/CoordinatorGrpcTest.java
Fix flaky test for CoordinatorGrpcTest
Do some efforts to make CI getting more stable.
No.
Existing UTs.
=> [MINOR] fix(test): Fix flaky test for CoordinatorGrpcTest

storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileNioWriter.java
Support WriteIndex api for LocalFileNioWriter.
- Finish the suggestion left in https://github.com/apache/incubator-uniffle/pull/2223#discussion_r1818333247 
- Introduce the `LocalFileNullDeviceWriter` in the follow up PR.
No.
No need.
=> [MINOR] improvement(server): LocalFileNioWriter support writeIndex api

integration-test/common/src/test/java/org/apache/uniffle/test/QuorumTest.java
extend the timeout value for QuorumTest#case6
Fix: #2333 
No.
current UT
=> [#2333] Improvement: extend the timeout value for QuorumTest#case6

.github/workflows/build.yml, .github/workflows/parallel.yml, .github/workflows/sequential.yml, .github/workflows/single.yml
Upgrade to actions/upload-artifact@v4
fix CI failure
No.
Neen't
=> fix(ci): Upgrade to actions/upload-artifact@v4

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Followup to log more compression infos like data len and compression ratio
followup #2362
No.
Needn't
=> [#2362] feat(client): Log more compression infos

client-spark/spark2-shaded/pom.xml, client-spark/spark3-shaded/pom.xml, client/src/test/java/org/apache/uniffle/client/record/reader/RMRecordsReaderTest.java, client/src/test/java/org/apache/uniffle/client/record/writer/RecordCollectionTest.java, common/pom.xml, common/src/main/java/org/apache/uniffle/common/config/RssBaseConf.java, common/src/main/java/org/apache/uniffle/common/serializer/kryo/KryoDeserializationStream.java, common/src/main/java/org/apache/uniffle/common/serializer/kryo/KryoSerializationStream.java, common/src/main/java/org/apache/uniffle/common/serializer/kryo/KryoSerializer.java, common/src/main/java/org/apache/uniffle/common/serializer/kryo/KryoSerializerInstance.java, common/src/main/java/org/apache/uniffle/common/serializer/kryo/PoolWrapper.java, common/src/test/java/org/apache/uniffle/common/merger/MergerTest.java, common/src/test/java/org/apache/uniffle/common/records/RecordsReaderWriterTest.java, common/src/test/java/org/apache/uniffle/common/serializer/KryoSerializerTest.java, common/src/test/java/org/apache/uniffle/common/serializer/SerializerFactoryTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/RemoteMergeShuffleWithRssClientTestWhenShuffleFlushed.java, pom.xml, server/src/test/java/org/apache/uniffle/server/merge/BlockFlushFileReaderTest.java, server/src/test/java/org/apache/uniffle/server/merge/MergedResultTest.java, server/src/test/java/org/apache/uniffle/server/merge/ShuffleMergeManagerTest.java
Introduce kryo serializer for spark.
#1745
No.
unit test,  real job in cluster
=> [#1745] feat(remote merge): Introduce kryo serializer for spark.

client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/RssShuffleManagerBase.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Add support of partition split for grpc
followup for #2093 
No.
Existing unit tests
=> [#2093][followup] feat: Add support of partition split for grpc

common/src/test/java/org/apache/uniffle/common/KerberizedHadoop.java
This PR improves the `KerberizedHadoop` test base class by addressing two main issues:
1. **Temporary Directory Cleanup**:  
Previously created temporary directories (e.g., `tempDir`, `kerberizedDfsBaseDir`) were not deleted after the test execution, which could lead to filesystem clutter. This PR ensures that they are properly cleaned up in the `tearDown()` method.
2. **Port Allocation Simplification and Safety**:  
Replaced the manual port selection logic (`findAvailablePorts`) with dynamic port allocation by configuring HDFS to use port `0`. This avoids the race condition where manually selected ports may be taken by other processes before being bound.
- To avoid polluting the `/tmp` filesystem with leftover directories.
- To make the test setup more robust and avoid flaky failures …
=> [MINOR] test: clean temp dir and allocate real ports for MiniDFSCluster

.github/workflows/changes.yml
Update dorny/paths-filter@v3 to dorny/paths-filter@v3.0.2
Solve the CI problem.
No.
CI
=> [MINOR] chore(ci): update dorny/paths-filter@v2 to dorny/paths-filter@v3.0.2

internal-client/src/main/java/org/apache/uniffle/client/factory/ShuffleServerClientFactory.java
Remove synchronized in ShuffleServerClientFactory#getShuffleServerClient
For better performance
Fix: #2441
No.
CI
=> [#2441] improvement(client): remove synchronized in ShuffleServerClientFactory#getShuffleServerClient

.github/workflows/changes.yml, .github/workflows/docker.yml, .github/workflows/parallel.yml, .github/workflows/sequential.yml, .github/workflows/single.yml
Drop ubuntu 20.04 and update to the ubuntu-latest
CI failure
No.
Neen't
=> fix(CI): Update CI ubuntu version to latest

docs/dashboard_guide.md
Fixing directory of `rss-env.sh` in documentation.
Directory is incorrect.
No.
N/A
=> [MINOR] fix(docs): Fixing rss-env.sh directory

.github/workflows/docker.yml, deploy/docker/build.sh, deploy/docker/docker-compose.yml, deploy/docker/uniffle/Dockerfile, deploy/docker/uniffle/start.sh
Adding dashboard to the docker images.
There are no dashboard in the docker images.
No.
Tested the docker manually.
=> improvement(docker): Add dashboard to docker

client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala, client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala, client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala, client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java, client/src/main/java/org/apache/uniffle/client/factory/ShuffleClientFactory.java, client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java, client/src/test/java/org/apache/uniffle/client/record/reader/MockedShuffleServerClient.java, docs/client_guide/spark_client_guide.md, internal-client/src/main/java/org/apache/uniffle/client/api/ClientInfo.java, internal-client/src/main/java/org/apache/uniffle/client/api/ShuffleServerClient.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcNettyClient.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleReadMetricRequest.java, storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/MemoryClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/ShuffleServerReadCost.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/ShuffleServerReadCostTracker.java, storage/src/main/java/org/apache/uniffle/storage/request/CreateShuffleReadHandlerRequest.java
1. Add support of read metrics report into UI
2. Add tab of uniffle properties
followup #2460 
No.
Internal tests
=> [#2460] feat(spark)(part-3): Add support of read metrics report

server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java
1. Remove the lock in ShuffleTaskManager#registerShuffle
2. App with heartbeat timeout is not allowed to register again
For better performance
Fix: #2454 
No.
CI
=> [#2454] improvement(server): Remove lock in ShuffleTaskManager#registerShuffle

client-spark/common/src/main/java/org/apache/spark/shuffle/events/ShuffleReadMetric.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java, client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala, client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala, client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala, client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleReadMetricRequest.java, proto/src/main/proto/Rss.proto, storage/src/main/java/org/apache/uniffle/storage/handler/impl/ShuffleServerReadCost.java
1. Add support of hybrid storage reading statistics
followup #2460 
No.
=> [#2460][part-4] feat(spark): Hybrid storage reading statistics

client/src/main/java/org/apache/uniffle/client/impl/ShuffleReadClientImpl.java, client/src/test/java/org/apache/uniffle/client/impl/ShuffleReadClientImplTest.java, common/src/main/java/org/apache/uniffle/common/util/RssUtils.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerFaultToleranceTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHadoopTest.java, integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemoryTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleFlushManagerTest.java, server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java, storage/src/main/java/org/apache/uniffle/storage/factory/ShuffleHandlerFactory.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/DataSkippableReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/LocalFileClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/handler/impl/MultiReplicaClientReadHandler.java, storage/src/main/java/org/apache/uniffle/storage/request/CreateShuffleReadHandlerRequest.java, storage/src/test/java/org/apache/uniffle/storage/handler/impl/HadoopClientReadHandlerTest.java, storage/src/test/java/org/apache/uniffle/storage/handler/impl/HadoopHandlerTest.java, storage/src/test/java/org/apache/uniffle/storage/handler/impl/HadoopShuffleReadHandlerTest.java, storage/src/test/java/org/apache/uniffle/storage/handler/impl/LocalFileServerReadHandlerTest.java
fix potential race condition on reading prefetch
fix #2369
No.
Exsiting tests
=> [#2369] fix(spark): Potential race condition on reading prefetch

client-spark/spark2-shaded/pom.xml, client-spark/spark3-shaded/pom.xml
Exclude kryo when package spark shaded client.
The follow up of #1745.
NoSuchMethodException will be thrown without this pr. 
https://github.com/apache/uniffle/blob/057dcd227286cbfc409b6cfc5787e6057190119b/common/src/main/java/org/apache/uniffle/common/serializer/kryo/KryoSerializerInstance.java#L62
No.
Manual Testing
=> [#1745][FOLLOWUP] fix(client): exclude kryo when package spark shaded client

server/src/main/java/org/apache/uniffle/server/merge/ShuffleMergeManager.java
Print log when merge failed
Currently we don't know the reason why merge failed from the logs.
No.
Manual Testing
=> [MINOR] improvement(remote merge): print log when merge failed

client-spark/common/src/main/java/org/apache/spark/shuffle/events/ShuffleWriteMetric.java, client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java, client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java, client-spark/common/src/test/java/org/apache/spark/shuffle/writer/DataPusherTest.java, client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala, client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala, client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala, client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java, client/src/main/java/org/apache/uniffle/client/response/SendShuffleDataResult.java, internal-client/src/main/java/org/apache/uniffle/client/common/ShuffleServerPushCost.java, internal-client/src/main/java/org/apache/uniffle/client/common/ShuffleServerPushCostTracker.java, internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleWriteMetricRequest.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssSendShuffleDataRequest.java, proto/src/main/proto/Rss.proto
Tracking failure of pushing data for spark UI
More easiler to inspect data writing
Yes.
Internal tests
=> [#2460] feat(spark): Tracking failure of pushing data for spark UI

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/DataPusher.java
closes #2483
Avoid NoSuchElementException error
No.
minor fix
=> [#2483] fix(spark): Avoid NoSuchElementException error

client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala
fix npe
closes #2487
No.
minor fix
=> [#2487] fix(client): Fix NPE in UniffleListener

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
Display memory usage of all consumers under low-memory conditions
for #2490
No.
Existing tests
=> [#2490] feat(spark): Display memory usage of all consumers under low-memory conditions

internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java
Take with bytes for data RPC
For inspecting the latency for RPC with concrate data bytes
No.
Neen't
=> feat(client): Log show with data bytes for each data RPC

client-spark/common/src/main/java/org/apache/spark/shuffle/events/TaskShuffleWriteInfoEvent.java, client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java, client-spark/common/src/main/java/org/apache/uniffle/shuffle/manager/ShuffleManagerGrpcService.java, client-spark/extension/src/main/scala/org/apache/spark/UniffleListener.scala, client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala, client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, internal-client/src/main/java/org/apache/uniffle/client/request/RssReportShuffleWriteMetricRequest.java, proto/src/main/proto/Rss.proto
Show compression ratio into spark UI tab
for #2540
No.
Needn't
=> [#2540] feat(spark): Show compression ratio into spark UI tab

client-spark/extension/src/main/scala/org/apache/spark/UniffleStatusStore.scala, client-spark/extension/src/main/scala/org/apache/spark/ui/ShufflePage.scala
Fix NPE on rendering spark UI tab
closes #2533
No.
minor fix
=> [#2533] fix(client): Fix NPE on rendering spark UI tab

docs/server_guide.md
Add some docs for LAB
Fix: #2527 
No.
CI
=> [#2527] docs: Add some docs for LAB

.asf.yaml
Remove protected branch
Just a minor.
No.
No need.
=> Remove protected branch

cli/src/main/java/org/apache/uniffle/client/HttpClientFactory.java
=> Just a minor

common/src/main/java/org/apache/uniffle/common/ShuffleReadTimes.java
Fix the NPE in `ShuffleReadTimes.merge`
fix #2619
No.
Neen't
=> [#2619] fix(spark): NPE in ShuffleReadTimes.merge
